<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\KS4\SubjectEntries\**" />
    <EmbeddedResource Remove="Entities\KS4\SubjectEntries\**" />
    <None Remove="Entities\KS4\SubjectEntries\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="ServiceModels\KS4\Performance\AdditionalMeasures.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IeuanWalker.GeoUK" Version="1.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    <PackageReference Include="Microsoft.FeatureManagement" Version="4.7.0" />
  </ItemGroup>

</Project>
