<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SAPPub.Core\SAPPub.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="GovukNotify" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.12" />
    <PackageReference Include="IeuanWalker.GeoUK" Version="1.4.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
    <PackageReference Include="MiniProfiler.Shared" Version="4.5.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Spatial4n" Version="0.4.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
