using System.Text;

namespace SAPData.Helpers;

internal static class SqlHelpers
{
    public static void WriteCleanupSql(
        string path, 
        IEnumerable<string> tableNamesToRebuild,
        IEnumerable<string> knownTableNames,
        bool rebuildAllRawTables)
    {
        static List<string> Sorted(IEnumerable<string> names) => [.. names
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)];

        static string SqlArray(List<string> names) => names.Count > 0
            ? $"ARRAY[{string.Join(", ", names.Select(name => $"'{name}'"))}]"
            : "ARRAY[]::text[]";

        var tablesToRebuild = Sorted(tableNamesToRebuild);
        var tablesToKeep = Sorted(knownTableNames.Except(tablesToRebuild, StringComparer.OrdinalIgnoreCase));

        var sql = new StringBuilder(4000);
        sql.AppendLine("-- ================================================================");
        sql.AppendLine("-- 00_cleanup.sql");
        sql.AppendLine("-- Auto-generated by SAPData/Program.cs");
        sql.AppendLine("-- Drops raw tables being rebuilt, and any stale t_table no longer backed by a source file.");
        sql.AppendLine("-- Recreates helper functions used by generated views.");
        sql.AppendLine("-- ================================================================");
        sql.AppendLine(@"\echo 'Ensuring required PostgreSQL extensions...'");
        sql.AppendLine(@"CREATE EXTENSION IF NOT EXISTS postgis;");
        sql.AppendLine();
        sql.AppendLine(@"\echo 'Cleaning up rebuilt and stale raw tables and regenerating helper functions...'");
        sql.AppendLine();
        sql.AppendLine("DO $$");
        sql.AppendLine("DECLARE");
        sql.AppendLine("  v_schema text := current_schema();");
        sql.AppendLine("  r record;");
        sql.AppendLine($"  tables_to_rebuild text[] := {SqlArray(tablesToRebuild)};");
        sql.AppendLine($"  tables_to_keep text[] := {SqlArray(tablesToKeep)};");
        sql.AppendLine("BEGIN");
        sql.AppendLine("  EXECUTE format('SET search_path TO %I', v_schema);");
        sql.AppendLine();
        sql.AppendLine("  -- Drop raw tables being rebuilt, and any generated t_ table not backed by a current source file");
        sql.AppendLine("  FOR r IN");
        sql.AppendLine("    SELECT schemaname, tablename");
        sql.AppendLine("    FROM pg_tables");
        sql.AppendLine("    WHERE schemaname = v_schema");
        sql.AppendLine("      AND tablename LIKE 't\\_%' ESCAPE '\\'");
        if(!rebuildAllRawTables)
        {
            sql.AppendLine("      AND (tablename = ANY(tables_to_rebuild) OR NOT (tablename = ANY(tables_to_keep)))");
        }
        sql.AppendLine("  LOOP");
        sql.AppendLine("   IF NOT (r.tablename = ANY(tables_to_rebuild)) THEN");
        sql.AppendLine("     RAISE NOTICE 'Dropping stale raw table %.%', r.schemaname, r.tablename;");
        sql.AppendLine("   END IF;");
        sql.AppendLine("    EXECUTE format('DROP TABLE IF EXISTS %I.%I CASCADE', r.schemaname, r.tablename);");
        sql.AppendLine("  END LOOP;");
        sql.AppendLine("END $$;");
        sql.AppendLine();
        sql.AppendLine("-- =========================");
        sql.AppendLine("-- Cleaning helpers");
        sql.AppendLine("-- =========================");
        sql.AppendLine();
        sql.AppendLine("CREATE OR REPLACE FUNCTION clean_int(value TEXT)");
        sql.AppendLine("RETURNS INT");
        sql.AppendLine("LANGUAGE plpgsql");
        sql.AppendLine("IMMUTABLE");
        sql.AppendLine("AS $$");
        sql.AppendLine("BEGIN");
        sql.AppendLine("    IF value IS NULL OR trim(value) IN ('', 'NE', 'N', 'na', 'n/a', 'N/A', 'SUPP', '.', '-', '--', 'z') THEN");
        sql.AppendLine("        RETURN NULL;");
        sql.AppendLine("    END IF;");
        sql.AppendLine();
        sql.AppendLine("    RETURN value::INT;");
        sql.AppendLine();
        sql.AppendLine("EXCEPTION WHEN others THEN");
        sql.AppendLine("    RETURN NULL;");
        sql.AppendLine("END;");
        sql.AppendLine("$$;");
        sql.AppendLine();
        sql.AppendLine("CREATE OR REPLACE FUNCTION clean_numeric(value TEXT)");
        sql.AppendLine("RETURNS NUMERIC");
        sql.AppendLine("LANGUAGE plpgsql");
        sql.AppendLine("IMMUTABLE");
        sql.AppendLine("AS $$");
        sql.AppendLine("BEGIN");
        sql.AppendLine("    IF value IS NULL OR trim(value) IN ('', 'NE', 'N', 'na', 'n/a', 'N/A', 'SUPP', '.', '-', '--', 'z') THEN");
        sql.AppendLine("        RETURN NULL;");
        sql.AppendLine("    END IF;");
        sql.AppendLine();
        sql.AppendLine("    RETURN value::NUMERIC;");
        sql.AppendLine();
        sql.AppendLine("EXCEPTION WHEN others THEN");
        sql.AppendLine("    RETURN NULL;");
        sql.AppendLine("END;");
        sql.AppendLine("$$;");
        sql.AppendLine();
        sql.AppendLine("CREATE OR REPLACE FUNCTION clean_date(value TEXT)");
        sql.AppendLine("RETURNS DATE");
        sql.AppendLine("LANGUAGE plpgsql");
        sql.AppendLine("IMMUTABLE");
        sql.AppendLine("AS $$");
        sql.AppendLine("BEGIN");
        sql.AppendLine("    IF value IS NULL OR trim(value) IN ('', 'na', 'n/a', 'N/A', '.', '-', '--') THEN");
        sql.AppendLine("        RETURN NULL;");
        sql.AppendLine("    END IF;");
        sql.AppendLine();
        sql.AppendLine("    RETURN value::DATE;");
        sql.AppendLine();
        sql.AppendLine("EXCEPTION WHEN others THEN");
        sql.AppendLine("    RETURN NULL;");
        sql.AppendLine("END;");
        sql.AppendLine("$$;");
        sql.AppendLine();
        sql.AppendLine("CREATE OR REPLACE FUNCTION public.normalize_text(input_text text)");
        sql.AppendLine("RETURNS text AS $$");
        sql.AppendLine("DECLARE");
        sql.AppendLine("words text[];");
        sql.AppendLine("w text;");
        sql.AppendLine("syn text;");
        sql.AppendLine("normalized_words text[];");
        sql.AppendLine("BEGIN");
        sql.AppendLine("-- Split the input into words");
        sql.AppendLine("    words := regexp_split_to_array(lower(input_text), '\\s+');");
        sql.AppendLine("    FOREACH w IN ARRAY words LOOP");
        sql.AppendLine("        SELECT synonym INTO syn FROM public.thesaurus_synonyms WHERE word = w LIMIT 1;");
        sql.AppendLine("        normalized_words := array_append(normalized_words, COALESCE(syn, w));");
        sql.AppendLine("    END LOOP;");
        sql.AppendLine("    RETURN array_to_string(normalized_words, ' ');");
        sql.AppendLine("END;");
        sql.AppendLine("$$ LANGUAGE plpgsql IMMUTABLE;");
        sql.AppendLine();
        sql.AppendLine(@"\echo 'Cleanup complete.'");

        File.WriteAllText(path, sql.ToString(), new UTF8Encoding(false));
    }

}
