#
#   Little Powershell script to extract the headers from all CSV files in a given directory and write them to a Markdown file.
#
#   Navigate to the directory containing this script and run it. It will create a file named 'csv_headers.md' in the same directory, listing the headers of all CSV files found.
#
#   To run the script, you can use the following command in PowerShell:
#   .\Extract-CsvHeaders.ps1 -Path "C:\Path\To\Your\CSV\Files" -OutputFile "C:\Path\To\Your\Output\csv_headers.md"
#   or simply run it without parameters to use the current directory and default output file name.
#   .\Extract-CsvHeaders.ps1 in the SourceFiles directory
#



param(
    [string]$Path = (Split-Path -Parent $MyInvocation.MyCommand.Path),
    [string]$OutputFile = (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) '005-csv-headers.md'),
    [string]$Intro = 'This document lists the column names found in each CSV file. This is autogenerated from the "Extract-CsvHeaders.ps1" script, do not update this file directly. If you need to update the headers, please update the CSV files and rerun the script. '
)

$resolvedPath = Resolve-Path $Path
$csvFiles = Get-ChildItem -Path $resolvedPath -Filter *.csv | Sort-Object Name

$lines = @(
    '# CSV Headers',
    '',
    $Intro,
    ''
)

foreach ($csv in $csvFiles) {
    $lines += "## $($csv.Name)"
    $lines += ''

    try {
        $firstLine = Get-Content -Path $csv.FullName -TotalCount 1 -ErrorAction Stop

        if ([string]::IsNullOrWhiteSpace($firstLine)) {
            $lines += '- (no header row found)'
        }
        else {
            $delimiter = ','
            $commaCount = ($firstLine.ToCharArray() | Where-Object { $_ -eq ',' }).Count
            $semicolonCount = ($firstLine.ToCharArray() | Where-Object { $_ -eq ';' }).Count

            if ($semicolonCount -gt $commaCount) {
                $delimiter = ';'
            }

            $headerFields = $firstLine -split [regex]::Escape($delimiter)
            $headerFields = $headerFields | ForEach-Object { $_.Trim().Trim('"') }

            if ($null -ne $headerFields -and $headerFields.Count -gt 0) {
                foreach ($field in $headerFields) {
                    $lines += "- $field"
                }
            }
            else {
                $lines += '- (no header row found)'
            }
        }
    }
    catch {
        $lines += "- Error reading file: $($_.Exception.Message)"
    }

    $lines += ''
    $lines += ''
}

$lines | Set-Content -Path $OutputFile -Encoding UTF8
Write-Host "Processed $($csvFiles.Count) CSV files. Output written to $OutputFile"
