-- ================================================================
-- 01_create_raw_tables.sql
-- NOTE: This project generates RAW tables from CSV headers in C#.
-- If you already generated this file, you can ignore this wrapper.
-- ================================================================

\echo '01_create_raw_tables.sql is generated by the C# tool (GenerateRawTables).'