-- ================================================================
-- 02_copy_into_raw.sql
-- NOTE: This project generates COPY commands in C#.
-- If you already generated this file, you can ignore this wrapper.
-- ================================================================

\echo '02_copy_into_raw.sql is generated by the C# tool (GenerateRawTables).'