-- AUTO-GENERATED MATERIALIZED VIEW: v_la_destinations

DROP MATERIALIZED VIEW IF EXISTS v_la_destinations;

CREATE MATERIALIZED VIEW v_la_destinations AS
WITH
src_1 AS (
    SELECT
        t."old_la_code" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."overall"::text END) AS "AllDest_Boy_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."overall"::text END) AS "AllDest_Boy_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."overall"::text END) AS "AllDest_Dis_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."overall"::text END) AS "AllDest_Dis_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."overall"::text END) AS "AllDest_Grl_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."overall"::text END) AS "AllDest_Grl_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."overall"::text END) AS "AllDest_NDi_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."overall"::text END) AS "AllDest_NDi_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."overall"::text END) AS "AllDest_Tot_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."education"::text END) AS "Education_Boy_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."education"::text END) AS "Education_Boy_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."education"::text END) AS "Education_Dis_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."education"::text END) AS "Education_Dis_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."education"::text END) AS "Education_Grl_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."education"::text END) AS "Education_Grl_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."education"::text END) AS "Education_NDi_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."education"::text END) AS "Education_NDi_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."education"::text END) AS "Education_Tot_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."all_work"::text END) AS "Employment_Boy_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."all_work"::text END) AS "Employment_Boy_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."all_work"::text END) AS "Employment_Dis_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."all_work"::text END) AS "Employment_Dis_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."all_work"::text END) AS "Employment_Grl_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."all_work"::text END) AS "Employment_Grl_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."all_work"::text END) AS "Employment_NDi_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."all_work"::text END) AS "Employment_NDi_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."all_work"::text END) AS "Employment_Tot_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."appren"::text END) AS "Apprentice_Boy_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."appren"::text END) AS "Apprentice_Boy_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."appren"::text END) AS "Apprentice_Dis_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."appren"::text END) AS "Apprentice_Dis_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."appren"::text END) AS "Apprentice_Grl_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."appren"::text END) AS "Apprentice_Grl_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."appren"::text END) AS "Apprentice_NDi_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."appren"::text END) AS "Apprentice_NDi_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of Students' AND t."time_period" = '202223' AND t."institution_group" = 'State-funded mainstream and special' THEN t."appren"::text END) AS "Apprentice_Tot_LA_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream schools' AND t."time_period" = '202223' AND t."institution_type" = 'Total' THEN t."overall"::text END) AS "AllDest_Tot_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream schools' AND t."time_period" = '202223' AND t."institution_type" = 'Total' THEN t."education"::text END) AS "Education_Tot_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream schools' AND t."time_period" = '202223' AND t."institution_type" = 'Total' THEN t."all_work"::text END) AS "Employment_Tot_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream schools' AND t."time_period" = '202223' AND t."institution_type" = 'Total' THEN t."appren"::text END) AS "Apprentice_Tot_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream schools' AND t."time_period" = '202122' AND t."institution_type" = 'Total' THEN t."overall"::text END) AS "AllDest_Tot_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream schools' AND t."time_period" = '202122' AND t."institution_type" = 'Total' THEN t."education"::text END) AS "Education_Tot_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream schools' AND t."time_period" = '202122' AND t."institution_type" = 'Total' THEN t."all_work"::text END) AS "Employment_Tot_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream schools' AND t."time_period" = '202122' AND t."institution_type" = 'Total' THEN t."appren"::text END) AS "Apprentice_Tot_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream schools' AND t."time_period" = '202021' AND t."institution_type" = 'Total' THEN t."overall"::text END) AS "AllDest_Tot_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream schools' AND t."time_period" = '202021' AND t."institution_type" = 'Total' THEN t."education"::text END) AS "Education_Tot_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream schools' AND t."time_period" = '202021' AND t."institution_type" = 'Total' THEN t."all_work"::text END) AS "Employment_Tot_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream schools' AND t."time_period" = '202021' AND t."institution_type" = 'Total' THEN t."appren"::text END) AS "Apprentice_Tot_LA_Previous2_Pct_Coded"
    FROM t_ees_ks4_la_202223_77d7d16802 t
    GROUP BY t."old_la_code"
)
,
src_2 AS (
    SELECT
        t."old_la_code" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."overall"::text END) AS "AllDest_Boy_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."overall"::text END) AS "AllDest_Boy_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."overall"::text END) AS "AllDest_Dis_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."overall"::text END) AS "AllDest_Dis_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."overall"::text END) AS "AllDest_Grl_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."overall"::text END) AS "AllDest_Grl_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."overall"::text END) AS "AllDest_NDi_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."overall"::text END) AS "AllDest_NDi_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."overall"::text END) AS "AllDest_Tot_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."education"::text END) AS "Education_Boy_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."education"::text END) AS "Education_Boy_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."education"::text END) AS "Education_Dis_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."education"::text END) AS "Education_Dis_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."education"::text END) AS "Education_Grl_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."education"::text END) AS "Education_Grl_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."education"::text END) AS "Education_NDi_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."education"::text END) AS "Education_NDi_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."education"::text END) AS "Education_Tot_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."all_work"::text END) AS "Employment_Boy_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."all_work"::text END) AS "Employment_Boy_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."all_work"::text END) AS "Employment_Dis_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."all_work"::text END) AS "Employment_Dis_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."all_work"::text END) AS "Employment_Grl_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."all_work"::text END) AS "Employment_Grl_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."all_work"::text END) AS "Employment_NDi_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."all_work"::text END) AS "Employment_NDi_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."all_work"::text END) AS "Employment_Tot_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."appren"::text END) AS "Apprentice_Boy_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."appren"::text END) AS "Apprentice_Boy_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."appren"::text END) AS "Apprentice_Dis_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."appren"::text END) AS "Apprentice_Dis_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."appren"::text END) AS "Apprentice_Grl_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."appren"::text END) AS "Apprentice_Grl_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."appren"::text END) AS "Apprentice_NDi_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."appren"::text END) AS "Apprentice_NDi_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202223' THEN t."appren"::text END) AS "Apprentice_Tot_LA_Previous_Num_Coded"
    FROM t_ks4_dm_ud_202223_la__c3b076dcd1 t
    GROUP BY t."old_la_code"
)
,
src_3 AS (
    SELECT
        t."old_la_code" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."overall"::text END) AS "AllDest_Boy_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."overall"::text END) AS "AllDest_Boy_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."overall"::text END) AS "AllDest_Dis_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."overall"::text END) AS "AllDest_Dis_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."overall"::text END) AS "AllDest_Grl_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."overall"::text END) AS "AllDest_Grl_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."overall"::text END) AS "AllDest_NDi_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."overall"::text END) AS "AllDest_NDi_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."overall"::text END) AS "AllDest_Tot_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."education"::text END) AS "Education_Boy_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."education"::text END) AS "Education_Boy_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."education"::text END) AS "Education_Dis_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."education"::text END) AS "Education_Dis_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."education"::text END) AS "Education_Grl_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."education"::text END) AS "Education_Grl_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."education"::text END) AS "Education_NDi_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."education"::text END) AS "Education_NDi_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."education"::text END) AS "Education_Tot_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."all_work"::text END) AS "Employment_Boy_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."all_work"::text END) AS "Employment_Boy_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."all_work"::text END) AS "Employment_Dis_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."all_work"::text END) AS "Employment_Dis_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."all_work"::text END) AS "Employment_Grl_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."all_work"::text END) AS "Employment_Grl_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."all_work"::text END) AS "Employment_NDi_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."all_work"::text END) AS "Employment_NDi_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."all_work"::text END) AS "Employment_Tot_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."appren"::text END) AS "Apprentice_Boy_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."appren"::text END) AS "Apprentice_Boy_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."appren"::text END) AS "Apprentice_Dis_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."appren"::text END) AS "Apprentice_Dis_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."appren"::text END) AS "Apprentice_Grl_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."appren"::text END) AS "Apprentice_Grl_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."appren"::text END) AS "Apprentice_NDi_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."appren"::text END) AS "Apprentice_NDi_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' AND t."institution_group" = 'State-funded mainstream & special schools' AND t."time_period" = '202122' THEN t."appren"::text END) AS "Apprentice_Tot_LA_Previous2_Num_Coded"
    FROM t_ks4_dm_ud_202122_la__f22330973f t
    GROUP BY t."old_la_code"
)
,
all_ids AS (
    SELECT "Id" FROM src_1
    UNION SELECT "Id" FROM src_2
    UNION SELECT "Id" FROM src_3
)

SELECT
    a."Id" AS "Id",
    src_1."AllDest_Boy_LA_Current_Num_Coded" AS "AllDest_Boy_LA_Current_Num_Coded",
    src_1."AllDest_Boy_LA_Current_Pct_Coded" AS "AllDest_Boy_LA_Current_Pct_Coded",
    src_2."AllDest_Boy_LA_Previous_Num_Coded" AS "AllDest_Boy_LA_Previous_Num_Coded",
    src_2."AllDest_Boy_LA_Previous_Pct_Coded" AS "AllDest_Boy_LA_Previous_Pct_Coded",
    src_3."AllDest_Boy_LA_Previous2_Num_Coded" AS "AllDest_Boy_LA_Previous2_Num_Coded",
    src_3."AllDest_Boy_LA_Previous2_Pct_Coded" AS "AllDest_Boy_LA_Previous2_Pct_Coded",
    src_1."AllDest_Dis_LA_Current_Num_Coded" AS "AllDest_Dis_LA_Current_Num_Coded",
    src_1."AllDest_Dis_LA_Current_Pct_Coded" AS "AllDest_Dis_LA_Current_Pct_Coded",
    src_2."AllDest_Dis_LA_Previous_Num_Coded" AS "AllDest_Dis_LA_Previous_Num_Coded",
    src_2."AllDest_Dis_LA_Previous_Pct_Coded" AS "AllDest_Dis_LA_Previous_Pct_Coded",
    src_3."AllDest_Dis_LA_Previous2_Num_Coded" AS "AllDest_Dis_LA_Previous2_Num_Coded",
    src_3."AllDest_Dis_LA_Previous2_Pct_Coded" AS "AllDest_Dis_LA_Previous2_Pct_Coded",
    src_1."AllDest_Grl_LA_Current_Num_Coded" AS "AllDest_Grl_LA_Current_Num_Coded",
    src_1."AllDest_Grl_LA_Current_Pct_Coded" AS "AllDest_Grl_LA_Current_Pct_Coded",
    src_2."AllDest_Grl_LA_Previous_Num_Coded" AS "AllDest_Grl_LA_Previous_Num_Coded",
    src_2."AllDest_Grl_LA_Previous_Pct_Coded" AS "AllDest_Grl_LA_Previous_Pct_Coded",
    src_3."AllDest_Grl_LA_Previous2_Num_Coded" AS "AllDest_Grl_LA_Previous2_Num_Coded",
    src_3."AllDest_Grl_LA_Previous2_Pct_Coded" AS "AllDest_Grl_LA_Previous2_Pct_Coded",
    src_1."AllDest_NDi_LA_Current_Num_Coded" AS "AllDest_NDi_LA_Current_Num_Coded",
    src_1."AllDest_NDi_LA_Current_Pct_Coded" AS "AllDest_NDi_LA_Current_Pct_Coded",
    src_2."AllDest_NDi_LA_Previous_Num_Coded" AS "AllDest_NDi_LA_Previous_Num_Coded",
    src_2."AllDest_NDi_LA_Previous_Pct_Coded" AS "AllDest_NDi_LA_Previous_Pct_Coded",
    src_3."AllDest_NDi_LA_Previous2_Num_Coded" AS "AllDest_NDi_LA_Previous2_Num_Coded",
    src_3."AllDest_NDi_LA_Previous2_Pct_Coded" AS "AllDest_NDi_LA_Previous2_Pct_Coded",
    src_1."AllDest_Tot_LA_Current_Num_Coded" AS "AllDest_Tot_LA_Current_Num_Coded",
    src_1."AllDest_Tot_LA_Current_Pct_Coded" AS "AllDest_Tot_LA_Current_Pct_Coded",
    src_2."AllDest_Tot_LA_Previous_Num_Coded" AS "AllDest_Tot_LA_Previous_Num_Coded",
    src_1."AllDest_Tot_LA_Previous_Pct_Coded" AS "AllDest_Tot_LA_Previous_Pct_Coded",
    src_3."AllDest_Tot_LA_Previous2_Num_Coded" AS "AllDest_Tot_LA_Previous2_Num_Coded",
    src_1."AllDest_Tot_LA_Previous2_Pct_Coded" AS "AllDest_Tot_LA_Previous2_Pct_Coded",
    src_1."Apprentice_Boy_LA_Current_Num_Coded" AS "Apprentice_Boy_LA_Current_Num_Coded",
    src_1."Apprentice_Boy_LA_Current_Pct_Coded" AS "Apprentice_Boy_LA_Current_Pct_Coded",
    src_2."Apprentice_Boy_LA_Previous_Num_Coded" AS "Apprentice_Boy_LA_Previous_Num_Coded",
    src_2."Apprentice_Boy_LA_Previous_Pct_Coded" AS "Apprentice_Boy_LA_Previous_Pct_Coded",
    src_3."Apprentice_Boy_LA_Previous2_Num_Coded" AS "Apprentice_Boy_LA_Previous2_Num_Coded",
    src_3."Apprentice_Boy_LA_Previous2_Pct_Coded" AS "Apprentice_Boy_LA_Previous2_Pct_Coded",
    src_1."Apprentice_Dis_LA_Current_Num_Coded" AS "Apprentice_Dis_LA_Current_Num_Coded",
    src_1."Apprentice_Dis_LA_Current_Pct_Coded" AS "Apprentice_Dis_LA_Current_Pct_Coded",
    src_2."Apprentice_Dis_LA_Previous_Num_Coded" AS "Apprentice_Dis_LA_Previous_Num_Coded",
    src_2."Apprentice_Dis_LA_Previous_Pct_Coded" AS "Apprentice_Dis_LA_Previous_Pct_Coded",
    src_3."Apprentice_Dis_LA_Previous2_Num_Coded" AS "Apprentice_Dis_LA_Previous2_Num_Coded",
    src_3."Apprentice_Dis_LA_Previous2_Pct_Coded" AS "Apprentice_Dis_LA_Previous2_Pct_Coded",
    src_1."Apprentice_Grl_LA_Current_Num_Coded" AS "Apprentice_Grl_LA_Current_Num_Coded",
    src_1."Apprentice_Grl_LA_Current_Pct_Coded" AS "Apprentice_Grl_LA_Current_Pct_Coded",
    src_2."Apprentice_Grl_LA_Previous_Num_Coded" AS "Apprentice_Grl_LA_Previous_Num_Coded",
    src_2."Apprentice_Grl_LA_Previous_Pct_Coded" AS "Apprentice_Grl_LA_Previous_Pct_Coded",
    src_3."Apprentice_Grl_LA_Previous2_Num_Coded" AS "Apprentice_Grl_LA_Previous2_Num_Coded",
    src_3."Apprentice_Grl_LA_Previous2_Pct_Coded" AS "Apprentice_Grl_LA_Previous2_Pct_Coded",
    src_1."Apprentice_NDi_LA_Current_Num_Coded" AS "Apprentice_NDi_LA_Current_Num_Coded",
    src_1."Apprentice_NDi_LA_Current_Pct_Coded" AS "Apprentice_NDi_LA_Current_Pct_Coded",
    src_2."Apprentice_NDi_LA_Previous_Num_Coded" AS "Apprentice_NDi_LA_Previous_Num_Coded",
    src_2."Apprentice_NDi_LA_Previous_Pct_Coded" AS "Apprentice_NDi_LA_Previous_Pct_Coded",
    src_3."Apprentice_NDi_LA_Previous2_Num_Coded" AS "Apprentice_NDi_LA_Previous2_Num_Coded",
    src_3."Apprentice_NDi_LA_Previous2_Pct_Coded" AS "Apprentice_NDi_LA_Previous2_Pct_Coded",
    src_1."Apprentice_Tot_LA_Current_Num_Coded" AS "Apprentice_Tot_LA_Current_Num_Coded",
    src_1."Apprentice_Tot_LA_Current_Pct_Coded" AS "Apprentice_Tot_LA_Current_Pct_Coded",
    src_2."Apprentice_Tot_LA_Previous_Num_Coded" AS "Apprentice_Tot_LA_Previous_Num_Coded",
    src_1."Apprentice_Tot_LA_Previous_Pct_Coded" AS "Apprentice_Tot_LA_Previous_Pct_Coded",
    src_3."Apprentice_Tot_LA_Previous2_Num_Coded" AS "Apprentice_Tot_LA_Previous2_Num_Coded",
    src_1."Apprentice_Tot_LA_Previous2_Pct_Coded" AS "Apprentice_Tot_LA_Previous2_Pct_Coded",
    src_1."Education_Boy_LA_Current_Num_Coded" AS "Education_Boy_LA_Current_Num_Coded",
    src_1."Education_Boy_LA_Current_Pct_Coded" AS "Education_Boy_LA_Current_Pct_Coded",
    src_2."Education_Boy_LA_Previous_Num_Coded" AS "Education_Boy_LA_Previous_Num_Coded",
    src_2."Education_Boy_LA_Previous_Pct_Coded" AS "Education_Boy_LA_Previous_Pct_Coded",
    src_3."Education_Boy_LA_Previous2_Num_Coded" AS "Education_Boy_LA_Previous2_Num_Coded",
    src_3."Education_Boy_LA_Previous2_Pct_Coded" AS "Education_Boy_LA_Previous2_Pct_Coded",
    src_1."Education_Dis_LA_Current_Num_Coded" AS "Education_Dis_LA_Current_Num_Coded",
    src_1."Education_Dis_LA_Current_Pct_Coded" AS "Education_Dis_LA_Current_Pct_Coded",
    src_2."Education_Dis_LA_Previous_Num_Coded" AS "Education_Dis_LA_Previous_Num_Coded",
    src_2."Education_Dis_LA_Previous_Pct_Coded" AS "Education_Dis_LA_Previous_Pct_Coded",
    src_3."Education_Dis_LA_Previous2_Num_Coded" AS "Education_Dis_LA_Previous2_Num_Coded",
    src_3."Education_Dis_LA_Previous2_Pct_Coded" AS "Education_Dis_LA_Previous2_Pct_Coded",
    src_1."Education_Grl_LA_Current_Num_Coded" AS "Education_Grl_LA_Current_Num_Coded",
    src_1."Education_Grl_LA_Current_Pct_Coded" AS "Education_Grl_LA_Current_Pct_Coded",
    src_2."Education_Grl_LA_Previous_Num_Coded" AS "Education_Grl_LA_Previous_Num_Coded",
    src_2."Education_Grl_LA_Previous_Pct_Coded" AS "Education_Grl_LA_Previous_Pct_Coded",
    src_3."Education_Grl_LA_Previous2_Num_Coded" AS "Education_Grl_LA_Previous2_Num_Coded",
    src_3."Education_Grl_LA_Previous2_Pct_Coded" AS "Education_Grl_LA_Previous2_Pct_Coded",
    src_1."Education_NDi_LA_Current_Num_Coded" AS "Education_NDi_LA_Current_Num_Coded",
    src_1."Education_NDi_LA_Current_Pct_Coded" AS "Education_NDi_LA_Current_Pct_Coded",
    src_2."Education_NDi_LA_Previous_Num_Coded" AS "Education_NDi_LA_Previous_Num_Coded",
    src_2."Education_NDi_LA_Previous_Pct_Coded" AS "Education_NDi_LA_Previous_Pct_Coded",
    src_3."Education_NDi_LA_Previous2_Num_Coded" AS "Education_NDi_LA_Previous2_Num_Coded",
    src_3."Education_NDi_LA_Previous2_Pct_Coded" AS "Education_NDi_LA_Previous2_Pct_Coded",
    src_1."Education_Tot_LA_Current_Num_Coded" AS "Education_Tot_LA_Current_Num_Coded",
    src_1."Education_Tot_LA_Current_Pct_Coded" AS "Education_Tot_LA_Current_Pct_Coded",
    src_2."Education_Tot_LA_Previous_Num_Coded" AS "Education_Tot_LA_Previous_Num_Coded",
    src_1."Education_Tot_LA_Previous_Pct_Coded" AS "Education_Tot_LA_Previous_Pct_Coded",
    src_3."Education_Tot_LA_Previous2_Num_Coded" AS "Education_Tot_LA_Previous2_Num_Coded",
    src_1."Education_Tot_LA_Previous2_Pct_Coded" AS "Education_Tot_LA_Previous2_Pct_Coded",
    src_1."Employment_Boy_LA_Current_Num_Coded" AS "Employment_Boy_LA_Current_Num_Coded",
    src_1."Employment_Boy_LA_Current_Pct_Coded" AS "Employment_Boy_LA_Current_Pct_Coded",
    src_2."Employment_Boy_LA_Previous_Num_Coded" AS "Employment_Boy_LA_Previous_Num_Coded",
    src_2."Employment_Boy_LA_Previous_Pct_Coded" AS "Employment_Boy_LA_Previous_Pct_Coded",
    src_3."Employment_Boy_LA_Previous2_Num_Coded" AS "Employment_Boy_LA_Previous2_Num_Coded",
    src_3."Employment_Boy_LA_Previous2_Pct_Coded" AS "Employment_Boy_LA_Previous2_Pct_Coded",
    src_1."Employment_Dis_LA_Current_Num_Coded" AS "Employment_Dis_LA_Current_Num_Coded",
    src_1."Employment_Dis_LA_Current_Pct_Coded" AS "Employment_Dis_LA_Current_Pct_Coded",
    src_2."Employment_Dis_LA_Previous_Num_Coded" AS "Employment_Dis_LA_Previous_Num_Coded",
    src_2."Employment_Dis_LA_Previous_Pct_Coded" AS "Employment_Dis_LA_Previous_Pct_Coded",
    src_3."Employment_Dis_LA_Previous2_Num_Coded" AS "Employment_Dis_LA_Previous2_Num_Coded",
    src_3."Employment_Dis_LA_Previous2_Pct_Coded" AS "Employment_Dis_LA_Previous2_Pct_Coded",
    src_1."Employment_Grl_LA_Current_Num_Coded" AS "Employment_Grl_LA_Current_Num_Coded",
    src_1."Employment_Grl_LA_Current_Pct_Coded" AS "Employment_Grl_LA_Current_Pct_Coded",
    src_2."Employment_Grl_LA_Previous_Num_Coded" AS "Employment_Grl_LA_Previous_Num_Coded",
    src_2."Employment_Grl_LA_Previous_Pct_Coded" AS "Employment_Grl_LA_Previous_Pct_Coded",
    src_3."Employment_Grl_LA_Previous2_Num_Coded" AS "Employment_Grl_LA_Previous2_Num_Coded",
    src_3."Employment_Grl_LA_Previous2_Pct_Coded" AS "Employment_Grl_LA_Previous2_Pct_Coded",
    src_1."Employment_NDi_LA_Current_Num_Coded" AS "Employment_NDi_LA_Current_Num_Coded",
    src_1."Employment_NDi_LA_Current_Pct_Coded" AS "Employment_NDi_LA_Current_Pct_Coded",
    src_2."Employment_NDi_LA_Previous_Num_Coded" AS "Employment_NDi_LA_Previous_Num_Coded",
    src_2."Employment_NDi_LA_Previous_Pct_Coded" AS "Employment_NDi_LA_Previous_Pct_Coded",
    src_3."Employment_NDi_LA_Previous2_Num_Coded" AS "Employment_NDi_LA_Previous2_Num_Coded",
    src_3."Employment_NDi_LA_Previous2_Pct_Coded" AS "Employment_NDi_LA_Previous2_Pct_Coded",
    src_1."Employment_Tot_LA_Current_Num_Coded" AS "Employment_Tot_LA_Current_Num_Coded",
    src_1."Employment_Tot_LA_Current_Pct_Coded" AS "Employment_Tot_LA_Current_Pct_Coded",
    src_2."Employment_Tot_LA_Previous_Num_Coded" AS "Employment_Tot_LA_Previous_Num_Coded",
    src_1."Employment_Tot_LA_Previous_Pct_Coded" AS "Employment_Tot_LA_Previous_Pct_Coded",
    src_3."Employment_Tot_LA_Previous2_Num_Coded" AS "Employment_Tot_LA_Previous2_Num_Coded",
    src_1."Employment_Tot_LA_Previous2_Pct_Coded" AS "Employment_Tot_LA_Previous2_Pct_Coded"
FROM all_ids a
LEFT JOIN src_1 ON src_1."Id" = a."Id"
LEFT JOIN src_2 ON src_2."Id" = a."Id"
LEFT JOIN src_3 ON src_3."Id" = a."Id"
;
