-- AUTO-GENERATED MATERIALIZED VIEW: v_establishment_performance

DROP MATERIALIZED VIEW IF EXISTS v_establishment_performance;

CREATE MATERIALIZED VIEW v_establishment_performance AS
WITH
src_1 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."attainment8_average"::text END) AS "Attainment8_Tot_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."engmath_94_percent"::text END) AS "EngMaths49_Boy_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."engmath_94_percent"::text END) AS "EngMaths49_Grl_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."engmath_94_percent"::text END) AS "EngMaths49_Tot_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."engmath_95_percent"::text END) AS "EngMaths59_Boy_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."engmath_95_percent"::text END) AS "EngMaths59_Grl_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."engmath_94_total"::text END) AS "EngMaths49_Tot_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."engmath_95_percent"::text END) AS "EngMaths59_Tot_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."engmath_95_total"::text END) AS "EngMaths59_Tot_Est_Current_Num_Coded"
    FROM t_202425_performance_t_5fd3fc6827 t
    GROUP BY t."school_urn"
)
,
src_2 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."attainment8_average"::text END) AS "Attainment8_Boy_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."attainment8_average"::text END) AS "Attainment8_Dis_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."attainment8_average"::text END) AS "Attainment8_EAL_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."attainment8_average"::text END) AS "Attainment8_Grl_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN t."attainment8_average"::text END) AS "Attainment8_NDi_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."attainment8_average"::text END) AS "Attainment8_NMo_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."engmath_94_total"::text END) AS "EngMaths49_Boy_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."engmath_94_total"::text END) AS "EngMaths49_Dis_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."engmath_94_percent"::text END) AS "EngMaths49_Dis_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."engmath_94_total"::text END) AS "EngMaths49_EAL_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."engmath_94_percent"::text END) AS "EngMaths49_EAL_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."engmath_94_total"::text END) AS "EngMaths49_Grl_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN t."engmath_94_total"::text END) AS "EngMaths49_NDi_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN t."engmath_94_percent"::text END) AS "EngMaths49_NDi_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."engmath_94_total"::text END) AS "EngMaths49_NMo_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."engmath_94_percent"::text END) AS "EngMaths49_NMo_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."engmath_95_total"::text END) AS "EngMaths59_Boy_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."engmath_95_total"::text END) AS "EngMaths59_Dis_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."engmath_95_percent"::text END) AS "EngMaths59_Dis_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."engmath_95_total"::text END) AS "EngMaths59_EAL_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."engmath_95_percent"::text END) AS "EngMaths59_EAL_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."engmath_95_total"::text END) AS "EngMaths59_Grl_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN t."engmath_95_total"::text END) AS "EngMaths59_NDi_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN t."engmath_95_percent"::text END) AS "EngMaths59_NDi_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."engmath_95_total"::text END) AS "EngMaths59_NMo_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."engmath_95_percent"::text END) AS "EngMaths59_NMo_Est_Current_Pct_Coded"
    FROM t_202425_performance_t_7d6e7188b9 t
    GROUP BY t."school_urn"
)
,
src_3 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."avg_att8"::text END) AS "Attainment8_Tot_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."pt_l2basics_94"::text END) AS "EngMaths49_Tot_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."pt_l2basics_95"::text END) AS "EngMaths59_Tot_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."avg_p8score"::text END) AS "Prog8_Tot_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."p8score_ci_low"::text END) AS "Prog8_CI_Lower_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."p8score_ci_upp"::text END) AS "Prog8_CI_Upper_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."t_l2basics_95"::text END) AS "EngMaths59_Tot_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."avg_att8"::text END) AS "Attainment8_Boy_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."avg_att8"::text END) AS "Attainment8_Dis_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."avg_att8"::text END) AS "Attainment8_EAL_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."avg_att8"::text END) AS "Attainment8_Grl_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."avg_att8"::text END) AS "Attainment8_NMo_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."t_l2basics_94"::text END) AS "EngMaths49_Boy_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."pt_l2basics_94"::text END) AS "EngMaths49_Boy_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."t_l2basics_94"::text END) AS "EngMaths49_Dis_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."pt_l2basics_94"::text END) AS "EngMaths49_Dis_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."t_l2basics_94"::text END) AS "EngMaths49_EAL_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."pt_l2basics_94"::text END) AS "EngMaths49_EAL_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."t_l2basics_94"::text END) AS "EngMaths49_Grl_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."pt_l2basics_94"::text END) AS "EngMaths49_Grl_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."t_l2basics_94"::text END) AS "EngMaths49_NMo_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."pt_l2basics_94"::text END) AS "EngMaths49_NMo_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."t_l2basics_94"::text END) AS "EngMaths49_Tot_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."t_l2basics_95"::text END) AS "EngMaths59_Boy_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."pt_l2basics_95"::text END) AS "EngMaths59_Boy_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."t_l2basics_95"::text END) AS "EngMaths59_Dis_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."pt_l2basics_95"::text END) AS "EngMaths59_Dis_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."t_l2basics_95"::text END) AS "EngMaths59_EAL_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."pt_l2basics_95"::text END) AS "EngMaths59_EAL_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."t_l2basics_95"::text END) AS "EngMaths59_Grl_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."pt_l2basics_95"::text END) AS "EngMaths59_Grl_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."t_l2basics_95"::text END) AS "EngMaths59_NMo_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."pt_l2basics_95"::text END) AS "EngMaths59_NMo_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."t_pupils"::text END) AS "Pup_Tot_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."t_inp8calc"::text END) AS "Prog8_TotPup_Est_Previous_Num_Coded"
    FROM t_202324_performance_t_371eb4e56c t
    GROUP BY t."school_urn"
)
,
src_4 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving"::text END) AS "Bio49_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving"::text END) AS "Bio59_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '7+8+9' THEN t."number_achieving"::text END) AS "Bio79_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving"::text END) AS "Chem49_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving"::text END) AS "Chem59_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '7+8+9' THEN t."number_achieving"::text END) AS "Chem79_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99+98+88+87+77+76+66+65+55+54+44' THEN t."number_achieving"::text END) AS "CombSci49_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99+98+88+87+77+76+66+65+55' THEN t."number_achieving"::text END) AS "CombSci59_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99+98+88+87+77' THEN t."number_achieving"::text END) AS "CombSci79_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving"::text END) AS "EngLang49_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving"::text END) AS "EngLang59_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7+8+9' THEN t."number_achieving"::text END) AS "EngLang79_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving"::text END) AS "EngLit49_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving"::text END) AS "EngLit59_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7+8+9' THEN t."number_achieving"::text END) AS "EngLit79_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving"::text END) AS "Maths49_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving"::text END) AS "Maths59_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7+8+9' THEN t."number_achieving"::text END) AS "Maths79_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving"::text END) AS "Physics49_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving"::text END) AS "Physics59_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7+8+9' THEN t."number_achieving"::text END) AS "Physics79_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4' THEN t."number_achieving"::text END) AS "Bio4_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '5' THEN t."number_achieving"::text END) AS "Bio5_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '6' THEN t."number_achieving"::text END) AS "Bio6_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '7' THEN t."number_achieving"::text END) AS "Bio7_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '8' THEN t."number_achieving"::text END) AS "Bio8_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '9' THEN t."number_achieving"::text END) AS "Bio9_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4' THEN t."number_achieving"::text END) AS "Chem4_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5' THEN t."number_achieving"::text END) AS "Chem5_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '6' THEN t."number_achieving"::text END) AS "Chem6_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '7' THEN t."number_achieving"::text END) AS "Chem7_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '8' THEN t."number_achieving"::text END) AS "Chem8_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '9' THEN t."number_achieving"::text END) AS "Chem9_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '43' THEN t."number_achieving"::text END) AS "CombSci43_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '44' THEN t."number_achieving"::text END) AS "CombSci44_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '54' THEN t."number_achieving"::text END) AS "CombSci54_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '55' THEN t."number_achieving"::text END) AS "CombSci55_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '65' THEN t."number_achieving"::text END) AS "CombSci65_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '66' THEN t."number_achieving"::text END) AS "CombSci66_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '76' THEN t."number_achieving"::text END) AS "CombSci76_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '77' THEN t."number_achieving"::text END) AS "CombSci77_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '87' THEN t."number_achieving"::text END) AS "CombSci87_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '88' THEN t."number_achieving"::text END) AS "CombSci88_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '98' THEN t."number_achieving"::text END) AS "CombSci98_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99' THEN t."number_achieving"::text END) AS "CombSci99_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4' THEN t."number_achieving"::text END) AS "EngLang4_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5' THEN t."number_achieving"::text END) AS "EngLang5_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '6' THEN t."number_achieving"::text END) AS "EngLang6_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7' THEN t."number_achieving"::text END) AS "EngLang7_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '8' THEN t."number_achieving"::text END) AS "EngLang8_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '9' THEN t."number_achieving"::text END) AS "EngLang9_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4' THEN t."number_achieving"::text END) AS "EngLit4_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5' THEN t."number_achieving"::text END) AS "EngLit5_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '6' THEN t."number_achieving"::text END) AS "EngLit6_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7' THEN t."number_achieving"::text END) AS "EngLit7_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '8' THEN t."number_achieving"::text END) AS "EngLit8_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '9' THEN t."number_achieving"::text END) AS "EngLit9_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4' THEN t."number_achieving"::text END) AS "Maths4_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5' THEN t."number_achieving"::text END) AS "Maths5_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '6' THEN t."number_achieving"::text END) AS "Maths6_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7' THEN t."number_achieving"::text END) AS "Maths7_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '8' THEN t."number_achieving"::text END) AS "Maths8_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '9' THEN t."number_achieving"::text END) AS "Maths9_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4' THEN t."number_achieving"::text END) AS "Physics4_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5' THEN t."number_achieving"::text END) AS "Physics5_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '6' THEN t."number_achieving"::text END) AS "Physics6_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7' THEN t."number_achieving"::text END) AS "Physics7_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '8' THEN t."number_achieving"::text END) AS "Physics8_Sum_Est_Current_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '9' THEN t."number_achieving"::text END) AS "Physics9_Sum_Est_Current_Num_Coded"
    FROM t_202425_subject_schoo_ff1f246d1c t
    GROUP BY t."school_urn"
)
,
src_5 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving"::text END) AS "Bio49_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving"::text END) AS "Bio59_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '7+8+9' THEN t."number_achieving"::text END) AS "Bio79_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving"::text END) AS "Chem49_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving"::text END) AS "Chem59_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '7+8+9' THEN t."number_achieving"::text END) AS "Chem79_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99+98+88+87+77+76+66+65+55+54+44' THEN t."number_achieving"::text END) AS "CombSci49_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99+98+88+87+77+76+66+65+55' THEN t."number_achieving"::text END) AS "CombSci59_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99+98+88+87+77' THEN t."number_achieving"::text END) AS "CombSci79_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving"::text END) AS "EngLang49_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving"::text END) AS "EngLang59_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7+8+9' THEN t."number_achieving"::text END) AS "EngLang79_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving"::text END) AS "EngLit49_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving"::text END) AS "EngLit59_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7+8+9' THEN t."number_achieving"::text END) AS "EngLit79_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving"::text END) AS "Maths49_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving"::text END) AS "Maths59_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7+8+9' THEN t."number_achieving"::text END) AS "Maths79_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving"::text END) AS "Physics49_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving"::text END) AS "Physics59_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7+8+9' THEN t."number_achieving"::text END) AS "Physics79_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4' THEN t."number_achieving"::text END) AS "Bio4_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '5' THEN t."number_achieving"::text END) AS "Bio5_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '6' THEN t."number_achieving"::text END) AS "Bio6_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '7' THEN t."number_achieving"::text END) AS "Bio7_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '8' THEN t."number_achieving"::text END) AS "Bio8_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '9' THEN t."number_achieving"::text END) AS "Bio9_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4' THEN t."number_achieving"::text END) AS "Chem4_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5' THEN t."number_achieving"::text END) AS "Chem5_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '6' THEN t."number_achieving"::text END) AS "Chem6_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '7' THEN t."number_achieving"::text END) AS "Chem7_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '8' THEN t."number_achieving"::text END) AS "Chem8_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '9' THEN t."number_achieving"::text END) AS "Chem9_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '43' THEN t."number_achieving"::text END) AS "CombSci43_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '44' THEN t."number_achieving"::text END) AS "CombSci44_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '54' THEN t."number_achieving"::text END) AS "CombSci54_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '55' THEN t."number_achieving"::text END) AS "CombSci55_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '65' THEN t."number_achieving"::text END) AS "CombSci65_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '66' THEN t."number_achieving"::text END) AS "CombSci66_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '76' THEN t."number_achieving"::text END) AS "CombSci76_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '77' THEN t."number_achieving"::text END) AS "CombSci77_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '87' THEN t."number_achieving"::text END) AS "CombSci87_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '88' THEN t."number_achieving"::text END) AS "CombSci88_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '98' THEN t."number_achieving"::text END) AS "CombSci98_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99' THEN t."number_achieving"::text END) AS "CombSci99_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4' THEN t."number_achieving"::text END) AS "EngLang4_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5' THEN t."number_achieving"::text END) AS "EngLang5_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '6' THEN t."number_achieving"::text END) AS "EngLang6_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7' THEN t."number_achieving"::text END) AS "EngLang7_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '8' THEN t."number_achieving"::text END) AS "EngLang8_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '9' THEN t."number_achieving"::text END) AS "EngLang9_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4' THEN t."number_achieving"::text END) AS "EngLit4_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5' THEN t."number_achieving"::text END) AS "EngLit5_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '6' THEN t."number_achieving"::text END) AS "EngLit6_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7' THEN t."number_achieving"::text END) AS "EngLit7_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '8' THEN t."number_achieving"::text END) AS "EngLit8_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '9' THEN t."number_achieving"::text END) AS "EngLit9_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4' THEN t."number_achieving"::text END) AS "Maths4_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5' THEN t."number_achieving"::text END) AS "Maths5_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '6' THEN t."number_achieving"::text END) AS "Maths6_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7' THEN t."number_achieving"::text END) AS "Maths7_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '8' THEN t."number_achieving"::text END) AS "Maths8_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '9' THEN t."number_achieving"::text END) AS "Maths9_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4' THEN t."number_achieving"::text END) AS "Physics4_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5' THEN t."number_achieving"::text END) AS "Physics5_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '6' THEN t."number_achieving"::text END) AS "Physics6_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7' THEN t."number_achieving"::text END) AS "Physics7_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '8' THEN t."number_achieving"::text END) AS "Physics8_Sum_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '9' THEN t."number_achieving"::text END) AS "Physics9_Sum_Est_Previous_Num_Coded"
    FROM t_202324_subject_schoo_84751f4769 t
    GROUP BY t."school_urn"
)
,
src_6 AS (
    SELECT
        t."urn" AS "Id",
        MAX(CASE WHEN TRUE THEN t."p8_banding" END) AS "Prog8_Banding_Est_Previous"
    FROM t_2023_2024_england_ks_73319d608b t
    GROUP BY t."urn"
)
,
src_7 AS (
    SELECT
        t."urn" AS "Id",
        MAX(CASE WHEN TRUE THEN t."ptl2basics_95_prev2"::text END) AS "EngMaths59_Tot_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN TRUE THEN t."ptl2basics_94_prev2"::text END) AS "EngMaths49_Tot_Est_Previous2_Pct_Coded"
    FROM t_2024_2025_england_ks_46ebf4be43 t
    GROUP BY t."urn"
)
,
src_8 AS (
    SELECT
        t."urn" AS "Id",
        MAX(CASE WHEN TRUE THEN t."att8scr"::text END) AS "Attainment8_Tot_Est_Previous2_Num_Coded",
        MAX(CASE WHEN TRUE THEN t."p8mea"::text END) AS "Prog8_Tot_Est_Previous2_Num_Coded",
        MAX(CASE WHEN TRUE THEN t."p8cilow" END) AS "Prog8_CI_Lower_Est_Previous2_Num_Coded",
        MAX(CASE WHEN TRUE THEN t."p8ciupp" END) AS "Prog8_CI_Upper_Est_Previous2_Num_Coded",
        MAX(CASE WHEN TRUE THEN t."p8_banding" END) AS "Prog8_Banding_Est_Previous2",
        MAX(CASE WHEN TRUE THEN t."att8scr_boys"::text END) AS "Attainment8_Boy_Est_Previous2_Num_Coded",
        MAX(CASE WHEN TRUE THEN t."att8scr_fsm6cla1a"::text END) AS "Attainment8_Dis_Est_Previous2_Num_Coded",
        MAX(CASE WHEN TRUE THEN t."att8scr_eal"::text END) AS "Attainment8_EAL_Est_Previous2_Num_Coded",
        MAX(CASE WHEN TRUE THEN t."att8scr_girls"::text END) AS "Attainment8_Grl_Est_Previous2_Num_Coded",
        MAX(CASE WHEN TRUE THEN t."att8scr_nfsm6cla1a"::text END) AS "Attainment8_NDi_Est_Previous2_Num_Coded",
        MAX(CASE WHEN TRUE THEN t."att8scr_nmob"::text END) AS "Attainment8_NMo_Est_Previous2_Num_Coded",
        MAX(CASE WHEN TRUE THEN t."pbl2basics_94"::text END) AS "EngMaths49_Boy_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN TRUE THEN t."ptfsm6cla1abasics_94"::text END) AS "EngMaths49_Dis_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN TRUE THEN t."ptl2basicseal_94"::text END) AS "EngMaths49_EAL_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN TRUE THEN t."pgl2basics_94"::text END) AS "EngMaths49_Grl_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN TRUE THEN t."ptl2basicsnmob_94"::text END) AS "EngMaths49_Mob_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN TRUE THEN t."pbl2basics_95"::text END) AS "EngMaths59_Boy_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN TRUE THEN t."ptfsm6cla1abasics_95"::text END) AS "EngMaths59_Dis_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN TRUE THEN t."ptl2basicseal_95"::text END) AS "EngMaths59_EAL_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN TRUE THEN t."pgl2basics_95"::text END) AS "EngMaths59_Grl_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN TRUE THEN t."ptl2basicsnmob_95"::text END) AS "EngMaths59_Mob_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN TRUE THEN t."tpup"::text END) AS "Pup_Tot_Est_Previous2_Num_Coded",
        MAX(CASE WHEN TRUE THEN t."p8pup"::text END) AS "Prog8_TotPup_Est_Previous2_Num_Coded"
    FROM t_2022_2023_england_ks_28199246f1 t
    GROUP BY t."urn"
)
,
src_9 AS (
    SELECT
        t."unique_reference_number__urn_" AS "Id",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "Bio49_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "Bio59_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "Bio79_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "Chem49_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "Chem59_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "Chem79_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99+98+88+87+77+76+66+65+55+54+44' THEN t."number_of_entries_at_grade"::text END) AS "CombSci49_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99+98+88+87+77+76+66+65+55' THEN t."number_of_entries_at_grade"::text END) AS "CombSci59_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99+98+88+87+77' THEN t."number_of_entries_at_grade"::text END) AS "CombSci79_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "EngLang49_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "EngLang59_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "EngLang79_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "EngLit49_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "EngLit59_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "EngLit79_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "Maths49_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "Maths59_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "Maths79_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "Physics49_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "Physics59_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade"::text END) AS "Physics79_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4' THEN t."number_of_entries_at_grade"::text END) AS "Bio4_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '5' THEN t."number_of_entries_at_grade"::text END) AS "Bio5_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '6' THEN t."number_of_entries_at_grade"::text END) AS "Bio6_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '7' THEN t."number_of_entries_at_grade"::text END) AS "Bio7_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '8' THEN t."number_of_entries_at_grade"::text END) AS "Bio8_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '9' THEN t."number_of_entries_at_grade"::text END) AS "Bio9_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4' THEN t."number_of_entries_at_grade"::text END) AS "Chem4_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5' THEN t."number_of_entries_at_grade"::text END) AS "Chem5_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '6' THEN t."number_of_entries_at_grade"::text END) AS "Chem6_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '7' THEN t."number_of_entries_at_grade"::text END) AS "Chem7_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '8' THEN t."number_of_entries_at_grade"::text END) AS "Chem8_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '9' THEN t."number_of_entries_at_grade"::text END) AS "Chem9_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '43' THEN t."number_of_entries_at_grade"::text END) AS "CombSci43_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '44' THEN t."number_of_entries_at_grade"::text END) AS "CombSci44_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '54' THEN t."number_of_entries_at_grade"::text END) AS "CombSci54_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '55' THEN t."number_of_entries_at_grade"::text END) AS "CombSci55_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '65' THEN t."number_of_entries_at_grade"::text END) AS "CombSci65_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '66' THEN t."number_of_entries_at_grade"::text END) AS "CombSci66_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '76' THEN t."number_of_entries_at_grade"::text END) AS "CombSci76_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '77' THEN t."number_of_entries_at_grade"::text END) AS "CombSci77_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '87' THEN t."number_of_entries_at_grade"::text END) AS "CombSci87_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '88' THEN t."number_of_entries_at_grade"::text END) AS "CombSci88_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '98' THEN t."number_of_entries_at_grade"::text END) AS "CombSci98_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99' THEN t."number_of_entries_at_grade"::text END) AS "CombSci99_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4' THEN t."number_of_entries_at_grade"::text END) AS "EngLang4_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5' THEN t."number_of_entries_at_grade"::text END) AS "EngLang5_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '6' THEN t."number_of_entries_at_grade"::text END) AS "EngLang6_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7' THEN t."number_of_entries_at_grade"::text END) AS "EngLang7_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '8' THEN t."number_of_entries_at_grade"::text END) AS "EngLang8_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '9' THEN t."number_of_entries_at_grade"::text END) AS "EngLang9_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4' THEN t."number_of_entries_at_grade"::text END) AS "EngLit4_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5' THEN t."number_of_entries_at_grade"::text END) AS "EngLit5_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '6' THEN t."number_of_entries_at_grade"::text END) AS "EngLit6_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7' THEN t."number_of_entries_at_grade"::text END) AS "EngLit7_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '8' THEN t."number_of_entries_at_grade"::text END) AS "EngLit8_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '9' THEN t."number_of_entries_at_grade"::text END) AS "EngLit9_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4' THEN t."number_of_entries_at_grade"::text END) AS "Maths4_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5' THEN t."number_of_entries_at_grade"::text END) AS "Maths5_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '6' THEN t."number_of_entries_at_grade"::text END) AS "Maths6_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7' THEN t."number_of_entries_at_grade"::text END) AS "Maths7_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '8' THEN t."number_of_entries_at_grade"::text END) AS "Maths8_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '9' THEN t."number_of_entries_at_grade"::text END) AS "Maths9_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4' THEN t."number_of_entries_at_grade"::text END) AS "Physics4_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5' THEN t."number_of_entries_at_grade"::text END) AS "Physics5_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '6' THEN t."number_of_entries_at_grade"::text END) AS "Physics6_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7' THEN t."number_of_entries_at_grade"::text END) AS "Physics7_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '8' THEN t."number_of_entries_at_grade"::text END) AS "Physics8_Sum_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '9' THEN t."number_of_entries_at_grade"::text END) AS "Physics9_Sum_Est_Previous2_Num_Coded"
    FROM t_england_ks4underlyin_effb560d65 t
    GROUP BY t."unique_reference_number__urn_"
)
,
all_ids AS (
    SELECT "Id" FROM src_1
    UNION SELECT "Id" FROM src_2
    UNION SELECT "Id" FROM src_3
    UNION SELECT "Id" FROM src_4
    UNION SELECT "Id" FROM src_5
    UNION SELECT "Id" FROM src_6
    UNION SELECT "Id" FROM src_7
    UNION SELECT "Id" FROM src_8
    UNION SELECT "Id" FROM src_9
)

SELECT
    a."Id" AS "Id",
    e."LAId" AS "LAId",
    e."LAName" AS "LAName",
    e."RegionId" AS "RegionId",
    e."RegionName" AS "RegionName",
    src_2."Attainment8_Boy_Est_Current_Num_Coded" AS "Attainment8_Boy_Est_Current_Num_Coded",
    src_3."Attainment8_Boy_Est_Previous_Num_Coded" AS "Attainment8_Boy_Est_Previous_Num_Coded",
    src_8."Attainment8_Boy_Est_Previous2_Num_Coded" AS "Attainment8_Boy_Est_Previous2_Num_Coded",
    src_2."Attainment8_Dis_Est_Current_Num_Coded" AS "Attainment8_Dis_Est_Current_Num_Coded",
    src_3."Attainment8_Dis_Est_Previous_Num_Coded" AS "Attainment8_Dis_Est_Previous_Num_Coded",
    src_8."Attainment8_Dis_Est_Previous2_Num_Coded" AS "Attainment8_Dis_Est_Previous2_Num_Coded",
    src_2."Attainment8_EAL_Est_Current_Num_Coded" AS "Attainment8_EAL_Est_Current_Num_Coded",
    src_3."Attainment8_EAL_Est_Previous_Num_Coded" AS "Attainment8_EAL_Est_Previous_Num_Coded",
    src_8."Attainment8_EAL_Est_Previous2_Num_Coded" AS "Attainment8_EAL_Est_Previous2_Num_Coded",
    src_2."Attainment8_Grl_Est_Current_Num_Coded" AS "Attainment8_Grl_Est_Current_Num_Coded",
    src_3."Attainment8_Grl_Est_Previous_Num_Coded" AS "Attainment8_Grl_Est_Previous_Num_Coded",
    src_8."Attainment8_Grl_Est_Previous2_Num_Coded" AS "Attainment8_Grl_Est_Previous2_Num_Coded",
    src_2."Attainment8_NDi_Est_Current_Num_Coded" AS "Attainment8_NDi_Est_Current_Num_Coded",
    src_8."Attainment8_NDi_Est_Previous2_Num_Coded" AS "Attainment8_NDi_Est_Previous2_Num_Coded",
    src_2."Attainment8_NMo_Est_Current_Num_Coded" AS "Attainment8_NMo_Est_Current_Num_Coded",
    src_3."Attainment8_NMo_Est_Previous_Num_Coded" AS "Attainment8_NMo_Est_Previous_Num_Coded",
    src_8."Attainment8_NMo_Est_Previous2_Num_Coded" AS "Attainment8_NMo_Est_Previous2_Num_Coded",
    src_1."Attainment8_Tot_Est_Current_Num_Coded" AS "Attainment8_Tot_Est_Current_Num_Coded",
    src_3."Attainment8_Tot_Est_Previous_Num_Coded" AS "Attainment8_Tot_Est_Previous_Num_Coded",
    src_8."Attainment8_Tot_Est_Previous2_Num_Coded" AS "Attainment8_Tot_Est_Previous2_Num_Coded",
    src_4."Bio4_Sum_Est_Current_Num_Coded" AS "Bio4_Sum_Est_Current_Num_Coded",
    src_5."Bio4_Sum_Est_Previous_Num_Coded" AS "Bio4_Sum_Est_Previous_Num_Coded",
    src_9."Bio4_Sum_Est_Previous2_Num_Coded" AS "Bio4_Sum_Est_Previous2_Num_Coded",
    src_4."Bio49_Sum_Est_Current_Num_Coded" AS "Bio49_Sum_Est_Current_Num_Coded",
    src_5."Bio49_Sum_Est_Previous_Num_Coded" AS "Bio49_Sum_Est_Previous_Num_Coded",
    src_9."Bio49_Sum_Est_Previous2_Num_Coded" AS "Bio49_Sum_Est_Previous2_Num_Coded",
    src_4."Bio5_Sum_Est_Current_Num_Coded" AS "Bio5_Sum_Est_Current_Num_Coded",
    src_5."Bio5_Sum_Est_Previous_Num_Coded" AS "Bio5_Sum_Est_Previous_Num_Coded",
    src_9."Bio5_Sum_Est_Previous2_Num_Coded" AS "Bio5_Sum_Est_Previous2_Num_Coded",
    src_4."Bio59_Sum_Est_Current_Num_Coded" AS "Bio59_Sum_Est_Current_Num_Coded",
    src_5."Bio59_Sum_Est_Previous_Num_Coded" AS "Bio59_Sum_Est_Previous_Num_Coded",
    src_9."Bio59_Sum_Est_Previous2_Num_Coded" AS "Bio59_Sum_Est_Previous2_Num_Coded",
    src_4."Bio6_Sum_Est_Current_Num_Coded" AS "Bio6_Sum_Est_Current_Num_Coded",
    src_5."Bio6_Sum_Est_Previous_Num_Coded" AS "Bio6_Sum_Est_Previous_Num_Coded",
    src_9."Bio6_Sum_Est_Previous2_Num_Coded" AS "Bio6_Sum_Est_Previous2_Num_Coded",
    src_4."Bio7_Sum_Est_Current_Num_Coded" AS "Bio7_Sum_Est_Current_Num_Coded",
    src_5."Bio7_Sum_Est_Previous_Num_Coded" AS "Bio7_Sum_Est_Previous_Num_Coded",
    src_9."Bio7_Sum_Est_Previous2_Num_Coded" AS "Bio7_Sum_Est_Previous2_Num_Coded",
    src_4."Bio79_Sum_Est_Current_Num_Coded" AS "Bio79_Sum_Est_Current_Num_Coded",
    src_5."Bio79_Sum_Est_Previous_Num_Coded" AS "Bio79_Sum_Est_Previous_Num_Coded",
    src_9."Bio79_Sum_Est_Previous2_Num_Coded" AS "Bio79_Sum_Est_Previous2_Num_Coded",
    src_4."Bio8_Sum_Est_Current_Num_Coded" AS "Bio8_Sum_Est_Current_Num_Coded",
    src_5."Bio8_Sum_Est_Previous_Num_Coded" AS "Bio8_Sum_Est_Previous_Num_Coded",
    src_9."Bio8_Sum_Est_Previous2_Num_Coded" AS "Bio8_Sum_Est_Previous2_Num_Coded",
    src_4."Bio9_Sum_Est_Current_Num_Coded" AS "Bio9_Sum_Est_Current_Num_Coded",
    src_5."Bio9_Sum_Est_Previous_Num_Coded" AS "Bio9_Sum_Est_Previous_Num_Coded",
    src_9."Bio9_Sum_Est_Previous2_Num_Coded" AS "Bio9_Sum_Est_Previous2_Num_Coded",
    src_4."Chem4_Sum_Est_Current_Num_Coded" AS "Chem4_Sum_Est_Current_Num_Coded",
    src_5."Chem4_Sum_Est_Previous_Num_Coded" AS "Chem4_Sum_Est_Previous_Num_Coded",
    src_9."Chem4_Sum_Est_Previous2_Num_Coded" AS "Chem4_Sum_Est_Previous2_Num_Coded",
    src_4."Chem49_Sum_Est_Current_Num_Coded" AS "Chem49_Sum_Est_Current_Num_Coded",
    src_5."Chem49_Sum_Est_Previous_Num_Coded" AS "Chem49_Sum_Est_Previous_Num_Coded",
    src_9."Chem49_Sum_Est_Previous2_Num_Coded" AS "Chem49_Sum_Est_Previous2_Num_Coded",
    src_4."Chem5_Sum_Est_Current_Num_Coded" AS "Chem5_Sum_Est_Current_Num_Coded",
    src_5."Chem5_Sum_Est_Previous_Num_Coded" AS "Chem5_Sum_Est_Previous_Num_Coded",
    src_9."Chem5_Sum_Est_Previous2_Num_Coded" AS "Chem5_Sum_Est_Previous2_Num_Coded",
    src_4."Chem59_Sum_Est_Current_Num_Coded" AS "Chem59_Sum_Est_Current_Num_Coded",
    src_5."Chem59_Sum_Est_Previous_Num_Coded" AS "Chem59_Sum_Est_Previous_Num_Coded",
    src_9."Chem59_Sum_Est_Previous2_Num_Coded" AS "Chem59_Sum_Est_Previous2_Num_Coded",
    src_4."Chem6_Sum_Est_Current_Num_Coded" AS "Chem6_Sum_Est_Current_Num_Coded",
    src_5."Chem6_Sum_Est_Previous_Num_Coded" AS "Chem6_Sum_Est_Previous_Num_Coded",
    src_9."Chem6_Sum_Est_Previous2_Num_Coded" AS "Chem6_Sum_Est_Previous2_Num_Coded",
    src_4."Chem7_Sum_Est_Current_Num_Coded" AS "Chem7_Sum_Est_Current_Num_Coded",
    src_5."Chem7_Sum_Est_Previous_Num_Coded" AS "Chem7_Sum_Est_Previous_Num_Coded",
    src_9."Chem7_Sum_Est_Previous2_Num_Coded" AS "Chem7_Sum_Est_Previous2_Num_Coded",
    src_4."Chem79_Sum_Est_Current_Num_Coded" AS "Chem79_Sum_Est_Current_Num_Coded",
    src_5."Chem79_Sum_Est_Previous_Num_Coded" AS "Chem79_Sum_Est_Previous_Num_Coded",
    src_9."Chem79_Sum_Est_Previous2_Num_Coded" AS "Chem79_Sum_Est_Previous2_Num_Coded",
    src_4."Chem8_Sum_Est_Current_Num_Coded" AS "Chem8_Sum_Est_Current_Num_Coded",
    src_5."Chem8_Sum_Est_Previous_Num_Coded" AS "Chem8_Sum_Est_Previous_Num_Coded",
    src_9."Chem8_Sum_Est_Previous2_Num_Coded" AS "Chem8_Sum_Est_Previous2_Num_Coded",
    src_4."Chem9_Sum_Est_Current_Num_Coded" AS "Chem9_Sum_Est_Current_Num_Coded",
    src_5."Chem9_Sum_Est_Previous_Num_Coded" AS "Chem9_Sum_Est_Previous_Num_Coded",
    src_9."Chem9_Sum_Est_Previous2_Num_Coded" AS "Chem9_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci43_Sum_Est_Current_Num_Coded" AS "CombSci43_Sum_Est_Current_Num_Coded",
    src_5."CombSci43_Sum_Est_Previous_Num_Coded" AS "CombSci43_Sum_Est_Previous_Num_Coded",
    src_9."CombSci43_Sum_Est_Previous2_Num_Coded" AS "CombSci43_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci44_Sum_Est_Current_Num_Coded" AS "CombSci44_Sum_Est_Current_Num_Coded",
    src_5."CombSci44_Sum_Est_Previous_Num_Coded" AS "CombSci44_Sum_Est_Previous_Num_Coded",
    src_9."CombSci44_Sum_Est_Previous2_Num_Coded" AS "CombSci44_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci49_Sum_Est_Current_Num_Coded" AS "CombSci49_Sum_Est_Current_Num_Coded",
    src_5."CombSci49_Sum_Est_Previous_Num_Coded" AS "CombSci49_Sum_Est_Previous_Num_Coded",
    src_9."CombSci49_Sum_Est_Previous2_Num_Coded" AS "CombSci49_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci54_Sum_Est_Current_Num_Coded" AS "CombSci54_Sum_Est_Current_Num_Coded",
    src_5."CombSci54_Sum_Est_Previous_Num_Coded" AS "CombSci54_Sum_Est_Previous_Num_Coded",
    src_9."CombSci54_Sum_Est_Previous2_Num_Coded" AS "CombSci54_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci55_Sum_Est_Current_Num_Coded" AS "CombSci55_Sum_Est_Current_Num_Coded",
    src_5."CombSci55_Sum_Est_Previous_Num_Coded" AS "CombSci55_Sum_Est_Previous_Num_Coded",
    src_9."CombSci55_Sum_Est_Previous2_Num_Coded" AS "CombSci55_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci59_Sum_Est_Current_Num_Coded" AS "CombSci59_Sum_Est_Current_Num_Coded",
    src_5."CombSci59_Sum_Est_Previous_Num_Coded" AS "CombSci59_Sum_Est_Previous_Num_Coded",
    src_9."CombSci59_Sum_Est_Previous2_Num_Coded" AS "CombSci59_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci65_Sum_Est_Current_Num_Coded" AS "CombSci65_Sum_Est_Current_Num_Coded",
    src_5."CombSci65_Sum_Est_Previous_Num_Coded" AS "CombSci65_Sum_Est_Previous_Num_Coded",
    src_9."CombSci65_Sum_Est_Previous2_Num_Coded" AS "CombSci65_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci66_Sum_Est_Current_Num_Coded" AS "CombSci66_Sum_Est_Current_Num_Coded",
    src_5."CombSci66_Sum_Est_Previous_Num_Coded" AS "CombSci66_Sum_Est_Previous_Num_Coded",
    src_9."CombSci66_Sum_Est_Previous2_Num_Coded" AS "CombSci66_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci76_Sum_Est_Current_Num_Coded" AS "CombSci76_Sum_Est_Current_Num_Coded",
    src_5."CombSci76_Sum_Est_Previous_Num_Coded" AS "CombSci76_Sum_Est_Previous_Num_Coded",
    src_9."CombSci76_Sum_Est_Previous2_Num_Coded" AS "CombSci76_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci77_Sum_Est_Current_Num_Coded" AS "CombSci77_Sum_Est_Current_Num_Coded",
    src_5."CombSci77_Sum_Est_Previous_Num_Coded" AS "CombSci77_Sum_Est_Previous_Num_Coded",
    src_9."CombSci77_Sum_Est_Previous2_Num_Coded" AS "CombSci77_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci79_Sum_Est_Current_Num_Coded" AS "CombSci79_Sum_Est_Current_Num_Coded",
    src_5."CombSci79_Sum_Est_Previous_Num_Coded" AS "CombSci79_Sum_Est_Previous_Num_Coded",
    src_9."CombSci79_Sum_Est_Previous2_Num_Coded" AS "CombSci79_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci87_Sum_Est_Current_Num_Coded" AS "CombSci87_Sum_Est_Current_Num_Coded",
    src_5."CombSci87_Sum_Est_Previous_Num_Coded" AS "CombSci87_Sum_Est_Previous_Num_Coded",
    src_9."CombSci87_Sum_Est_Previous2_Num_Coded" AS "CombSci87_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci88_Sum_Est_Current_Num_Coded" AS "CombSci88_Sum_Est_Current_Num_Coded",
    src_5."CombSci88_Sum_Est_Previous_Num_Coded" AS "CombSci88_Sum_Est_Previous_Num_Coded",
    src_9."CombSci88_Sum_Est_Previous2_Num_Coded" AS "CombSci88_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci98_Sum_Est_Current_Num_Coded" AS "CombSci98_Sum_Est_Current_Num_Coded",
    src_5."CombSci98_Sum_Est_Previous_Num_Coded" AS "CombSci98_Sum_Est_Previous_Num_Coded",
    src_9."CombSci98_Sum_Est_Previous2_Num_Coded" AS "CombSci98_Sum_Est_Previous2_Num_Coded",
    src_4."CombSci99_Sum_Est_Current_Num_Coded" AS "CombSci99_Sum_Est_Current_Num_Coded",
    src_5."CombSci99_Sum_Est_Previous_Num_Coded" AS "CombSci99_Sum_Est_Previous_Num_Coded",
    src_9."CombSci99_Sum_Est_Previous2_Num_Coded" AS "CombSci99_Sum_Est_Previous2_Num_Coded",
    src_4."EngLang4_Sum_Est_Current_Num_Coded" AS "EngLang4_Sum_Est_Current_Num_Coded",
    src_5."EngLang4_Sum_Est_Previous_Num_Coded" AS "EngLang4_Sum_Est_Previous_Num_Coded",
    src_9."EngLang4_Sum_Est_Previous2_Num_Coded" AS "EngLang4_Sum_Est_Previous2_Num_Coded",
    src_4."EngLang49_Sum_Est_Current_Num_Coded" AS "EngLang49_Sum_Est_Current_Num_Coded",
    src_5."EngLang49_Sum_Est_Previous_Num_Coded" AS "EngLang49_Sum_Est_Previous_Num_Coded",
    src_9."EngLang49_Sum_Est_Previous2_Num_Coded" AS "EngLang49_Sum_Est_Previous2_Num_Coded",
    src_4."EngLang5_Sum_Est_Current_Num_Coded" AS "EngLang5_Sum_Est_Current_Num_Coded",
    src_5."EngLang5_Sum_Est_Previous_Num_Coded" AS "EngLang5_Sum_Est_Previous_Num_Coded",
    src_9."EngLang5_Sum_Est_Previous2_Num_Coded" AS "EngLang5_Sum_Est_Previous2_Num_Coded",
    src_4."EngLang59_Sum_Est_Current_Num_Coded" AS "EngLang59_Sum_Est_Current_Num_Coded",
    src_5."EngLang59_Sum_Est_Previous_Num_Coded" AS "EngLang59_Sum_Est_Previous_Num_Coded",
    src_9."EngLang59_Sum_Est_Previous2_Num_Coded" AS "EngLang59_Sum_Est_Previous2_Num_Coded",
    src_4."EngLang6_Sum_Est_Current_Num_Coded" AS "EngLang6_Sum_Est_Current_Num_Coded",
    src_5."EngLang6_Sum_Est_Previous_Num_Coded" AS "EngLang6_Sum_Est_Previous_Num_Coded",
    src_9."EngLang6_Sum_Est_Previous2_Num_Coded" AS "EngLang6_Sum_Est_Previous2_Num_Coded",
    src_4."EngLang7_Sum_Est_Current_Num_Coded" AS "EngLang7_Sum_Est_Current_Num_Coded",
    src_5."EngLang7_Sum_Est_Previous_Num_Coded" AS "EngLang7_Sum_Est_Previous_Num_Coded",
    src_9."EngLang7_Sum_Est_Previous2_Num_Coded" AS "EngLang7_Sum_Est_Previous2_Num_Coded",
    src_4."EngLang79_Sum_Est_Current_Num_Coded" AS "EngLang79_Sum_Est_Current_Num_Coded",
    src_5."EngLang79_Sum_Est_Previous_Num_Coded" AS "EngLang79_Sum_Est_Previous_Num_Coded",
    src_9."EngLang79_Sum_Est_Previous2_Num_Coded" AS "EngLang79_Sum_Est_Previous2_Num_Coded",
    src_4."EngLang8_Sum_Est_Current_Num_Coded" AS "EngLang8_Sum_Est_Current_Num_Coded",
    src_5."EngLang8_Sum_Est_Previous_Num_Coded" AS "EngLang8_Sum_Est_Previous_Num_Coded",
    src_9."EngLang8_Sum_Est_Previous2_Num_Coded" AS "EngLang8_Sum_Est_Previous2_Num_Coded",
    src_4."EngLang9_Sum_Est_Current_Num_Coded" AS "EngLang9_Sum_Est_Current_Num_Coded",
    src_5."EngLang9_Sum_Est_Previous_Num_Coded" AS "EngLang9_Sum_Est_Previous_Num_Coded",
    src_9."EngLang9_Sum_Est_Previous2_Num_Coded" AS "EngLang9_Sum_Est_Previous2_Num_Coded",
    src_4."EngLit4_Sum_Est_Current_Num_Coded" AS "EngLit4_Sum_Est_Current_Num_Coded",
    src_5."EngLit4_Sum_Est_Previous_Num_Coded" AS "EngLit4_Sum_Est_Previous_Num_Coded",
    src_9."EngLit4_Sum_Est_Previous2_Num_Coded" AS "EngLit4_Sum_Est_Previous2_Num_Coded",
    src_4."EngLit49_Sum_Est_Current_Num_Coded" AS "EngLit49_Sum_Est_Current_Num_Coded",
    src_5."EngLit49_Sum_Est_Previous_Num_Coded" AS "EngLit49_Sum_Est_Previous_Num_Coded",
    src_9."EngLit49_Sum_Est_Previous2_Num_Coded" AS "EngLit49_Sum_Est_Previous2_Num_Coded",
    src_4."EngLit5_Sum_Est_Current_Num_Coded" AS "EngLit5_Sum_Est_Current_Num_Coded",
    src_5."EngLit5_Sum_Est_Previous_Num_Coded" AS "EngLit5_Sum_Est_Previous_Num_Coded",
    src_9."EngLit5_Sum_Est_Previous2_Num_Coded" AS "EngLit5_Sum_Est_Previous2_Num_Coded",
    src_4."EngLit59_Sum_Est_Current_Num_Coded" AS "EngLit59_Sum_Est_Current_Num_Coded",
    src_5."EngLit59_Sum_Est_Previous_Num_Coded" AS "EngLit59_Sum_Est_Previous_Num_Coded",
    src_9."EngLit59_Sum_Est_Previous2_Num_Coded" AS "EngLit59_Sum_Est_Previous2_Num_Coded",
    src_4."EngLit6_Sum_Est_Current_Num_Coded" AS "EngLit6_Sum_Est_Current_Num_Coded",
    src_5."EngLit6_Sum_Est_Previous_Num_Coded" AS "EngLit6_Sum_Est_Previous_Num_Coded",
    src_9."EngLit6_Sum_Est_Previous2_Num_Coded" AS "EngLit6_Sum_Est_Previous2_Num_Coded",
    src_4."EngLit7_Sum_Est_Current_Num_Coded" AS "EngLit7_Sum_Est_Current_Num_Coded",
    src_5."EngLit7_Sum_Est_Previous_Num_Coded" AS "EngLit7_Sum_Est_Previous_Num_Coded",
    src_9."EngLit7_Sum_Est_Previous2_Num_Coded" AS "EngLit7_Sum_Est_Previous2_Num_Coded",
    src_4."EngLit79_Sum_Est_Current_Num_Coded" AS "EngLit79_Sum_Est_Current_Num_Coded",
    src_5."EngLit79_Sum_Est_Previous_Num_Coded" AS "EngLit79_Sum_Est_Previous_Num_Coded",
    src_9."EngLit79_Sum_Est_Previous2_Num_Coded" AS "EngLit79_Sum_Est_Previous2_Num_Coded",
    src_4."EngLit8_Sum_Est_Current_Num_Coded" AS "EngLit8_Sum_Est_Current_Num_Coded",
    src_5."EngLit8_Sum_Est_Previous_Num_Coded" AS "EngLit8_Sum_Est_Previous_Num_Coded",
    src_9."EngLit8_Sum_Est_Previous2_Num_Coded" AS "EngLit8_Sum_Est_Previous2_Num_Coded",
    src_4."EngLit9_Sum_Est_Current_Num_Coded" AS "EngLit9_Sum_Est_Current_Num_Coded",
    src_5."EngLit9_Sum_Est_Previous_Num_Coded" AS "EngLit9_Sum_Est_Previous_Num_Coded",
    src_9."EngLit9_Sum_Est_Previous2_Num_Coded" AS "EngLit9_Sum_Est_Previous2_Num_Coded",
    src_2."EngMaths49_Boy_Est_Current_Num_Coded" AS "EngMaths49_Boy_Est_Current_Num_Coded",
    src_1."EngMaths49_Boy_Est_Current_Pct_Coded" AS "EngMaths49_Boy_Est_Current_Pct_Coded",
    src_3."EngMaths49_Boy_Est_Previous_Num_Coded" AS "EngMaths49_Boy_Est_Previous_Num_Coded",
    src_3."EngMaths49_Boy_Est_Previous_Pct_Coded" AS "EngMaths49_Boy_Est_Previous_Pct_Coded",
    src_8."EngMaths49_Boy_Est_Previous2_Pct_Coded" AS "EngMaths49_Boy_Est_Previous2_Pct_Coded",
    src_2."EngMaths49_Dis_Est_Current_Num_Coded" AS "EngMaths49_Dis_Est_Current_Num_Coded",
    src_2."EngMaths49_Dis_Est_Current_Pct_Coded" AS "EngMaths49_Dis_Est_Current_Pct_Coded",
    src_3."EngMaths49_Dis_Est_Previous_Num_Coded" AS "EngMaths49_Dis_Est_Previous_Num_Coded",
    src_3."EngMaths49_Dis_Est_Previous_Pct_Coded" AS "EngMaths49_Dis_Est_Previous_Pct_Coded",
    src_8."EngMaths49_Dis_Est_Previous2_Pct_Coded" AS "EngMaths49_Dis_Est_Previous2_Pct_Coded",
    src_2."EngMaths49_EAL_Est_Current_Num_Coded" AS "EngMaths49_EAL_Est_Current_Num_Coded",
    src_2."EngMaths49_EAL_Est_Current_Pct_Coded" AS "EngMaths49_EAL_Est_Current_Pct_Coded",
    src_3."EngMaths49_EAL_Est_Previous_Num_Coded" AS "EngMaths49_EAL_Est_Previous_Num_Coded",
    src_3."EngMaths49_EAL_Est_Previous_Pct_Coded" AS "EngMaths49_EAL_Est_Previous_Pct_Coded",
    src_8."EngMaths49_EAL_Est_Previous2_Pct_Coded" AS "EngMaths49_EAL_Est_Previous2_Pct_Coded",
    src_2."EngMaths49_Grl_Est_Current_Num_Coded" AS "EngMaths49_Grl_Est_Current_Num_Coded",
    src_1."EngMaths49_Grl_Est_Current_Pct_Coded" AS "EngMaths49_Grl_Est_Current_Pct_Coded",
    src_3."EngMaths49_Grl_Est_Previous_Num_Coded" AS "EngMaths49_Grl_Est_Previous_Num_Coded",
    src_3."EngMaths49_Grl_Est_Previous_Pct_Coded" AS "EngMaths49_Grl_Est_Previous_Pct_Coded",
    src_8."EngMaths49_Grl_Est_Previous2_Pct_Coded" AS "EngMaths49_Grl_Est_Previous2_Pct_Coded",
    src_8."EngMaths49_Mob_Est_Previous2_Pct_Coded" AS "EngMaths49_Mob_Est_Previous2_Pct_Coded",
    src_2."EngMaths49_NDi_Est_Current_Num_Coded" AS "EngMaths49_NDi_Est_Current_Num_Coded",
    src_2."EngMaths49_NDi_Est_Current_Pct_Coded" AS "EngMaths49_NDi_Est_Current_Pct_Coded",
    src_2."EngMaths49_NMo_Est_Current_Num_Coded" AS "EngMaths49_NMo_Est_Current_Num_Coded",
    src_2."EngMaths49_NMo_Est_Current_Pct_Coded" AS "EngMaths49_NMo_Est_Current_Pct_Coded",
    src_3."EngMaths49_NMo_Est_Previous_Num_Coded" AS "EngMaths49_NMo_Est_Previous_Num_Coded",
    src_3."EngMaths49_NMo_Est_Previous_Pct_Coded" AS "EngMaths49_NMo_Est_Previous_Pct_Coded",
    src_1."EngMaths49_Tot_Est_Current_Num_Coded" AS "EngMaths49_Tot_Est_Current_Num_Coded",
    src_1."EngMaths49_Tot_Est_Current_Pct_Coded" AS "EngMaths49_Tot_Est_Current_Pct_Coded",
    src_3."EngMaths49_Tot_Est_Previous_Num_Coded" AS "EngMaths49_Tot_Est_Previous_Num_Coded",
    src_3."EngMaths49_Tot_Est_Previous_Pct_Coded" AS "EngMaths49_Tot_Est_Previous_Pct_Coded",
    src_7."EngMaths49_Tot_Est_Previous2_Pct_Coded" AS "EngMaths49_Tot_Est_Previous2_Pct_Coded",
    src_2."EngMaths59_Boy_Est_Current_Num_Coded" AS "EngMaths59_Boy_Est_Current_Num_Coded",
    src_1."EngMaths59_Boy_Est_Current_Pct_Coded" AS "EngMaths59_Boy_Est_Current_Pct_Coded",
    src_3."EngMaths59_Boy_Est_Previous_Num_Coded" AS "EngMaths59_Boy_Est_Previous_Num_Coded",
    src_3."EngMaths59_Boy_Est_Previous_Pct_Coded" AS "EngMaths59_Boy_Est_Previous_Pct_Coded",
    src_8."EngMaths59_Boy_Est_Previous2_Pct_Coded" AS "EngMaths59_Boy_Est_Previous2_Pct_Coded",
    src_2."EngMaths59_Dis_Est_Current_Num_Coded" AS "EngMaths59_Dis_Est_Current_Num_Coded",
    src_2."EngMaths59_Dis_Est_Current_Pct_Coded" AS "EngMaths59_Dis_Est_Current_Pct_Coded",
    src_3."EngMaths59_Dis_Est_Previous_Num_Coded" AS "EngMaths59_Dis_Est_Previous_Num_Coded",
    src_3."EngMaths59_Dis_Est_Previous_Pct_Coded" AS "EngMaths59_Dis_Est_Previous_Pct_Coded",
    src_8."EngMaths59_Dis_Est_Previous2_Pct_Coded" AS "EngMaths59_Dis_Est_Previous2_Pct_Coded",
    src_2."EngMaths59_EAL_Est_Current_Num_Coded" AS "EngMaths59_EAL_Est_Current_Num_Coded",
    src_2."EngMaths59_EAL_Est_Current_Pct_Coded" AS "EngMaths59_EAL_Est_Current_Pct_Coded",
    src_3."EngMaths59_EAL_Est_Previous_Num_Coded" AS "EngMaths59_EAL_Est_Previous_Num_Coded",
    src_3."EngMaths59_EAL_Est_Previous_Pct_Coded" AS "EngMaths59_EAL_Est_Previous_Pct_Coded",
    src_8."EngMaths59_EAL_Est_Previous2_Pct_Coded" AS "EngMaths59_EAL_Est_Previous2_Pct_Coded",
    src_2."EngMaths59_Grl_Est_Current_Num_Coded" AS "EngMaths59_Grl_Est_Current_Num_Coded",
    src_1."EngMaths59_Grl_Est_Current_Pct_Coded" AS "EngMaths59_Grl_Est_Current_Pct_Coded",
    src_3."EngMaths59_Grl_Est_Previous_Num_Coded" AS "EngMaths59_Grl_Est_Previous_Num_Coded",
    src_3."EngMaths59_Grl_Est_Previous_Pct_Coded" AS "EngMaths59_Grl_Est_Previous_Pct_Coded",
    src_8."EngMaths59_Grl_Est_Previous2_Pct_Coded" AS "EngMaths59_Grl_Est_Previous2_Pct_Coded",
    src_8."EngMaths59_Mob_Est_Previous2_Pct_Coded" AS "EngMaths59_Mob_Est_Previous2_Pct_Coded",
    src_2."EngMaths59_NDi_Est_Current_Num_Coded" AS "EngMaths59_NDi_Est_Current_Num_Coded",
    src_2."EngMaths59_NDi_Est_Current_Pct_Coded" AS "EngMaths59_NDi_Est_Current_Pct_Coded",
    src_2."EngMaths59_NMo_Est_Current_Num_Coded" AS "EngMaths59_NMo_Est_Current_Num_Coded",
    src_2."EngMaths59_NMo_Est_Current_Pct_Coded" AS "EngMaths59_NMo_Est_Current_Pct_Coded",
    src_3."EngMaths59_NMo_Est_Previous_Num_Coded" AS "EngMaths59_NMo_Est_Previous_Num_Coded",
    src_3."EngMaths59_NMo_Est_Previous_Pct_Coded" AS "EngMaths59_NMo_Est_Previous_Pct_Coded",
    src_1."EngMaths59_Tot_Est_Current_Num_Coded" AS "EngMaths59_Tot_Est_Current_Num_Coded",
    src_1."EngMaths59_Tot_Est_Current_Pct_Coded" AS "EngMaths59_Tot_Est_Current_Pct_Coded",
    src_3."EngMaths59_Tot_Est_Previous_Num_Coded" AS "EngMaths59_Tot_Est_Previous_Num_Coded",
    src_3."EngMaths59_Tot_Est_Previous_Pct_Coded" AS "EngMaths59_Tot_Est_Previous_Pct_Coded",
    src_7."EngMaths59_Tot_Est_Previous2_Pct_Coded" AS "EngMaths59_Tot_Est_Previous2_Pct_Coded",
    src_4."Maths4_Sum_Est_Current_Num_Coded" AS "Maths4_Sum_Est_Current_Num_Coded",
    src_5."Maths4_Sum_Est_Previous_Num_Coded" AS "Maths4_Sum_Est_Previous_Num_Coded",
    src_9."Maths4_Sum_Est_Previous2_Num_Coded" AS "Maths4_Sum_Est_Previous2_Num_Coded",
    src_4."Maths49_Sum_Est_Current_Num_Coded" AS "Maths49_Sum_Est_Current_Num_Coded",
    src_5."Maths49_Sum_Est_Previous_Num_Coded" AS "Maths49_Sum_Est_Previous_Num_Coded",
    src_9."Maths49_Sum_Est_Previous2_Num_Coded" AS "Maths49_Sum_Est_Previous2_Num_Coded",
    src_4."Maths5_Sum_Est_Current_Num_Coded" AS "Maths5_Sum_Est_Current_Num_Coded",
    src_5."Maths5_Sum_Est_Previous_Num_Coded" AS "Maths5_Sum_Est_Previous_Num_Coded",
    src_9."Maths5_Sum_Est_Previous2_Num_Coded" AS "Maths5_Sum_Est_Previous2_Num_Coded",
    src_4."Maths59_Sum_Est_Current_Num_Coded" AS "Maths59_Sum_Est_Current_Num_Coded",
    src_5."Maths59_Sum_Est_Previous_Num_Coded" AS "Maths59_Sum_Est_Previous_Num_Coded",
    src_9."Maths59_Sum_Est_Previous2_Num_Coded" AS "Maths59_Sum_Est_Previous2_Num_Coded",
    src_4."Maths6_Sum_Est_Current_Num_Coded" AS "Maths6_Sum_Est_Current_Num_Coded",
    src_5."Maths6_Sum_Est_Previous_Num_Coded" AS "Maths6_Sum_Est_Previous_Num_Coded",
    src_9."Maths6_Sum_Est_Previous2_Num_Coded" AS "Maths6_Sum_Est_Previous2_Num_Coded",
    src_4."Maths7_Sum_Est_Current_Num_Coded" AS "Maths7_Sum_Est_Current_Num_Coded",
    src_5."Maths7_Sum_Est_Previous_Num_Coded" AS "Maths7_Sum_Est_Previous_Num_Coded",
    src_9."Maths7_Sum_Est_Previous2_Num_Coded" AS "Maths7_Sum_Est_Previous2_Num_Coded",
    src_4."Maths79_Sum_Est_Current_Num_Coded" AS "Maths79_Sum_Est_Current_Num_Coded",
    src_5."Maths79_Sum_Est_Previous_Num_Coded" AS "Maths79_Sum_Est_Previous_Num_Coded",
    src_9."Maths79_Sum_Est_Previous2_Num_Coded" AS "Maths79_Sum_Est_Previous2_Num_Coded",
    src_4."Maths8_Sum_Est_Current_Num_Coded" AS "Maths8_Sum_Est_Current_Num_Coded",
    src_5."Maths8_Sum_Est_Previous_Num_Coded" AS "Maths8_Sum_Est_Previous_Num_Coded",
    src_9."Maths8_Sum_Est_Previous2_Num_Coded" AS "Maths8_Sum_Est_Previous2_Num_Coded",
    src_4."Maths9_Sum_Est_Current_Num_Coded" AS "Maths9_Sum_Est_Current_Num_Coded",
    src_5."Maths9_Sum_Est_Previous_Num_Coded" AS "Maths9_Sum_Est_Previous_Num_Coded",
    src_9."Maths9_Sum_Est_Previous2_Num_Coded" AS "Maths9_Sum_Est_Previous2_Num_Coded",
    src_4."Physics4_Sum_Est_Current_Num_Coded" AS "Physics4_Sum_Est_Current_Num_Coded",
    src_5."Physics4_Sum_Est_Previous_Num_Coded" AS "Physics4_Sum_Est_Previous_Num_Coded",
    src_9."Physics4_Sum_Est_Previous2_Num_Coded" AS "Physics4_Sum_Est_Previous2_Num_Coded",
    src_4."Physics49_Sum_Est_Current_Num_Coded" AS "Physics49_Sum_Est_Current_Num_Coded",
    src_5."Physics49_Sum_Est_Previous_Num_Coded" AS "Physics49_Sum_Est_Previous_Num_Coded",
    src_9."Physics49_Sum_Est_Previous2_Num_Coded" AS "Physics49_Sum_Est_Previous2_Num_Coded",
    src_4."Physics5_Sum_Est_Current_Num_Coded" AS "Physics5_Sum_Est_Current_Num_Coded",
    src_5."Physics5_Sum_Est_Previous_Num_Coded" AS "Physics5_Sum_Est_Previous_Num_Coded",
    src_9."Physics5_Sum_Est_Previous2_Num_Coded" AS "Physics5_Sum_Est_Previous2_Num_Coded",
    src_4."Physics59_Sum_Est_Current_Num_Coded" AS "Physics59_Sum_Est_Current_Num_Coded",
    src_5."Physics59_Sum_Est_Previous_Num_Coded" AS "Physics59_Sum_Est_Previous_Num_Coded",
    src_9."Physics59_Sum_Est_Previous2_Num_Coded" AS "Physics59_Sum_Est_Previous2_Num_Coded",
    src_4."Physics6_Sum_Est_Current_Num_Coded" AS "Physics6_Sum_Est_Current_Num_Coded",
    src_5."Physics6_Sum_Est_Previous_Num_Coded" AS "Physics6_Sum_Est_Previous_Num_Coded",
    src_9."Physics6_Sum_Est_Previous2_Num_Coded" AS "Physics6_Sum_Est_Previous2_Num_Coded",
    src_4."Physics7_Sum_Est_Current_Num_Coded" AS "Physics7_Sum_Est_Current_Num_Coded",
    src_5."Physics7_Sum_Est_Previous_Num_Coded" AS "Physics7_Sum_Est_Previous_Num_Coded",
    src_9."Physics7_Sum_Est_Previous2_Num_Coded" AS "Physics7_Sum_Est_Previous2_Num_Coded",
    src_4."Physics79_Sum_Est_Current_Num_Coded" AS "Physics79_Sum_Est_Current_Num_Coded",
    src_5."Physics79_Sum_Est_Previous_Num_Coded" AS "Physics79_Sum_Est_Previous_Num_Coded",
    src_9."Physics79_Sum_Est_Previous2_Num_Coded" AS "Physics79_Sum_Est_Previous2_Num_Coded",
    src_4."Physics8_Sum_Est_Current_Num_Coded" AS "Physics8_Sum_Est_Current_Num_Coded",
    src_5."Physics8_Sum_Est_Previous_Num_Coded" AS "Physics8_Sum_Est_Previous_Num_Coded",
    src_9."Physics8_Sum_Est_Previous2_Num_Coded" AS "Physics8_Sum_Est_Previous2_Num_Coded",
    src_4."Physics9_Sum_Est_Current_Num_Coded" AS "Physics9_Sum_Est_Current_Num_Coded",
    src_5."Physics9_Sum_Est_Previous_Num_Coded" AS "Physics9_Sum_Est_Previous_Num_Coded",
    src_9."Physics9_Sum_Est_Previous2_Num_Coded" AS "Physics9_Sum_Est_Previous2_Num_Coded",
    src_6."Prog8_Banding_Est_Previous" AS "Prog8_Banding_Est_Previous",
    src_8."Prog8_Banding_Est_Previous2" AS "Prog8_Banding_Est_Previous2",
    src_3."Prog8_CI_Lower_Est_Previous_Num_Coded" AS "Prog8_CI_Lower_Est_Previous_Num_Coded",
    src_8."Prog8_CI_Lower_Est_Previous2_Num_Coded" AS "Prog8_CI_Lower_Est_Previous2_Num_Coded",
    src_3."Prog8_CI_Upper_Est_Previous_Num_Coded" AS "Prog8_CI_Upper_Est_Previous_Num_Coded",
    src_8."Prog8_CI_Upper_Est_Previous2_Num_Coded" AS "Prog8_CI_Upper_Est_Previous2_Num_Coded",
    src_3."Prog8_Tot_Est_Previous_Num_Coded" AS "Prog8_Tot_Est_Previous_Num_Coded",
    src_8."Prog8_Tot_Est_Previous2_Num_Coded" AS "Prog8_Tot_Est_Previous2_Num_Coded",
    src_3."Prog8_TotPup_Est_Previous_Num_Coded" AS "Prog8_TotPup_Est_Previous_Num_Coded",
    src_8."Prog8_TotPup_Est_Previous2_Num_Coded" AS "Prog8_TotPup_Est_Previous2_Num_Coded",
    src_3."Pup_Tot_Est_Previous_Num_Coded" AS "Pup_Tot_Est_Previous_Num_Coded",
    src_8."Pup_Tot_Est_Previous2_Num_Coded" AS "Pup_Tot_Est_Previous2_Num_Coded"
FROM all_ids a
LEFT JOIN src_1 ON src_1."Id" = a."Id"
LEFT JOIN src_2 ON src_2."Id" = a."Id"
LEFT JOIN src_3 ON src_3."Id" = a."Id"
LEFT JOIN src_4 ON src_4."Id" = a."Id"
LEFT JOIN src_5 ON src_5."Id" = a."Id"
LEFT JOIN src_6 ON src_6."Id" = a."Id"
LEFT JOIN src_7 ON src_7."Id" = a."Id"
LEFT JOIN src_8 ON src_8."Id" = a."Id"
LEFT JOIN src_9 ON src_9."Id" = a."Id"
LEFT JOIN v_establishment e ON e."URN" = a."Id"
;
