-- AUTO-GENERATED MATERIALIZED VIEW: v_establishment_performance

DROP MATERIALIZED VIEW IF EXISTS v_establishment_performance;

CREATE MATERIALIZED VIEW v_establishment_performance AS
WITH
src_1 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."attainment8_average" END) AS "Attainment8_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."attainment8_average" END) AS "Attainment8_Dis_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."attainment8_average" END) AS "Attainment8_EAL_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."attainment8_average" END) AS "Attainment8_Grl_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN t."attainment8_average" END) AS "Attainment8_NDi_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."attainment8_average" END) AS "Attainment8_NMo_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."attainment8_average" END) AS "Attainment8_Tot_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."engmath_94_total" END) AS "EngMaths49_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."engmath_94_percent" END) AS "EngMaths49_Boy_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."engmath_94_total" END) AS "EngMaths49_Dis_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."engmath_94_percent" END) AS "EngMaths49_Dis_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."engmath_94_total" END) AS "EngMaths49_EAL_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."engmath_94_percent" END) AS "EngMaths49_EAL_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."engmath_94_total" END) AS "EngMaths49_Grl_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."engmath_94_percent" END) AS "EngMaths49_Grl_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN t."engmath_94_total" END) AS "EngMaths49_NDi_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN t."engmath_94_percent" END) AS "EngMaths49_NDi_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."engmath_94_total" END) AS "EngMaths49_NMo_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."engmath_94_percent" END) AS "EngMaths49_NMo_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."engmath_94_total" END) AS "EngMaths49_Tot_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."engmath_94_percent" END) AS "EngMaths49_Tot_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."engmath_95_total" END) AS "EngMaths59_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."engmath_95_percent" END) AS "EngMaths59_Boy_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."engmath_95_total" END) AS "EngMaths59_Dis_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."engmath_95_percent" END) AS "EngMaths59_Dis_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."engmath_95_total" END) AS "EngMaths59_EAL_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."engmath_95_percent" END) AS "EngMaths59_EAL_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."engmath_95_total" END) AS "EngMaths59_Grl_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."engmath_95_percent" END) AS "EngMaths59_Grl_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN t."engmath_95_total" END) AS "EngMaths59_NDi_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN t."engmath_95_percent" END) AS "EngMaths59_NDi_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."engmath_95_total" END) AS "EngMaths59_NMo_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."engmath_95_percent" END) AS "EngMaths59_NMo_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."engmath_95_total" END) AS "EngMaths59_Tot_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."engmath_95_percent" END) AS "EngMaths59_Tot_Est_Current_Pct"
    FROM t_202425_performance_t_058e5cff85 t
    GROUP BY t."school_urn"
)
,
src_2 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."avg_att8" END) AS "Attainment8_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."avg_att8" END) AS "Attainment8_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."avg_att8" END) AS "Attainment8_EAL_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."avg_att8" END) AS "Attainment8_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."avg_att8" END) AS "Attainment8_NMo_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."avg_att8" END) AS "Attainment8_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."t_l2basics_94" END) AS "EngMaths49_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."pt_l2basics_94" END) AS "EngMaths49_Boy_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."t_l2basics_94" END) AS "EngMaths49_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."pt_l2basics_94" END) AS "EngMaths49_Dis_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."t_l2basics_94" END) AS "EngMaths49_EAL_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."pt_l2basics_94" END) AS "EngMaths49_EAL_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."t_l2basics_94" END) AS "EngMaths49_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."pt_l2basics_94" END) AS "EngMaths49_Grl_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."t_l2basics_94" END) AS "EngMaths49_NMo_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."pt_l2basics_94" END) AS "EngMaths49_NMo_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."t_l2basics_94" END) AS "EngMaths49_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."pt_l2basics_94" END) AS "EngMaths49_Tot_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."t_l2basics_95" END) AS "EngMaths59_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."pt_l2basics_95" END) AS "EngMaths59_Boy_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."t_l2basics_95" END) AS "EngMaths59_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."pt_l2basics_95" END) AS "EngMaths59_Dis_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."t_l2basics_95" END) AS "EngMaths59_EAL_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."pt_l2basics_95" END) AS "EngMaths59_EAL_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."t_l2basics_95" END) AS "EngMaths59_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."pt_l2basics_95" END) AS "EngMaths59_Grl_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."t_l2basics_95" END) AS "EngMaths59_NMo_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."pt_l2basics_95" END) AS "EngMaths59_NMo_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."t_l2basics_95" END) AS "EngMaths59_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."pt_l2basics_95" END) AS "EngMaths59_Tot_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."avg_p8score" END) AS "Prog8_Tot_Est_Previous_Num"
    FROM t_202324_performance_t_371eb4e56c t
    GROUP BY t."school_urn"
)
,
src_3 AS (
    SELECT
        t."urn" AS "Id",
        MAX(CASE WHEN TRUE THEN t."att8scr_boys" END) AS "Attainment8_Boy_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."att8scr_fsm6cla1a" END) AS "Attainment8_Dis_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."att8scr_eal" END) AS "Attainment8_EAL_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."att8scr_girls" END) AS "Attainment8_Grl_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."att8scr_nfsm6cla1a" END) AS "Attainment8_NDi_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."att8scr_nmob" END) AS "Attainment8_NMo_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."att8scr" END) AS "Attainment8_Tot_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."pbl2basics_94" END) AS "EngMaths49_Boy_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."ptfsm6cla1abasics_94" END) AS "EngMaths49_Dis_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."ptl2basicseal_94" END) AS "EngMaths49_EAL_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."pgl2basics_94" END) AS "EngMaths49_Grl_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."ptl2basicsnmob_94" END) AS "EngMaths49_Mob_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."ptl2basics_94" END) AS "EngMaths49_Tot_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."pbl2basics_95" END) AS "EngMaths59_Boy_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."ptfsm6cla1abasics_95" END) AS "EngMaths59_Dis_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."ptl2basicseal_95" END) AS "EngMaths59_EAL_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."pgl2basics_95" END) AS "EngMaths59_Grl_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."ptl2basicsnmob_95" END) AS "EngMaths59_Mob_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."ptl2basics_95" END) AS "EngMaths59_Tot_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."p8mea" END) AS "Prog8_Tot_Est_Previous2_Num"
    FROM t_2022_2023_england_ks_28199246f1 t
    GROUP BY t."urn"
)
,
src_4 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Bio49_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Bio59_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "Bio79_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Chem49_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Chem59_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "Chem79_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RAE1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "CombSci49_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RAE1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "CombSci59_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RAE1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "CombSci79_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "EngLang49_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "EngLang59_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "EngLang79_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "EngLit49_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "EngLit59_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "EngLit79_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Maths49_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Maths59_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "Maths79_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Physics49_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Physics59_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "Physics79_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4' THEN t."number_achieving" END) AS "Bio4_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '5' THEN t."number_achieving" END) AS "Bio5_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '6' THEN t."number_achieving" END) AS "Bio6_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '7' THEN t."number_achieving" END) AS "Bio7_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '8' THEN t."number_achieving" END) AS "Bio8_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '9' THEN t."number_achieving" END) AS "Bio9_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4' THEN t."number_achieving" END) AS "Chem4_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5' THEN t."number_achieving" END) AS "Chem5_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '6' THEN t."number_achieving" END) AS "Chem6_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '7' THEN t."number_achieving" END) AS "Chem7_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '8' THEN t."number_achieving" END) AS "Chem8_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '9' THEN t."number_achieving" END) AS "Chem9_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '43' THEN t."number_achieving" END) AS "CombSci43_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '44' THEN t."number_achieving" END) AS "CombSci44_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '54' THEN t."number_achieving" END) AS "CombSci54_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '55' THEN t."number_achieving" END) AS "CombSci55_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '65' THEN t."number_achieving" END) AS "CombSci65_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '66' THEN t."number_achieving" END) AS "CombSci66_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '76' THEN t."number_achieving" END) AS "CombSci76_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '77' THEN t."number_achieving" END) AS "CombSci77_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '87' THEN t."number_achieving" END) AS "CombSci87_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '88' THEN t."number_achieving" END) AS "CombSci88_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '98' THEN t."number_achieving" END) AS "CombSci98_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99' THEN t."number_achieving" END) AS "CombSci99_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4' THEN t."number_achieving" END) AS "EngLang4_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5' THEN t."number_achieving" END) AS "EngLang5_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '6' THEN t."number_achieving" END) AS "EngLang6_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7' THEN t."number_achieving" END) AS "EngLang7_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '8' THEN t."number_achieving" END) AS "EngLang8_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '9' THEN t."number_achieving" END) AS "EngLang9_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4' THEN t."number_achieving" END) AS "EngLit4_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5' THEN t."number_achieving" END) AS "EngLit5_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '6' THEN t."number_achieving" END) AS "EngLit6_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7' THEN t."number_achieving" END) AS "EngLit7_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '8' THEN t."number_achieving" END) AS "EngLit8_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '9' THEN t."number_achieving" END) AS "EngLit9_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4' THEN t."number_achieving" END) AS "Maths4_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5' THEN t."number_achieving" END) AS "Maths5_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '6' THEN t."number_achieving" END) AS "Maths6_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7' THEN t."number_achieving" END) AS "Maths7_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '8' THEN t."number_achieving" END) AS "Maths8_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '9' THEN t."number_achieving" END) AS "Maths9_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4' THEN t."number_achieving" END) AS "Physics4_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5' THEN t."number_achieving" END) AS "Physics5_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '6' THEN t."number_achieving" END) AS "Physics6_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7' THEN t."number_achieving" END) AS "Physics7_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '8' THEN t."number_achieving" END) AS "Physics8_Sum_Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '9' THEN t."number_achieving" END) AS "Physics9_Sum_Est_Current_Num"
    FROM t_202425_subject_schoo_70cc75bcb6 t
    GROUP BY t."school_urn"
)
,
src_5 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Bio49_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Bio59_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "Bio79_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Chem49_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Chem59_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "Chem79_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RAE1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "CombSci49_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RAE1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "CombSci59_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RAE1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "CombSci79_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "EngLang49_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "EngLang59_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "EngLang79_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "EngLit49_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "EngLit59_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "EngLit79_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Maths49_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Maths59_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "Maths79_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Physics49_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Physics59_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "Physics79_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4' THEN t."number_achieving" END) AS "Bio4_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '5' THEN t."number_achieving" END) AS "Bio5_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '6' THEN t."number_achieving" END) AS "Bio6_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '7' THEN t."number_achieving" END) AS "Bio7_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '8' THEN t."number_achieving" END) AS "Bio8_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '9' THEN t."number_achieving" END) AS "Bio9_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4' THEN t."number_achieving" END) AS "Chem4_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5' THEN t."number_achieving" END) AS "Chem5_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '6' THEN t."number_achieving" END) AS "Chem6_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '7' THEN t."number_achieving" END) AS "Chem7_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '8' THEN t."number_achieving" END) AS "Chem8_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '9' THEN t."number_achieving" END) AS "Chem9_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '43' THEN t."number_achieving" END) AS "CombSci43_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '44' THEN t."number_achieving" END) AS "CombSci44_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '54' THEN t."number_achieving" END) AS "CombSci54_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '55' THEN t."number_achieving" END) AS "CombSci55_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '65' THEN t."number_achieving" END) AS "CombSci65_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '66' THEN t."number_achieving" END) AS "CombSci66_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '76' THEN t."number_achieving" END) AS "CombSci76_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '77' THEN t."number_achieving" END) AS "CombSci77_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '87' THEN t."number_achieving" END) AS "CombSci87_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '88' THEN t."number_achieving" END) AS "CombSci88_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '98' THEN t."number_achieving" END) AS "CombSci98_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99' THEN t."number_achieving" END) AS "CombSci99_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4' THEN t."number_achieving" END) AS "EngLang4_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5' THEN t."number_achieving" END) AS "EngLang5_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '6' THEN t."number_achieving" END) AS "EngLang6_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7' THEN t."number_achieving" END) AS "EngLang7_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '8' THEN t."number_achieving" END) AS "EngLang8_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '9' THEN t."number_achieving" END) AS "EngLang9_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4' THEN t."number_achieving" END) AS "EngLit4_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5' THEN t."number_achieving" END) AS "EngLit5_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '6' THEN t."number_achieving" END) AS "EngLit6_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7' THEN t."number_achieving" END) AS "EngLit7_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '8' THEN t."number_achieving" END) AS "EngLit8_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '9' THEN t."number_achieving" END) AS "EngLit9_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4' THEN t."number_achieving" END) AS "Maths4_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5' THEN t."number_achieving" END) AS "Maths5_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '6' THEN t."number_achieving" END) AS "Maths6_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7' THEN t."number_achieving" END) AS "Maths7_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '8' THEN t."number_achieving" END) AS "Maths8_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '9' THEN t."number_achieving" END) AS "Maths9_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4' THEN t."number_achieving" END) AS "Physics4_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5' THEN t."number_achieving" END) AS "Physics5_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '6' THEN t."number_achieving" END) AS "Physics6_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7' THEN t."number_achieving" END) AS "Physics7_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '8' THEN t."number_achieving" END) AS "Physics8_Sum_Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '9' THEN t."number_achieving" END) AS "Physics9_Sum_Est_Previous_Num"
    FROM t_202324_subject_schoo_84751f4769 t
    GROUP BY t."school_urn"
)
,
src_6 AS (
    SELECT
        t."unique_reference_number__urn_" AS "Id",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "Bio49_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "Bio59_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade" END) AS "Bio79_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "Chem49_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "Chem59_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade" END) AS "Chem79_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "CombSci49_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "CombSci59_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade" END) AS "CombSci79_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "EngLang49_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "EngLang59_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade" END) AS "EngLang79_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "EngLit49_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "EngLit59_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade" END) AS "EngLit79_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "Maths49_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "Maths59_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade" END) AS "Maths79_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "Physics49_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5+6+7+8+9' THEN t."number_of_entries_at_grade" END) AS "Physics59_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7+8+9' THEN t."number_of_entries_at_grade" END) AS "Physics79_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4' THEN t."number_of_entries_at_grade" END) AS "Bio4_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '5' THEN t."number_of_entries_at_grade" END) AS "Bio5_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '6' THEN t."number_of_entries_at_grade" END) AS "Bio6_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '7' THEN t."number_of_entries_at_grade" END) AS "Bio7_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '8' THEN t."number_of_entries_at_grade" END) AS "Bio8_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '9' THEN t."number_of_entries_at_grade" END) AS "Bio9_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4' THEN t."number_of_entries_at_grade" END) AS "Chem4_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5' THEN t."number_of_entries_at_grade" END) AS "Chem5_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '6' THEN t."number_of_entries_at_grade" END) AS "Chem6_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '7' THEN t."number_of_entries_at_grade" END) AS "Chem7_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '8' THEN t."number_of_entries_at_grade" END) AS "Chem8_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '9' THEN t."number_of_entries_at_grade" END) AS "Chem9_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '43' THEN t."number_of_entries_at_grade" END) AS "CombSci43_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '44' THEN t."number_of_entries_at_grade" END) AS "CombSci44_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '54' THEN t."number_of_entries_at_grade" END) AS "CombSci54_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '55' THEN t."number_of_entries_at_grade" END) AS "CombSci55_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '65' THEN t."number_of_entries_at_grade" END) AS "CombSci65_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '66' THEN t."number_of_entries_at_grade" END) AS "CombSci66_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '76' THEN t."number_of_entries_at_grade" END) AS "CombSci76_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '77' THEN t."number_of_entries_at_grade" END) AS "CombSci77_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '87' THEN t."number_of_entries_at_grade" END) AS "CombSci87_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '88' THEN t."number_of_entries_at_grade" END) AS "CombSci88_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '98' THEN t."number_of_entries_at_grade" END) AS "CombSci98_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RA1E' AND t."grade" = '99' THEN t."number_of_entries_at_grade" END) AS "CombSci99_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4' THEN t."number_of_entries_at_grade" END) AS "EngLang4_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5' THEN t."number_of_entries_at_grade" END) AS "EngLang5_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '6' THEN t."number_of_entries_at_grade" END) AS "EngLang6_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7' THEN t."number_of_entries_at_grade" END) AS "EngLang7_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '8' THEN t."number_of_entries_at_grade" END) AS "EngLang8_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '9' THEN t."number_of_entries_at_grade" END) AS "EngLang9_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4' THEN t."number_of_entries_at_grade" END) AS "EngLit4_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5' THEN t."number_of_entries_at_grade" END) AS "EngLit5_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '6' THEN t."number_of_entries_at_grade" END) AS "EngLit6_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7' THEN t."number_of_entries_at_grade" END) AS "EngLit7_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '8' THEN t."number_of_entries_at_grade" END) AS "EngLit8_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '9' THEN t."number_of_entries_at_grade" END) AS "EngLit9_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4' THEN t."number_of_entries_at_grade" END) AS "Maths4_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5' THEN t."number_of_entries_at_grade" END) AS "Maths5_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '6' THEN t."number_of_entries_at_grade" END) AS "Maths6_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7' THEN t."number_of_entries_at_grade" END) AS "Maths7_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '8' THEN t."number_of_entries_at_grade" END) AS "Maths8_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '9' THEN t."number_of_entries_at_grade" END) AS "Maths9_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4' THEN t."number_of_entries_at_grade" END) AS "Physics4_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5' THEN t."number_of_entries_at_grade" END) AS "Physics5_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '6' THEN t."number_of_entries_at_grade" END) AS "Physics6_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7' THEN t."number_of_entries_at_grade" END) AS "Physics7_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '8' THEN t."number_of_entries_at_grade" END) AS "Physics8_Sum_Est_Previous2_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '9' THEN t."number_of_entries_at_grade" END) AS "Physics9_Sum_Est_Previous2_Num"
    FROM t_england_ks4underlyin_effb560d65 t
    GROUP BY t."unique_reference_number__urn_"
)
,
all_ids AS (
    SELECT "Id" FROM src_1
    UNION SELECT "Id" FROM src_2
    UNION SELECT "Id" FROM src_3
    UNION SELECT "Id" FROM src_4
    UNION SELECT "Id" FROM src_5
    UNION SELECT "Id" FROM src_6
)

SELECT
    a."Id" AS "Id",
    e."LAId" AS "LAId",
    e."LAName" AS "LAName",
    e."RegionId" AS "RegionId",
    e."RegionName" AS "RegionName",
    src_1."Attainment8_Boy_Est_Current_Num" AS "Attainment8_Boy_Est_Current_Num",
    src_2."Attainment8_Boy_Est_Previous_Num" AS "Attainment8_Boy_Est_Previous_Num",
    src_3."Attainment8_Boy_Est_Previous2_Num" AS "Attainment8_Boy_Est_Previous2_Num",
    src_1."Attainment8_Dis_Est_Current_Num" AS "Attainment8_Dis_Est_Current_Num",
    src_2."Attainment8_Dis_Est_Previous_Num" AS "Attainment8_Dis_Est_Previous_Num",
    src_3."Attainment8_Dis_Est_Previous2_Num" AS "Attainment8_Dis_Est_Previous2_Num",
    src_1."Attainment8_EAL_Est_Current_Num" AS "Attainment8_EAL_Est_Current_Num",
    src_2."Attainment8_EAL_Est_Previous_Num" AS "Attainment8_EAL_Est_Previous_Num",
    src_3."Attainment8_EAL_Est_Previous2_Num" AS "Attainment8_EAL_Est_Previous2_Num",
    src_1."Attainment8_Grl_Est_Current_Num" AS "Attainment8_Grl_Est_Current_Num",
    src_2."Attainment8_Grl_Est_Previous_Num" AS "Attainment8_Grl_Est_Previous_Num",
    src_3."Attainment8_Grl_Est_Previous2_Num" AS "Attainment8_Grl_Est_Previous2_Num",
    src_1."Attainment8_NDi_Est_Current_Num" AS "Attainment8_NDi_Est_Current_Num",
    src_3."Attainment8_NDi_Est_Previous2_Num" AS "Attainment8_NDi_Est_Previous2_Num",
    src_1."Attainment8_NMo_Est_Current_Num" AS "Attainment8_NMo_Est_Current_Num",
    src_2."Attainment8_NMo_Est_Previous_Num" AS "Attainment8_NMo_Est_Previous_Num",
    src_3."Attainment8_NMo_Est_Previous2_Num" AS "Attainment8_NMo_Est_Previous2_Num",
    src_1."Attainment8_Tot_Est_Current_Num" AS "Attainment8_Tot_Est_Current_Num",
    src_2."Attainment8_Tot_Est_Previous_Num" AS "Attainment8_Tot_Est_Previous_Num",
    src_3."Attainment8_Tot_Est_Previous2_Num" AS "Attainment8_Tot_Est_Previous2_Num",
    src_4."Bio4_Sum_Est_Current_Num" AS "Bio4_Sum_Est_Current_Num",
    src_5."Bio4_Sum_Est_Previous_Num" AS "Bio4_Sum_Est_Previous_Num",
    src_6."Bio4_Sum_Est_Previous2_Num" AS "Bio4_Sum_Est_Previous2_Num",
    src_4."Bio49_Sum_Est_Current_Num" AS "Bio49_Sum_Est_Current_Num",
    src_5."Bio49_Sum_Est_Previous_Num" AS "Bio49_Sum_Est_Previous_Num",
    src_6."Bio49_Sum_Est_Previous2_Num" AS "Bio49_Sum_Est_Previous2_Num",
    src_4."Bio5_Sum_Est_Current_Num" AS "Bio5_Sum_Est_Current_Num",
    src_5."Bio5_Sum_Est_Previous_Num" AS "Bio5_Sum_Est_Previous_Num",
    src_6."Bio5_Sum_Est_Previous2_Num" AS "Bio5_Sum_Est_Previous2_Num",
    src_4."Bio59_Sum_Est_Current_Num" AS "Bio59_Sum_Est_Current_Num",
    src_5."Bio59_Sum_Est_Previous_Num" AS "Bio59_Sum_Est_Previous_Num",
    src_6."Bio59_Sum_Est_Previous2_Num" AS "Bio59_Sum_Est_Previous2_Num",
    src_4."Bio6_Sum_Est_Current_Num" AS "Bio6_Sum_Est_Current_Num",
    src_5."Bio6_Sum_Est_Previous_Num" AS "Bio6_Sum_Est_Previous_Num",
    src_6."Bio6_Sum_Est_Previous2_Num" AS "Bio6_Sum_Est_Previous2_Num",
    src_4."Bio7_Sum_Est_Current_Num" AS "Bio7_Sum_Est_Current_Num",
    src_5."Bio7_Sum_Est_Previous_Num" AS "Bio7_Sum_Est_Previous_Num",
    src_6."Bio7_Sum_Est_Previous2_Num" AS "Bio7_Sum_Est_Previous2_Num",
    src_4."Bio79_Sum_Est_Current_Num" AS "Bio79_Sum_Est_Current_Num",
    src_5."Bio79_Sum_Est_Previous_Num" AS "Bio79_Sum_Est_Previous_Num",
    src_6."Bio79_Sum_Est_Previous2_Num" AS "Bio79_Sum_Est_Previous2_Num",
    src_4."Bio8_Sum_Est_Current_Num" AS "Bio8_Sum_Est_Current_Num",
    src_5."Bio8_Sum_Est_Previous_Num" AS "Bio8_Sum_Est_Previous_Num",
    src_6."Bio8_Sum_Est_Previous2_Num" AS "Bio8_Sum_Est_Previous2_Num",
    src_4."Bio9_Sum_Est_Current_Num" AS "Bio9_Sum_Est_Current_Num",
    src_5."Bio9_Sum_Est_Previous_Num" AS "Bio9_Sum_Est_Previous_Num",
    src_6."Bio9_Sum_Est_Previous2_Num" AS "Bio9_Sum_Est_Previous2_Num",
    src_4."Chem4_Sum_Est_Current_Num" AS "Chem4_Sum_Est_Current_Num",
    src_5."Chem4_Sum_Est_Previous_Num" AS "Chem4_Sum_Est_Previous_Num",
    src_6."Chem4_Sum_Est_Previous2_Num" AS "Chem4_Sum_Est_Previous2_Num",
    src_4."Chem49_Sum_Est_Current_Num" AS "Chem49_Sum_Est_Current_Num",
    src_5."Chem49_Sum_Est_Previous_Num" AS "Chem49_Sum_Est_Previous_Num",
    src_6."Chem49_Sum_Est_Previous2_Num" AS "Chem49_Sum_Est_Previous2_Num",
    src_4."Chem5_Sum_Est_Current_Num" AS "Chem5_Sum_Est_Current_Num",
    src_5."Chem5_Sum_Est_Previous_Num" AS "Chem5_Sum_Est_Previous_Num",
    src_6."Chem5_Sum_Est_Previous2_Num" AS "Chem5_Sum_Est_Previous2_Num",
    src_4."Chem59_Sum_Est_Current_Num" AS "Chem59_Sum_Est_Current_Num",
    src_5."Chem59_Sum_Est_Previous_Num" AS "Chem59_Sum_Est_Previous_Num",
    src_6."Chem59_Sum_Est_Previous2_Num" AS "Chem59_Sum_Est_Previous2_Num",
    src_4."Chem6_Sum_Est_Current_Num" AS "Chem6_Sum_Est_Current_Num",
    src_5."Chem6_Sum_Est_Previous_Num" AS "Chem6_Sum_Est_Previous_Num",
    src_6."Chem6_Sum_Est_Previous2_Num" AS "Chem6_Sum_Est_Previous2_Num",
    src_4."Chem7_Sum_Est_Current_Num" AS "Chem7_Sum_Est_Current_Num",
    src_5."Chem7_Sum_Est_Previous_Num" AS "Chem7_Sum_Est_Previous_Num",
    src_6."Chem7_Sum_Est_Previous2_Num" AS "Chem7_Sum_Est_Previous2_Num",
    src_4."Chem79_Sum_Est_Current_Num" AS "Chem79_Sum_Est_Current_Num",
    src_5."Chem79_Sum_Est_Previous_Num" AS "Chem79_Sum_Est_Previous_Num",
    src_6."Chem79_Sum_Est_Previous2_Num" AS "Chem79_Sum_Est_Previous2_Num",
    src_4."Chem8_Sum_Est_Current_Num" AS "Chem8_Sum_Est_Current_Num",
    src_5."Chem8_Sum_Est_Previous_Num" AS "Chem8_Sum_Est_Previous_Num",
    src_6."Chem8_Sum_Est_Previous2_Num" AS "Chem8_Sum_Est_Previous2_Num",
    src_4."Chem9_Sum_Est_Current_Num" AS "Chem9_Sum_Est_Current_Num",
    src_5."Chem9_Sum_Est_Previous_Num" AS "Chem9_Sum_Est_Previous_Num",
    src_6."Chem9_Sum_Est_Previous2_Num" AS "Chem9_Sum_Est_Previous2_Num",
    src_4."CombSci43_Sum_Est_Current_Num" AS "CombSci43_Sum_Est_Current_Num",
    src_5."CombSci43_Sum_Est_Previous_Num" AS "CombSci43_Sum_Est_Previous_Num",
    src_6."CombSci43_Sum_Est_Previous2_Num" AS "CombSci43_Sum_Est_Previous2_Num",
    src_4."CombSci44_Sum_Est_Current_Num" AS "CombSci44_Sum_Est_Current_Num",
    src_5."CombSci44_Sum_Est_Previous_Num" AS "CombSci44_Sum_Est_Previous_Num",
    src_6."CombSci44_Sum_Est_Previous2_Num" AS "CombSci44_Sum_Est_Previous2_Num",
    src_4."CombSci49_Sum_Est_Current_Num" AS "CombSci49_Sum_Est_Current_Num",
    src_5."CombSci49_Sum_Est_Previous_Num" AS "CombSci49_Sum_Est_Previous_Num",
    src_6."CombSci49_Sum_Est_Previous2_Num" AS "CombSci49_Sum_Est_Previous2_Num",
    src_4."CombSci54_Sum_Est_Current_Num" AS "CombSci54_Sum_Est_Current_Num",
    src_5."CombSci54_Sum_Est_Previous_Num" AS "CombSci54_Sum_Est_Previous_Num",
    src_6."CombSci54_Sum_Est_Previous2_Num" AS "CombSci54_Sum_Est_Previous2_Num",
    src_4."CombSci55_Sum_Est_Current_Num" AS "CombSci55_Sum_Est_Current_Num",
    src_5."CombSci55_Sum_Est_Previous_Num" AS "CombSci55_Sum_Est_Previous_Num",
    src_6."CombSci55_Sum_Est_Previous2_Num" AS "CombSci55_Sum_Est_Previous2_Num",
    src_4."CombSci59_Sum_Est_Current_Num" AS "CombSci59_Sum_Est_Current_Num",
    src_5."CombSci59_Sum_Est_Previous_Num" AS "CombSci59_Sum_Est_Previous_Num",
    src_6."CombSci59_Sum_Est_Previous2_Num" AS "CombSci59_Sum_Est_Previous2_Num",
    src_4."CombSci65_Sum_Est_Current_Num" AS "CombSci65_Sum_Est_Current_Num",
    src_5."CombSci65_Sum_Est_Previous_Num" AS "CombSci65_Sum_Est_Previous_Num",
    src_6."CombSci65_Sum_Est_Previous2_Num" AS "CombSci65_Sum_Est_Previous2_Num",
    src_4."CombSci66_Sum_Est_Current_Num" AS "CombSci66_Sum_Est_Current_Num",
    src_5."CombSci66_Sum_Est_Previous_Num" AS "CombSci66_Sum_Est_Previous_Num",
    src_6."CombSci66_Sum_Est_Previous2_Num" AS "CombSci66_Sum_Est_Previous2_Num",
    src_4."CombSci76_Sum_Est_Current_Num" AS "CombSci76_Sum_Est_Current_Num",
    src_5."CombSci76_Sum_Est_Previous_Num" AS "CombSci76_Sum_Est_Previous_Num",
    src_6."CombSci76_Sum_Est_Previous2_Num" AS "CombSci76_Sum_Est_Previous2_Num",
    src_4."CombSci77_Sum_Est_Current_Num" AS "CombSci77_Sum_Est_Current_Num",
    src_5."CombSci77_Sum_Est_Previous_Num" AS "CombSci77_Sum_Est_Previous_Num",
    src_6."CombSci77_Sum_Est_Previous2_Num" AS "CombSci77_Sum_Est_Previous2_Num",
    src_4."CombSci79_Sum_Est_Current_Num" AS "CombSci79_Sum_Est_Current_Num",
    src_5."CombSci79_Sum_Est_Previous_Num" AS "CombSci79_Sum_Est_Previous_Num",
    src_6."CombSci79_Sum_Est_Previous2_Num" AS "CombSci79_Sum_Est_Previous2_Num",
    src_4."CombSci87_Sum_Est_Current_Num" AS "CombSci87_Sum_Est_Current_Num",
    src_5."CombSci87_Sum_Est_Previous_Num" AS "CombSci87_Sum_Est_Previous_Num",
    src_6."CombSci87_Sum_Est_Previous2_Num" AS "CombSci87_Sum_Est_Previous2_Num",
    src_4."CombSci88_Sum_Est_Current_Num" AS "CombSci88_Sum_Est_Current_Num",
    src_5."CombSci88_Sum_Est_Previous_Num" AS "CombSci88_Sum_Est_Previous_Num",
    src_6."CombSci88_Sum_Est_Previous2_Num" AS "CombSci88_Sum_Est_Previous2_Num",
    src_4."CombSci98_Sum_Est_Current_Num" AS "CombSci98_Sum_Est_Current_Num",
    src_5."CombSci98_Sum_Est_Previous_Num" AS "CombSci98_Sum_Est_Previous_Num",
    src_6."CombSci98_Sum_Est_Previous2_Num" AS "CombSci98_Sum_Est_Previous2_Num",
    src_4."CombSci99_Sum_Est_Current_Num" AS "CombSci99_Sum_Est_Current_Num",
    src_5."CombSci99_Sum_Est_Previous_Num" AS "CombSci99_Sum_Est_Previous_Num",
    src_6."CombSci99_Sum_Est_Previous2_Num" AS "CombSci99_Sum_Est_Previous2_Num",
    src_4."EngLang4_Sum_Est_Current_Num" AS "EngLang4_Sum_Est_Current_Num",
    src_5."EngLang4_Sum_Est_Previous_Num" AS "EngLang4_Sum_Est_Previous_Num",
    src_6."EngLang4_Sum_Est_Previous2_Num" AS "EngLang4_Sum_Est_Previous2_Num",
    src_4."EngLang49_Sum_Est_Current_Num" AS "EngLang49_Sum_Est_Current_Num",
    src_5."EngLang49_Sum_Est_Previous_Num" AS "EngLang49_Sum_Est_Previous_Num",
    src_6."EngLang49_Sum_Est_Previous2_Num" AS "EngLang49_Sum_Est_Previous2_Num",
    src_4."EngLang5_Sum_Est_Current_Num" AS "EngLang5_Sum_Est_Current_Num",
    src_5."EngLang5_Sum_Est_Previous_Num" AS "EngLang5_Sum_Est_Previous_Num",
    src_6."EngLang5_Sum_Est_Previous2_Num" AS "EngLang5_Sum_Est_Previous2_Num",
    src_4."EngLang59_Sum_Est_Current_Num" AS "EngLang59_Sum_Est_Current_Num",
    src_5."EngLang59_Sum_Est_Previous_Num" AS "EngLang59_Sum_Est_Previous_Num",
    src_6."EngLang59_Sum_Est_Previous2_Num" AS "EngLang59_Sum_Est_Previous2_Num",
    src_4."EngLang6_Sum_Est_Current_Num" AS "EngLang6_Sum_Est_Current_Num",
    src_5."EngLang6_Sum_Est_Previous_Num" AS "EngLang6_Sum_Est_Previous_Num",
    src_6."EngLang6_Sum_Est_Previous2_Num" AS "EngLang6_Sum_Est_Previous2_Num",
    src_4."EngLang7_Sum_Est_Current_Num" AS "EngLang7_Sum_Est_Current_Num",
    src_5."EngLang7_Sum_Est_Previous_Num" AS "EngLang7_Sum_Est_Previous_Num",
    src_6."EngLang7_Sum_Est_Previous2_Num" AS "EngLang7_Sum_Est_Previous2_Num",
    src_4."EngLang79_Sum_Est_Current_Num" AS "EngLang79_Sum_Est_Current_Num",
    src_5."EngLang79_Sum_Est_Previous_Num" AS "EngLang79_Sum_Est_Previous_Num",
    src_6."EngLang79_Sum_Est_Previous2_Num" AS "EngLang79_Sum_Est_Previous2_Num",
    src_4."EngLang8_Sum_Est_Current_Num" AS "EngLang8_Sum_Est_Current_Num",
    src_5."EngLang8_Sum_Est_Previous_Num" AS "EngLang8_Sum_Est_Previous_Num",
    src_6."EngLang8_Sum_Est_Previous2_Num" AS "EngLang8_Sum_Est_Previous2_Num",
    src_4."EngLang9_Sum_Est_Current_Num" AS "EngLang9_Sum_Est_Current_Num",
    src_5."EngLang9_Sum_Est_Previous_Num" AS "EngLang9_Sum_Est_Previous_Num",
    src_6."EngLang9_Sum_Est_Previous2_Num" AS "EngLang9_Sum_Est_Previous2_Num",
    src_4."EngLit4_Sum_Est_Current_Num" AS "EngLit4_Sum_Est_Current_Num",
    src_5."EngLit4_Sum_Est_Previous_Num" AS "EngLit4_Sum_Est_Previous_Num",
    src_6."EngLit4_Sum_Est_Previous2_Num" AS "EngLit4_Sum_Est_Previous2_Num",
    src_4."EngLit49_Sum_Est_Current_Num" AS "EngLit49_Sum_Est_Current_Num",
    src_5."EngLit49_Sum_Est_Previous_Num" AS "EngLit49_Sum_Est_Previous_Num",
    src_6."EngLit49_Sum_Est_Previous2_Num" AS "EngLit49_Sum_Est_Previous2_Num",
    src_4."EngLit5_Sum_Est_Current_Num" AS "EngLit5_Sum_Est_Current_Num",
    src_5."EngLit5_Sum_Est_Previous_Num" AS "EngLit5_Sum_Est_Previous_Num",
    src_6."EngLit5_Sum_Est_Previous2_Num" AS "EngLit5_Sum_Est_Previous2_Num",
    src_4."EngLit59_Sum_Est_Current_Num" AS "EngLit59_Sum_Est_Current_Num",
    src_5."EngLit59_Sum_Est_Previous_Num" AS "EngLit59_Sum_Est_Previous_Num",
    src_6."EngLit59_Sum_Est_Previous2_Num" AS "EngLit59_Sum_Est_Previous2_Num",
    src_4."EngLit6_Sum_Est_Current_Num" AS "EngLit6_Sum_Est_Current_Num",
    src_5."EngLit6_Sum_Est_Previous_Num" AS "EngLit6_Sum_Est_Previous_Num",
    src_6."EngLit6_Sum_Est_Previous2_Num" AS "EngLit6_Sum_Est_Previous2_Num",
    src_4."EngLit7_Sum_Est_Current_Num" AS "EngLit7_Sum_Est_Current_Num",
    src_5."EngLit7_Sum_Est_Previous_Num" AS "EngLit7_Sum_Est_Previous_Num",
    src_6."EngLit7_Sum_Est_Previous2_Num" AS "EngLit7_Sum_Est_Previous2_Num",
    src_4."EngLit79_Sum_Est_Current_Num" AS "EngLit79_Sum_Est_Current_Num",
    src_5."EngLit79_Sum_Est_Previous_Num" AS "EngLit79_Sum_Est_Previous_Num",
    src_6."EngLit79_Sum_Est_Previous2_Num" AS "EngLit79_Sum_Est_Previous2_Num",
    src_4."EngLit8_Sum_Est_Current_Num" AS "EngLit8_Sum_Est_Current_Num",
    src_5."EngLit8_Sum_Est_Previous_Num" AS "EngLit8_Sum_Est_Previous_Num",
    src_6."EngLit8_Sum_Est_Previous2_Num" AS "EngLit8_Sum_Est_Previous2_Num",
    src_4."EngLit9_Sum_Est_Current_Num" AS "EngLit9_Sum_Est_Current_Num",
    src_5."EngLit9_Sum_Est_Previous_Num" AS "EngLit9_Sum_Est_Previous_Num",
    src_6."EngLit9_Sum_Est_Previous2_Num" AS "EngLit9_Sum_Est_Previous2_Num",
    src_1."EngMaths49_Boy_Est_Current_Num" AS "EngMaths49_Boy_Est_Current_Num",
    src_1."EngMaths49_Boy_Est_Current_Pct" AS "EngMaths49_Boy_Est_Current_Pct",
    src_2."EngMaths49_Boy_Est_Previous_Num" AS "EngMaths49_Boy_Est_Previous_Num",
    src_2."EngMaths49_Boy_Est_Previous_Pct" AS "EngMaths49_Boy_Est_Previous_Pct",
    src_3."EngMaths49_Boy_Est_Previous2_Pct" AS "EngMaths49_Boy_Est_Previous2_Pct",
    src_1."EngMaths49_Dis_Est_Current_Num" AS "EngMaths49_Dis_Est_Current_Num",
    src_1."EngMaths49_Dis_Est_Current_Pct" AS "EngMaths49_Dis_Est_Current_Pct",
    src_2."EngMaths49_Dis_Est_Previous_Num" AS "EngMaths49_Dis_Est_Previous_Num",
    src_2."EngMaths49_Dis_Est_Previous_Pct" AS "EngMaths49_Dis_Est_Previous_Pct",
    src_3."EngMaths49_Dis_Est_Previous2_Pct" AS "EngMaths49_Dis_Est_Previous2_Pct",
    src_1."EngMaths49_EAL_Est_Current_Num" AS "EngMaths49_EAL_Est_Current_Num",
    src_1."EngMaths49_EAL_Est_Current_Pct" AS "EngMaths49_EAL_Est_Current_Pct",
    src_2."EngMaths49_EAL_Est_Previous_Num" AS "EngMaths49_EAL_Est_Previous_Num",
    src_2."EngMaths49_EAL_Est_Previous_Pct" AS "EngMaths49_EAL_Est_Previous_Pct",
    src_3."EngMaths49_EAL_Est_Previous2_Pct" AS "EngMaths49_EAL_Est_Previous2_Pct",
    src_1."EngMaths49_Grl_Est_Current_Num" AS "EngMaths49_Grl_Est_Current_Num",
    src_1."EngMaths49_Grl_Est_Current_Pct" AS "EngMaths49_Grl_Est_Current_Pct",
    src_2."EngMaths49_Grl_Est_Previous_Num" AS "EngMaths49_Grl_Est_Previous_Num",
    src_2."EngMaths49_Grl_Est_Previous_Pct" AS "EngMaths49_Grl_Est_Previous_Pct",
    src_3."EngMaths49_Grl_Est_Previous2_Pct" AS "EngMaths49_Grl_Est_Previous2_Pct",
    src_3."EngMaths49_Mob_Est_Previous2_Pct" AS "EngMaths49_Mob_Est_Previous2_Pct",
    src_1."EngMaths49_NDi_Est_Current_Num" AS "EngMaths49_NDi_Est_Current_Num",
    src_1."EngMaths49_NDi_Est_Current_Pct" AS "EngMaths49_NDi_Est_Current_Pct",
    src_1."EngMaths49_NMo_Est_Current_Num" AS "EngMaths49_NMo_Est_Current_Num",
    src_1."EngMaths49_NMo_Est_Current_Pct" AS "EngMaths49_NMo_Est_Current_Pct",
    src_2."EngMaths49_NMo_Est_Previous_Num" AS "EngMaths49_NMo_Est_Previous_Num",
    src_2."EngMaths49_NMo_Est_Previous_Pct" AS "EngMaths49_NMo_Est_Previous_Pct",
    src_1."EngMaths49_Tot_Est_Current_Num" AS "EngMaths49_Tot_Est_Current_Num",
    src_1."EngMaths49_Tot_Est_Current_Pct" AS "EngMaths49_Tot_Est_Current_Pct",
    src_2."EngMaths49_Tot_Est_Previous_Num" AS "EngMaths49_Tot_Est_Previous_Num",
    src_2."EngMaths49_Tot_Est_Previous_Pct" AS "EngMaths49_Tot_Est_Previous_Pct",
    src_3."EngMaths49_Tot_Est_Previous2_Pct" AS "EngMaths49_Tot_Est_Previous2_Pct",
    src_1."EngMaths59_Boy_Est_Current_Num" AS "EngMaths59_Boy_Est_Current_Num",
    src_1."EngMaths59_Boy_Est_Current_Pct" AS "EngMaths59_Boy_Est_Current_Pct",
    src_2."EngMaths59_Boy_Est_Previous_Num" AS "EngMaths59_Boy_Est_Previous_Num",
    src_2."EngMaths59_Boy_Est_Previous_Pct" AS "EngMaths59_Boy_Est_Previous_Pct",
    src_3."EngMaths59_Boy_Est_Previous2_Pct" AS "EngMaths59_Boy_Est_Previous2_Pct",
    src_1."EngMaths59_Dis_Est_Current_Num" AS "EngMaths59_Dis_Est_Current_Num",
    src_1."EngMaths59_Dis_Est_Current_Pct" AS "EngMaths59_Dis_Est_Current_Pct",
    src_2."EngMaths59_Dis_Est_Previous_Num" AS "EngMaths59_Dis_Est_Previous_Num",
    src_2."EngMaths59_Dis_Est_Previous_Pct" AS "EngMaths59_Dis_Est_Previous_Pct",
    src_3."EngMaths59_Dis_Est_Previous2_Pct" AS "EngMaths59_Dis_Est_Previous2_Pct",
    src_1."EngMaths59_EAL_Est_Current_Num" AS "EngMaths59_EAL_Est_Current_Num",
    src_1."EngMaths59_EAL_Est_Current_Pct" AS "EngMaths59_EAL_Est_Current_Pct",
    src_2."EngMaths59_EAL_Est_Previous_Num" AS "EngMaths59_EAL_Est_Previous_Num",
    src_2."EngMaths59_EAL_Est_Previous_Pct" AS "EngMaths59_EAL_Est_Previous_Pct",
    src_3."EngMaths59_EAL_Est_Previous2_Pct" AS "EngMaths59_EAL_Est_Previous2_Pct",
    src_1."EngMaths59_Grl_Est_Current_Num" AS "EngMaths59_Grl_Est_Current_Num",
    src_1."EngMaths59_Grl_Est_Current_Pct" AS "EngMaths59_Grl_Est_Current_Pct",
    src_2."EngMaths59_Grl_Est_Previous_Num" AS "EngMaths59_Grl_Est_Previous_Num",
    src_2."EngMaths59_Grl_Est_Previous_Pct" AS "EngMaths59_Grl_Est_Previous_Pct",
    src_3."EngMaths59_Grl_Est_Previous2_Pct" AS "EngMaths59_Grl_Est_Previous2_Pct",
    src_3."EngMaths59_Mob_Est_Previous2_Pct" AS "EngMaths59_Mob_Est_Previous2_Pct",
    src_1."EngMaths59_NDi_Est_Current_Num" AS "EngMaths59_NDi_Est_Current_Num",
    src_1."EngMaths59_NDi_Est_Current_Pct" AS "EngMaths59_NDi_Est_Current_Pct",
    src_1."EngMaths59_NMo_Est_Current_Num" AS "EngMaths59_NMo_Est_Current_Num",
    src_1."EngMaths59_NMo_Est_Current_Pct" AS "EngMaths59_NMo_Est_Current_Pct",
    src_2."EngMaths59_NMo_Est_Previous_Num" AS "EngMaths59_NMo_Est_Previous_Num",
    src_2."EngMaths59_NMo_Est_Previous_Pct" AS "EngMaths59_NMo_Est_Previous_Pct",
    src_1."EngMaths59_Tot_Est_Current_Num" AS "EngMaths59_Tot_Est_Current_Num",
    src_1."EngMaths59_Tot_Est_Current_Pct" AS "EngMaths59_Tot_Est_Current_Pct",
    src_2."EngMaths59_Tot_Est_Previous_Num" AS "EngMaths59_Tot_Est_Previous_Num",
    src_2."EngMaths59_Tot_Est_Previous_Pct" AS "EngMaths59_Tot_Est_Previous_Pct",
    src_3."EngMaths59_Tot_Est_Previous2_Pct" AS "EngMaths59_Tot_Est_Previous2_Pct",
    src_4."Maths4_Sum_Est_Current_Num" AS "Maths4_Sum_Est_Current_Num",
    src_5."Maths4_Sum_Est_Previous_Num" AS "Maths4_Sum_Est_Previous_Num",
    src_6."Maths4_Sum_Est_Previous2_Num" AS "Maths4_Sum_Est_Previous2_Num",
    src_4."Maths49_Sum_Est_Current_Num" AS "Maths49_Sum_Est_Current_Num",
    src_5."Maths49_Sum_Est_Previous_Num" AS "Maths49_Sum_Est_Previous_Num",
    src_6."Maths49_Sum_Est_Previous2_Num" AS "Maths49_Sum_Est_Previous2_Num",
    src_4."Maths5_Sum_Est_Current_Num" AS "Maths5_Sum_Est_Current_Num",
    src_5."Maths5_Sum_Est_Previous_Num" AS "Maths5_Sum_Est_Previous_Num",
    src_6."Maths5_Sum_Est_Previous2_Num" AS "Maths5_Sum_Est_Previous2_Num",
    src_4."Maths59_Sum_Est_Current_Num" AS "Maths59_Sum_Est_Current_Num",
    src_5."Maths59_Sum_Est_Previous_Num" AS "Maths59_Sum_Est_Previous_Num",
    src_6."Maths59_Sum_Est_Previous2_Num" AS "Maths59_Sum_Est_Previous2_Num",
    src_4."Maths6_Sum_Est_Current_Num" AS "Maths6_Sum_Est_Current_Num",
    src_5."Maths6_Sum_Est_Previous_Num" AS "Maths6_Sum_Est_Previous_Num",
    src_6."Maths6_Sum_Est_Previous2_Num" AS "Maths6_Sum_Est_Previous2_Num",
    src_4."Maths7_Sum_Est_Current_Num" AS "Maths7_Sum_Est_Current_Num",
    src_5."Maths7_Sum_Est_Previous_Num" AS "Maths7_Sum_Est_Previous_Num",
    src_6."Maths7_Sum_Est_Previous2_Num" AS "Maths7_Sum_Est_Previous2_Num",
    src_4."Maths79_Sum_Est_Current_Num" AS "Maths79_Sum_Est_Current_Num",
    src_5."Maths79_Sum_Est_Previous_Num" AS "Maths79_Sum_Est_Previous_Num",
    src_6."Maths79_Sum_Est_Previous2_Num" AS "Maths79_Sum_Est_Previous2_Num",
    src_4."Maths8_Sum_Est_Current_Num" AS "Maths8_Sum_Est_Current_Num",
    src_5."Maths8_Sum_Est_Previous_Num" AS "Maths8_Sum_Est_Previous_Num",
    src_6."Maths8_Sum_Est_Previous2_Num" AS "Maths8_Sum_Est_Previous2_Num",
    src_4."Maths9_Sum_Est_Current_Num" AS "Maths9_Sum_Est_Current_Num",
    src_5."Maths9_Sum_Est_Previous_Num" AS "Maths9_Sum_Est_Previous_Num",
    src_6."Maths9_Sum_Est_Previous2_Num" AS "Maths9_Sum_Est_Previous2_Num",
    src_4."Physics4_Sum_Est_Current_Num" AS "Physics4_Sum_Est_Current_Num",
    src_5."Physics4_Sum_Est_Previous_Num" AS "Physics4_Sum_Est_Previous_Num",
    src_6."Physics4_Sum_Est_Previous2_Num" AS "Physics4_Sum_Est_Previous2_Num",
    src_4."Physics49_Sum_Est_Current_Num" AS "Physics49_Sum_Est_Current_Num",
    src_5."Physics49_Sum_Est_Previous_Num" AS "Physics49_Sum_Est_Previous_Num",
    src_6."Physics49_Sum_Est_Previous2_Num" AS "Physics49_Sum_Est_Previous2_Num",
    src_4."Physics5_Sum_Est_Current_Num" AS "Physics5_Sum_Est_Current_Num",
    src_5."Physics5_Sum_Est_Previous_Num" AS "Physics5_Sum_Est_Previous_Num",
    src_6."Physics5_Sum_Est_Previous2_Num" AS "Physics5_Sum_Est_Previous2_Num",
    src_4."Physics59_Sum_Est_Current_Num" AS "Physics59_Sum_Est_Current_Num",
    src_5."Physics59_Sum_Est_Previous_Num" AS "Physics59_Sum_Est_Previous_Num",
    src_6."Physics59_Sum_Est_Previous2_Num" AS "Physics59_Sum_Est_Previous2_Num",
    src_4."Physics6_Sum_Est_Current_Num" AS "Physics6_Sum_Est_Current_Num",
    src_5."Physics6_Sum_Est_Previous_Num" AS "Physics6_Sum_Est_Previous_Num",
    src_6."Physics6_Sum_Est_Previous2_Num" AS "Physics6_Sum_Est_Previous2_Num",
    src_4."Physics7_Sum_Est_Current_Num" AS "Physics7_Sum_Est_Current_Num",
    src_5."Physics7_Sum_Est_Previous_Num" AS "Physics7_Sum_Est_Previous_Num",
    src_6."Physics7_Sum_Est_Previous2_Num" AS "Physics7_Sum_Est_Previous2_Num",
    src_4."Physics79_Sum_Est_Current_Num" AS "Physics79_Sum_Est_Current_Num",
    src_5."Physics79_Sum_Est_Previous_Num" AS "Physics79_Sum_Est_Previous_Num",
    src_6."Physics79_Sum_Est_Previous2_Num" AS "Physics79_Sum_Est_Previous2_Num",
    src_4."Physics8_Sum_Est_Current_Num" AS "Physics8_Sum_Est_Current_Num",
    src_5."Physics8_Sum_Est_Previous_Num" AS "Physics8_Sum_Est_Previous_Num",
    src_6."Physics8_Sum_Est_Previous2_Num" AS "Physics8_Sum_Est_Previous2_Num",
    src_4."Physics9_Sum_Est_Current_Num" AS "Physics9_Sum_Est_Current_Num",
    src_5."Physics9_Sum_Est_Previous_Num" AS "Physics9_Sum_Est_Previous_Num",
    src_6."Physics9_Sum_Est_Previous2_Num" AS "Physics9_Sum_Est_Previous2_Num",
    src_2."Prog8_Tot_Est_Previous_Num" AS "Prog8_Tot_Est_Previous_Num",
    src_3."Prog8_Tot_Est_Previous2_Num" AS "Prog8_Tot_Est_Previous2_Num"
FROM all_ids a
LEFT JOIN src_1 ON src_1."Id" = a."Id"
LEFT JOIN src_2 ON src_2."Id" = a."Id"
LEFT JOIN src_3 ON src_3."Id" = a."Id"
LEFT JOIN src_4 ON src_4."Id" = a."Id"
LEFT JOIN src_5 ON src_5."Id" = a."Id"
LEFT JOIN src_6 ON src_6."Id" = a."Id"
LEFT JOIN v_establishment e ON e."URN" = a."Id"
;
