-- AUTO-GENERATED MATERIALIZED VIEW: v_establishment_performance

DROP MATERIALIZED VIEW IF EXISTS v_establishment_performance;

CREATE MATERIALIZED VIEW v_establishment_performance AS
WITH
src_1 AS (
    SELECT
        t."URN" AS "Id",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR_BOYS" END) AS "Attainment8_Boy_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR_FSM6CLA1A" END) AS "Attainment8_Dis_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR_EAL" END) AS "Attainment8_EAL_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR_GIRLS" END) AS "Attainment8_Grl_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR_NFSM6CLA1A" END) AS "Attainment8_NDi_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR_NMOB" END) AS "Attainment8_NMo_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR" END) AS "Attainment8_Tot_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PBL2BASICS_94") END) AS "EngMaths49_Boy_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PBL2BASICS_95") END) AS "EngMaths59_Boy_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTFSM6CLA1ABASICS_94") END) AS "EngMaths49_Dis_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTFSM6CLA1ABASICS_95") END) AS "EngMaths59_Dis_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTL2BASICSEAL_94") END) AS "EngMaths49_EAL_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTL2BASICSEAL_95") END) AS "EngMaths59_EAL_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PGL2BASICS_94") END) AS "EngMaths49_Grl_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PGL2BASICS_95") END) AS "EngMaths59_Grl_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTL2BASICSNMOB_94") END) AS "EngMaths49_Mob_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTL2BASICSNMOB_95") END) AS "EngMaths59_Mob_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTL2BASICS_94") END) AS "EngMaths49_Tot_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTL2BASICS_95") END) AS "EngMaths59_Tot_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."P8MEA" END) AS "Prog8_Tot_Est_Previous2_Num"
    FROM raw_2022_2023_england__28199246 t
    GROUP BY t."URN"
),
src_2 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."avg_att8" END) AS "Attainment8_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."avg_att8" END) AS "Attainment8_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."avg_att8" END) AS "Attainment8_EAL_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."avg_att8" END) AS "Attainment8_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."avg_att8" END) AS "Attainment8_NMo_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."avg_att8" END) AS "Attainment8_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Boy_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Boy_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Dis_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Dis_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_EAL_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_EAL_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_EAL_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_EAL_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Grl_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Grl_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_NMo_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_NMo_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_NMo_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_NMo_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Tot_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Tot_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."t_p8score" END) AS "Prog8_Tot_Est_Previous_Num"
    FROM raw_202324_performance_371eb4e5 t
    GROUP BY t."school_urn"
),
src_3 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_numeric(t."engmath_94_total") END) AS "EngMaths49_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_Boy_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Boy_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_numeric(t."engmath_94_total") END) AS "EngMaths49_Dis_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Dis_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Dis_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_numeric(t."engmath_94_total") END) AS "EngMaths49_EAL_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_EAL_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_EAL_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Dis_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_numeric(t."engmath_94_total") END) AS "EngMaths49_Grl_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Grl_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Grl_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN clean_int(t."engmath_94_total") END) AS "EngMaths49_NDi_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_NDi_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN clean_numeric(t."engmath_95_total") END) AS "EngMaths59_NDi_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_numeric(t."engmath_94_total") END) AS "EngMaths49_NMo_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_NMo_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_NMo_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_int(t."attainment8_average") END) AS "Attainment8_EAL_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_int(t."engmath_94_total") END) AS "EngMaths49_Tot_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_Tot_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Tot_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Tot_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Grl_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN clean_int(t."attainment8_average") END) AS "Attainment8_NDi_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_int(t."attainment8_average") END) AS "Attainment8_NMo_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Tot_Est_Current_Num"
    FROM raw_202425_performance_3979aec1 t
    GROUP BY t."school_urn"
)

SELECT
    COALESCE(src_1."Id", src_2."Id", src_3."Id") AS "Id",
    src_3."Attainment8_Boy_Est_Current_Num" AS "Attainment8_Boy_Est_Current_Num",
    src_2."Attainment8_Boy_Est_Previous_Num" AS "Attainment8_Boy_Est_Previous_Num",
    src_1."Attainment8_Boy_Est_Previous2_Num" AS "Attainment8_Boy_Est_Previous2_Num",
    src_3."Attainment8_Dis_Est_Current_Num" AS "Attainment8_Dis_Est_Current_Num",
    src_2."Attainment8_Dis_Est_Previous_Num" AS "Attainment8_Dis_Est_Previous_Num",
    src_1."Attainment8_Dis_Est_Previous2_Num" AS "Attainment8_Dis_Est_Previous2_Num",
    src_3."Attainment8_EAL_Est_Current_Num" AS "Attainment8_EAL_Est_Current_Num",
    src_2."Attainment8_EAL_Est_Previous_Num" AS "Attainment8_EAL_Est_Previous_Num",
    src_1."Attainment8_EAL_Est_Previous2_Num" AS "Attainment8_EAL_Est_Previous2_Num",
    src_3."Attainment8_Grl_Est_Current_Num" AS "Attainment8_Grl_Est_Current_Num",
    src_2."Attainment8_Grl_Est_Previous_Num" AS "Attainment8_Grl_Est_Previous_Num",
    src_1."Attainment8_Grl_Est_Previous2_Num" AS "Attainment8_Grl_Est_Previous2_Num",
    src_3."Attainment8_NDi_Est_Current_Num" AS "Attainment8_NDi_Est_Current_Num",
    src_1."Attainment8_NDi_Est_Previous2_Num" AS "Attainment8_NDi_Est_Previous2_Num",
    src_3."Attainment8_NMo_Est_Current_Num" AS "Attainment8_NMo_Est_Current_Num",
    src_2."Attainment8_NMo_Est_Previous_Num" AS "Attainment8_NMo_Est_Previous_Num",
    src_1."Attainment8_NMo_Est_Previous2_Num" AS "Attainment8_NMo_Est_Previous2_Num",
    src_3."Attainment8_Tot_Est_Current_Num" AS "Attainment8_Tot_Est_Current_Num",
    src_2."Attainment8_Tot_Est_Previous_Num" AS "Attainment8_Tot_Est_Previous_Num",
    src_1."Attainment8_Tot_Est_Previous2_Num" AS "Attainment8_Tot_Est_Previous2_Num",
    src_3."EngMaths49_Boy_Est_Current_Num" AS "EngMaths49_Boy_Est_Current_Num",
    src_3."EngMaths49_Boy_Est_Current_Pct" AS "EngMaths49_Boy_Est_Current_Pct",
    src_2."EngMaths49_Boy_Est_Previous_Num" AS "EngMaths49_Boy_Est_Previous_Num",
    src_2."EngMaths49_Boy_Est_Previous_Pct" AS "EngMaths49_Boy_Est_Previous_Pct",
    src_1."EngMaths49_Boy_Est_Previous2_Pct" AS "EngMaths49_Boy_Est_Previous2_Pct",
    src_3."EngMaths49_Dis_Est_Current_Pct" AS "EngMaths49_Dis_Est_Current_Pct",
    src_2."EngMaths49_Dis_Est_Previous_Num" AS "EngMaths49_Dis_Est_Previous_Num",
    src_2."EngMaths49_Dis_Est_Previous_Pct" AS "EngMaths49_Dis_Est_Previous_Pct",
    src_1."EngMaths49_Dis_Est_Previous2_Pct" AS "EngMaths49_Dis_Est_Previous2_Pct",
    src_3."EngMaths49_EAL_Est_Current_Pct" AS "EngMaths49_EAL_Est_Current_Pct",
    src_2."EngMaths49_EAL_Est_Previous_Num" AS "EngMaths49_EAL_Est_Previous_Num",
    src_2."EngMaths49_EAL_Est_Previous_Pct" AS "EngMaths49_EAL_Est_Previous_Pct",
    src_1."EngMaths49_EAL_Est_Previous2_Pct" AS "EngMaths49_EAL_Est_Previous2_Pct",
    src_3."EngMaths49_Grl_Est_Current_Pct" AS "EngMaths49_Grl_Est_Current_Pct",
    src_2."EngMaths49_Grl_Est_Previous_Num" AS "EngMaths49_Grl_Est_Previous_Num",
    src_2."EngMaths49_Grl_Est_Previous_Pct" AS "EngMaths49_Grl_Est_Previous_Pct",
    src_1."EngMaths49_Grl_Est_Previous2_Pct" AS "EngMaths49_Grl_Est_Previous2_Pct",
    src_1."EngMaths49_Mob_Est_Previous2_Pct" AS "EngMaths49_Mob_Est_Previous2_Pct",
    src_3."EngMaths49_NDi_Est_Current_Num" AS "EngMaths49_NDi_Est_Current_Num",
    src_3."EngMaths49_NDi_Est_Current_Pct" AS "EngMaths49_NDi_Est_Current_Pct",
    src_3."EngMaths49_NMo_Est_Current_Pct" AS "EngMaths49_NMo_Est_Current_Pct",
    src_2."EngMaths49_NMo_Est_Previous_Num" AS "EngMaths49_NMo_Est_Previous_Num",
    src_2."EngMaths49_NMo_Est_Previous_Pct" AS "EngMaths49_NMo_Est_Previous_Pct",
    src_3."EngMaths49_Tot_Est_Current_Num" AS "EngMaths49_Tot_Est_Current_Num",
    src_3."EngMaths49_Tot_Est_Current_Pct" AS "EngMaths49_Tot_Est_Current_Pct",
    src_2."EngMaths49_Tot_Est_Previous_Num" AS "EngMaths49_Tot_Est_Previous_Num",
    src_2."EngMaths49_Tot_Est_Previous_Pct" AS "EngMaths49_Tot_Est_Previous_Pct",
    src_1."EngMaths49_Tot_Est_Previous2_Pct" AS "EngMaths49_Tot_Est_Previous2_Pct",
    src_3."EngMaths59_Boy_Est_Current_Num" AS "EngMaths59_Boy_Est_Current_Num",
    src_3."EngMaths59_Boy_Est_Current_Pct" AS "EngMaths59_Boy_Est_Current_Pct",
    src_2."EngMaths59_Boy_Est_Previous_Num" AS "EngMaths59_Boy_Est_Previous_Num",
    src_2."EngMaths59_Boy_Est_Previous_Pct" AS "EngMaths59_Boy_Est_Previous_Pct",
    src_1."EngMaths59_Boy_Est_Previous2_Pct" AS "EngMaths59_Boy_Est_Previous2_Pct",
    src_3."EngMaths59_Dis_Est_Current_Num" AS "EngMaths59_Dis_Est_Current_Num",
    src_3."EngMaths59_Dis_Est_Current_Pct" AS "EngMaths59_Dis_Est_Current_Pct",
    src_2."EngMaths59_Dis_Est_Previous_Num" AS "EngMaths59_Dis_Est_Previous_Num",
    src_2."EngMaths59_Dis_Est_Previous_Pct" AS "EngMaths59_Dis_Est_Previous_Pct",
    src_1."EngMaths59_Dis_Est_Previous2_Pct" AS "EngMaths59_Dis_Est_Previous2_Pct",
    src_3."EngMaths59_EAL_Est_Current_Num" AS "EngMaths59_EAL_Est_Current_Num",
    src_3."EngMaths59_EAL_Est_Current_Pct" AS "EngMaths59_EAL_Est_Current_Pct",
    src_2."EngMaths59_EAL_Est_Previous_Num" AS "EngMaths59_EAL_Est_Previous_Num",
    src_2."EngMaths59_EAL_Est_Previous_Pct" AS "EngMaths59_EAL_Est_Previous_Pct",
    src_1."EngMaths59_EAL_Est_Previous2_Pct" AS "EngMaths59_EAL_Est_Previous2_Pct",
    src_3."EngMaths59_Grl_Est_Current_Num" AS "EngMaths59_Grl_Est_Current_Num",
    src_3."EngMaths59_Grl_Est_Current_Pct" AS "EngMaths59_Grl_Est_Current_Pct",
    src_2."EngMaths59_Grl_Est_Previous_Num" AS "EngMaths59_Grl_Est_Previous_Num",
    src_2."EngMaths59_Grl_Est_Previous_Pct" AS "EngMaths59_Grl_Est_Previous_Pct",
    src_1."EngMaths59_Grl_Est_Previous2_Pct" AS "EngMaths59_Grl_Est_Previous2_Pct",
    src_1."EngMaths59_Mob_Est_Previous2_Pct" AS "EngMaths59_Mob_Est_Previous2_Pct",
    src_3."EngMaths59_NDi_Est_Current_Pct" AS "EngMaths59_NDi_Est_Current_Pct",
    src_3."EngMaths59_NMo_Est_Current_Num" AS "EngMaths59_NMo_Est_Current_Num",
    src_3."EngMaths59_NMo_Est_Current_Pct" AS "EngMaths59_NMo_Est_Current_Pct",
    src_2."EngMaths59_NMo_Est_Previous_Num" AS "EngMaths59_NMo_Est_Previous_Num",
    src_2."EngMaths59_NMo_Est_Previous_Pct" AS "EngMaths59_NMo_Est_Previous_Pct",
    src_3."EngMaths59_Tot_Est_Current_Num" AS "EngMaths59_Tot_Est_Current_Num",
    src_3."EngMaths59_Tot_Est_Current_Pct" AS "EngMaths59_Tot_Est_Current_Pct",
    src_2."EngMaths59_Tot_Est_Previous_Num" AS "EngMaths59_Tot_Est_Previous_Num",
    src_2."EngMaths59_Tot_Est_Previous_Pct" AS "EngMaths59_Tot_Est_Previous_Pct",
    src_1."EngMaths59_Tot_Est_Previous2_Pct" AS "EngMaths59_Tot_Est_Previous2_Pct",
    src_2."Prog8_Tot_Est_Previous_Num" AS "Prog8_Tot_Est_Previous_Num",
    src_1."Prog8_Tot_Est_Previous2_Num" AS "Prog8_Tot_Est_Previous2_Num"
FROM src_1
LEFT JOIN src_2 ON src_2."Id" = src_1."Id"
LEFT JOIN src_3 ON src_3."Id" = src_1."Id"
;
