-- AUTO-GENERATED MATERIALIZED VIEW: v_establishment_destinations

DROP MATERIALIZED VIEW IF EXISTS v_establishment_destinations;

CREATE MATERIALIZED VIEW v_establishment_destinations AS
WITH
src_1 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of Students' THEN t."overall"::text END) AS "AllDest_Boy_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_Boy_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of Students' THEN t."overall"::text END) AS "AllDest_Dis_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_Dis_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of Students' THEN t."overall"::text END) AS "AllDest_Grl_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_Grl_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of Students' THEN t."overall"::text END) AS "AllDest_NDi_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_NDi_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of Students' THEN t."overall"::text END) AS "AllDest_Tot_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of Students' THEN t."education"::text END) AS "Education_Boy_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_Boy_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of Students' THEN t."education"::text END) AS "Education_Dis_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_Dis_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of Students' THEN t."education"::text END) AS "Education_Grl_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_Grl_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of Students' THEN t."education"::text END) AS "Education_NDi_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_NDi_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of Students' THEN t."education"::text END) AS "Education_Tot_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of Students' THEN t."all_work"::text END) AS "Employment_Boy_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_Boy_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of Students' THEN t."all_work"::text END) AS "Employment_Dis_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_Dis_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of Students' THEN t."all_work"::text END) AS "Employment_Grl_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_Grl_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of Students' THEN t."all_work"::text END) AS "Employment_NDi_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_NDi_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of Students' THEN t."all_work"::text END) AS "Employment_Tot_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of Students' THEN t."appren"::text END) AS "Apprentice_Boy_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_Boy_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of Students' THEN t."appren"::text END) AS "Apprentice_Dis_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_Dis_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of Students' THEN t."appren"::text END) AS "Apprentice_Grl_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_Grl_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of Students' THEN t."appren"::text END) AS "Apprentice_NDi_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_NDi_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of Students' THEN t."appren"::text END) AS "Apprentice_Tot_Est_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_Tot_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_Tot_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_Tot_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_Tot_Est_Current_Pct_Coded"
    FROM t_ees_ks4_inst_202223_cbe11c2768 t
    GROUP BY t."school_urn"
)
,
src_2 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN t."overall"::text END) AS "AllDest_Boy_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_Boy_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."overall"::text END) AS "AllDest_Dis_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_Dis_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN t."overall"::text END) AS "AllDest_Grl_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_Grl_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."overall"::text END) AS "AllDest_NDi_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_NDi_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN t."overall"::text END) AS "AllDest_Tot_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN t."education"::text END) AS "Education_Boy_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_Boy_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."education"::text END) AS "Education_Dis_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_Dis_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN t."education"::text END) AS "Education_Grl_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_Grl_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."education"::text END) AS "Education_NDi_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_NDi_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN t."education"::text END) AS "Education_Tot_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN t."all_work"::text END) AS "Employment_Boy_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_Boy_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."all_work"::text END) AS "Employment_Dis_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_Dis_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN t."all_work"::text END) AS "Employment_Grl_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_Grl_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."all_work"::text END) AS "Employment_NDi_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_NDi_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN t."all_work"::text END) AS "Employment_Tot_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN t."appren"::text END) AS "Apprentice_Boy_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_Boy_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."appren"::text END) AS "Apprentice_Dis_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_Dis_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN t."appren"::text END) AS "Apprentice_Grl_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_Grl_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."appren"::text END) AS "Apprentice_NDi_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_NDi_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN t."appren"::text END) AS "Apprentice_Tot_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_Tot_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_Tot_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_Tot_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_Tot_Est_Previous_Pct_Coded"
    FROM t_ks4_dm_ud_202223_ins_49ea482af3 t
    GROUP BY t."school_urn"
)
,
src_3 AS (
    SELECT
        e."URN" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN t."overall"::text END) AS "AllDest_Boy_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_Boy_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."overall"::text END) AS "AllDest_Dis_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_Dis_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN t."overall"::text END) AS "AllDest_Grl_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_Grl_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."overall"::text END) AS "AllDest_NDi_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_NDi_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN t."overall"::text END) AS "AllDest_Tot_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN t."education"::text END) AS "Education_Boy_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_Boy_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."education"::text END) AS "Education_Dis_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_Dis_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN t."education"::text END) AS "Education_Grl_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_Grl_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."education"::text END) AS "Education_NDi_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_NDi_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN t."education"::text END) AS "Education_Tot_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN t."all_work"::text END) AS "Employment_Boy_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_Boy_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."all_work"::text END) AS "Employment_Dis_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_Dis_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN t."all_work"::text END) AS "Employment_Grl_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_Grl_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."all_work"::text END) AS "Employment_NDi_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_NDi_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN t."all_work"::text END) AS "Employment_Tot_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN t."appren"::text END) AS "Apprentice_Boy_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_Boy_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."appren"::text END) AS "Apprentice_Dis_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_Dis_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN t."appren"::text END) AS "Apprentice_Grl_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_Grl_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN t."appren"::text END) AS "Apprentice_NDi_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_NDi_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN t."appren"::text END) AS "Apprentice_Tot_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN t."overall"::text END) AS "AllDest_Tot_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN t."education"::text END) AS "Education_Tot_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN t."all_work"::text END) AS "Employment_Tot_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN t."appren"::text END) AS "Apprentice_Tot_Est_Previous2_Pct_Coded"
    FROM t_ks4_dm_ud_202122_ins_d3152640f4 t
    JOIN v_establishment e ON (e."LAId"::text || LPAD(e."EstablishmentNumber"::text, 4, '0')) = t."school_laestab"
    GROUP BY e."URN"
)
,
all_ids AS (
    SELECT "Id" FROM src_1
    UNION SELECT "Id" FROM src_2
    UNION SELECT "Id" FROM src_3
)

SELECT
    a."Id" AS "Id",
    e."LAId" AS "LAId",
    e."LAName" AS "LAName",
    e."RegionId" AS "RegionId",
    e."RegionName" AS "RegionName",
    src_1."AllDest_Boy_Est_Current_Num_Coded" AS "AllDest_Boy_Est_Current_Num_Coded",
    src_1."AllDest_Boy_Est_Current_Pct_Coded" AS "AllDest_Boy_Est_Current_Pct_Coded",
    src_2."AllDest_Boy_Est_Previous_Num_Coded" AS "AllDest_Boy_Est_Previous_Num_Coded",
    src_2."AllDest_Boy_Est_Previous_Pct_Coded" AS "AllDest_Boy_Est_Previous_Pct_Coded",
    src_3."AllDest_Boy_Est_Previous2_Num_Coded" AS "AllDest_Boy_Est_Previous2_Num_Coded",
    src_3."AllDest_Boy_Est_Previous2_Pct_Coded" AS "AllDest_Boy_Est_Previous2_Pct_Coded",
    src_1."AllDest_Dis_Est_Current_Num_Coded" AS "AllDest_Dis_Est_Current_Num_Coded",
    src_1."AllDest_Dis_Est_Current_Pct_Coded" AS "AllDest_Dis_Est_Current_Pct_Coded",
    src_2."AllDest_Dis_Est_Previous_Num_Coded" AS "AllDest_Dis_Est_Previous_Num_Coded",
    src_2."AllDest_Dis_Est_Previous_Pct_Coded" AS "AllDest_Dis_Est_Previous_Pct_Coded",
    src_3."AllDest_Dis_Est_Previous2_Num_Coded" AS "AllDest_Dis_Est_Previous2_Num_Coded",
    src_3."AllDest_Dis_Est_Previous2_Pct_Coded" AS "AllDest_Dis_Est_Previous2_Pct_Coded",
    src_1."AllDest_Grl_Est_Current_Num_Coded" AS "AllDest_Grl_Est_Current_Num_Coded",
    src_1."AllDest_Grl_Est_Current_Pct_Coded" AS "AllDest_Grl_Est_Current_Pct_Coded",
    src_2."AllDest_Grl_Est_Previous_Num_Coded" AS "AllDest_Grl_Est_Previous_Num_Coded",
    src_2."AllDest_Grl_Est_Previous_Pct_Coded" AS "AllDest_Grl_Est_Previous_Pct_Coded",
    src_3."AllDest_Grl_Est_Previous2_Num_Coded" AS "AllDest_Grl_Est_Previous2_Num_Coded",
    src_3."AllDest_Grl_Est_Previous2_Pct_Coded" AS "AllDest_Grl_Est_Previous2_Pct_Coded",
    src_1."AllDest_NDi_Est_Current_Num_Coded" AS "AllDest_NDi_Est_Current_Num_Coded",
    src_1."AllDest_NDi_Est_Current_Pct_Coded" AS "AllDest_NDi_Est_Current_Pct_Coded",
    src_2."AllDest_NDi_Est_Previous_Num_Coded" AS "AllDest_NDi_Est_Previous_Num_Coded",
    src_2."AllDest_NDi_Est_Previous_Pct_Coded" AS "AllDest_NDi_Est_Previous_Pct_Coded",
    src_3."AllDest_NDi_Est_Previous2_Num_Coded" AS "AllDest_NDi_Est_Previous2_Num_Coded",
    src_3."AllDest_NDi_Est_Previous2_Pct_Coded" AS "AllDest_NDi_Est_Previous2_Pct_Coded",
    src_1."AllDest_Tot_Est_Current_Num_Coded" AS "AllDest_Tot_Est_Current_Num_Coded",
    src_1."AllDest_Tot_Est_Current_Pct_Coded" AS "AllDest_Tot_Est_Current_Pct_Coded",
    src_2."AllDest_Tot_Est_Previous_Num_Coded" AS "AllDest_Tot_Est_Previous_Num_Coded",
    src_2."AllDest_Tot_Est_Previous_Pct_Coded" AS "AllDest_Tot_Est_Previous_Pct_Coded",
    src_3."AllDest_Tot_Est_Previous2_Num_Coded" AS "AllDest_Tot_Est_Previous2_Num_Coded",
    src_3."AllDest_Tot_Est_Previous2_Pct_Coded" AS "AllDest_Tot_Est_Previous2_Pct_Coded",
    src_1."Apprentice_Boy_Est_Current_Num_Coded" AS "Apprentice_Boy_Est_Current_Num_Coded",
    src_1."Apprentice_Boy_Est_Current_Pct_Coded" AS "Apprentice_Boy_Est_Current_Pct_Coded",
    src_2."Apprentice_Boy_Est_Previous_Num_Coded" AS "Apprentice_Boy_Est_Previous_Num_Coded",
    src_2."Apprentice_Boy_Est_Previous_Pct_Coded" AS "Apprentice_Boy_Est_Previous_Pct_Coded",
    src_3."Apprentice_Boy_Est_Previous2_Num_Coded" AS "Apprentice_Boy_Est_Previous2_Num_Coded",
    src_3."Apprentice_Boy_Est_Previous2_Pct_Coded" AS "Apprentice_Boy_Est_Previous2_Pct_Coded",
    src_1."Apprentice_Dis_Est_Current_Num_Coded" AS "Apprentice_Dis_Est_Current_Num_Coded",
    src_1."Apprentice_Dis_Est_Current_Pct_Coded" AS "Apprentice_Dis_Est_Current_Pct_Coded",
    src_2."Apprentice_Dis_Est_Previous_Num_Coded" AS "Apprentice_Dis_Est_Previous_Num_Coded",
    src_2."Apprentice_Dis_Est_Previous_Pct_Coded" AS "Apprentice_Dis_Est_Previous_Pct_Coded",
    src_3."Apprentice_Dis_Est_Previous2_Num_Coded" AS "Apprentice_Dis_Est_Previous2_Num_Coded",
    src_3."Apprentice_Dis_Est_Previous2_Pct_Coded" AS "Apprentice_Dis_Est_Previous2_Pct_Coded",
    src_1."Apprentice_Grl_Est_Current_Num_Coded" AS "Apprentice_Grl_Est_Current_Num_Coded",
    src_1."Apprentice_Grl_Est_Current_Pct_Coded" AS "Apprentice_Grl_Est_Current_Pct_Coded",
    src_2."Apprentice_Grl_Est_Previous_Num_Coded" AS "Apprentice_Grl_Est_Previous_Num_Coded",
    src_2."Apprentice_Grl_Est_Previous_Pct_Coded" AS "Apprentice_Grl_Est_Previous_Pct_Coded",
    src_3."Apprentice_Grl_Est_Previous2_Num_Coded" AS "Apprentice_Grl_Est_Previous2_Num_Coded",
    src_3."Apprentice_Grl_Est_Previous2_Pct_Coded" AS "Apprentice_Grl_Est_Previous2_Pct_Coded",
    src_1."Apprentice_NDi_Est_Current_Num_Coded" AS "Apprentice_NDi_Est_Current_Num_Coded",
    src_1."Apprentice_NDi_Est_Current_Pct_Coded" AS "Apprentice_NDi_Est_Current_Pct_Coded",
    src_2."Apprentice_NDi_Est_Previous_Num_Coded" AS "Apprentice_NDi_Est_Previous_Num_Coded",
    src_2."Apprentice_NDi_Est_Previous_Pct_Coded" AS "Apprentice_NDi_Est_Previous_Pct_Coded",
    src_3."Apprentice_NDi_Est_Previous2_Num_Coded" AS "Apprentice_NDi_Est_Previous2_Num_Coded",
    src_3."Apprentice_NDi_Est_Previous2_Pct_Coded" AS "Apprentice_NDi_Est_Previous2_Pct_Coded",
    src_1."Apprentice_Tot_Est_Current_Num_Coded" AS "Apprentice_Tot_Est_Current_Num_Coded",
    src_1."Apprentice_Tot_Est_Current_Pct_Coded" AS "Apprentice_Tot_Est_Current_Pct_Coded",
    src_2."Apprentice_Tot_Est_Previous_Num_Coded" AS "Apprentice_Tot_Est_Previous_Num_Coded",
    src_2."Apprentice_Tot_Est_Previous_Pct_Coded" AS "Apprentice_Tot_Est_Previous_Pct_Coded",
    src_3."Apprentice_Tot_Est_Previous2_Num_Coded" AS "Apprentice_Tot_Est_Previous2_Num_Coded",
    src_3."Apprentice_Tot_Est_Previous2_Pct_Coded" AS "Apprentice_Tot_Est_Previous2_Pct_Coded",
    src_1."Education_Boy_Est_Current_Num_Coded" AS "Education_Boy_Est_Current_Num_Coded",
    src_1."Education_Boy_Est_Current_Pct_Coded" AS "Education_Boy_Est_Current_Pct_Coded",
    src_2."Education_Boy_Est_Previous_Num_Coded" AS "Education_Boy_Est_Previous_Num_Coded",
    src_2."Education_Boy_Est_Previous_Pct_Coded" AS "Education_Boy_Est_Previous_Pct_Coded",
    src_3."Education_Boy_Est_Previous2_Num_Coded" AS "Education_Boy_Est_Previous2_Num_Coded",
    src_3."Education_Boy_Est_Previous2_Pct_Coded" AS "Education_Boy_Est_Previous2_Pct_Coded",
    src_1."Education_Dis_Est_Current_Num_Coded" AS "Education_Dis_Est_Current_Num_Coded",
    src_1."Education_Dis_Est_Current_Pct_Coded" AS "Education_Dis_Est_Current_Pct_Coded",
    src_2."Education_Dis_Est_Previous_Num_Coded" AS "Education_Dis_Est_Previous_Num_Coded",
    src_2."Education_Dis_Est_Previous_Pct_Coded" AS "Education_Dis_Est_Previous_Pct_Coded",
    src_3."Education_Dis_Est_Previous2_Num_Coded" AS "Education_Dis_Est_Previous2_Num_Coded",
    src_3."Education_Dis_Est_Previous2_Pct_Coded" AS "Education_Dis_Est_Previous2_Pct_Coded",
    src_1."Education_Grl_Est_Current_Num_Coded" AS "Education_Grl_Est_Current_Num_Coded",
    src_1."Education_Grl_Est_Current_Pct_Coded" AS "Education_Grl_Est_Current_Pct_Coded",
    src_2."Education_Grl_Est_Previous_Num_Coded" AS "Education_Grl_Est_Previous_Num_Coded",
    src_2."Education_Grl_Est_Previous_Pct_Coded" AS "Education_Grl_Est_Previous_Pct_Coded",
    src_3."Education_Grl_Est_Previous2_Num_Coded" AS "Education_Grl_Est_Previous2_Num_Coded",
    src_3."Education_Grl_Est_Previous2_Pct_Coded" AS "Education_Grl_Est_Previous2_Pct_Coded",
    src_1."Education_NDi_Est_Current_Num_Coded" AS "Education_NDi_Est_Current_Num_Coded",
    src_1."Education_NDi_Est_Current_Pct_Coded" AS "Education_NDi_Est_Current_Pct_Coded",
    src_2."Education_NDi_Est_Previous_Num_Coded" AS "Education_NDi_Est_Previous_Num_Coded",
    src_2."Education_NDi_Est_Previous_Pct_Coded" AS "Education_NDi_Est_Previous_Pct_Coded",
    src_3."Education_NDi_Est_Previous2_Num_Coded" AS "Education_NDi_Est_Previous2_Num_Coded",
    src_3."Education_NDi_Est_Previous2_Pct_Coded" AS "Education_NDi_Est_Previous2_Pct_Coded",
    src_1."Education_Tot_Est_Current_Num_Coded" AS "Education_Tot_Est_Current_Num_Coded",
    src_1."Education_Tot_Est_Current_Pct_Coded" AS "Education_Tot_Est_Current_Pct_Coded",
    src_2."Education_Tot_Est_Previous_Num_Coded" AS "Education_Tot_Est_Previous_Num_Coded",
    src_2."Education_Tot_Est_Previous_Pct_Coded" AS "Education_Tot_Est_Previous_Pct_Coded",
    src_3."Education_Tot_Est_Previous2_Num_Coded" AS "Education_Tot_Est_Previous2_Num_Coded",
    src_3."Education_Tot_Est_Previous2_Pct_Coded" AS "Education_Tot_Est_Previous2_Pct_Coded",
    src_1."Employment_Boy_Est_Current_Num_Coded" AS "Employment_Boy_Est_Current_Num_Coded",
    src_1."Employment_Boy_Est_Current_Pct_Coded" AS "Employment_Boy_Est_Current_Pct_Coded",
    src_2."Employment_Boy_Est_Previous_Num_Coded" AS "Employment_Boy_Est_Previous_Num_Coded",
    src_2."Employment_Boy_Est_Previous_Pct_Coded" AS "Employment_Boy_Est_Previous_Pct_Coded",
    src_3."Employment_Boy_Est_Previous2_Num_Coded" AS "Employment_Boy_Est_Previous2_Num_Coded",
    src_3."Employment_Boy_Est_Previous2_Pct_Coded" AS "Employment_Boy_Est_Previous2_Pct_Coded",
    src_1."Employment_Dis_Est_Current_Num_Coded" AS "Employment_Dis_Est_Current_Num_Coded",
    src_1."Employment_Dis_Est_Current_Pct_Coded" AS "Employment_Dis_Est_Current_Pct_Coded",
    src_2."Employment_Dis_Est_Previous_Num_Coded" AS "Employment_Dis_Est_Previous_Num_Coded",
    src_2."Employment_Dis_Est_Previous_Pct_Coded" AS "Employment_Dis_Est_Previous_Pct_Coded",
    src_3."Employment_Dis_Est_Previous2_Num_Coded" AS "Employment_Dis_Est_Previous2_Num_Coded",
    src_3."Employment_Dis_Est_Previous2_Pct_Coded" AS "Employment_Dis_Est_Previous2_Pct_Coded",
    src_1."Employment_Grl_Est_Current_Num_Coded" AS "Employment_Grl_Est_Current_Num_Coded",
    src_1."Employment_Grl_Est_Current_Pct_Coded" AS "Employment_Grl_Est_Current_Pct_Coded",
    src_2."Employment_Grl_Est_Previous_Num_Coded" AS "Employment_Grl_Est_Previous_Num_Coded",
    src_2."Employment_Grl_Est_Previous_Pct_Coded" AS "Employment_Grl_Est_Previous_Pct_Coded",
    src_3."Employment_Grl_Est_Previous2_Num_Coded" AS "Employment_Grl_Est_Previous2_Num_Coded",
    src_3."Employment_Grl_Est_Previous2_Pct_Coded" AS "Employment_Grl_Est_Previous2_Pct_Coded",
    src_1."Employment_NDi_Est_Current_Num_Coded" AS "Employment_NDi_Est_Current_Num_Coded",
    src_1."Employment_NDi_Est_Current_Pct_Coded" AS "Employment_NDi_Est_Current_Pct_Coded",
    src_2."Employment_NDi_Est_Previous_Num_Coded" AS "Employment_NDi_Est_Previous_Num_Coded",
    src_2."Employment_NDi_Est_Previous_Pct_Coded" AS "Employment_NDi_Est_Previous_Pct_Coded",
    src_3."Employment_NDi_Est_Previous2_Num_Coded" AS "Employment_NDi_Est_Previous2_Num_Coded",
    src_3."Employment_NDi_Est_Previous2_Pct_Coded" AS "Employment_NDi_Est_Previous2_Pct_Coded",
    src_1."Employment_Tot_Est_Current_Num_Coded" AS "Employment_Tot_Est_Current_Num_Coded",
    src_1."Employment_Tot_Est_Current_Pct_Coded" AS "Employment_Tot_Est_Current_Pct_Coded",
    src_2."Employment_Tot_Est_Previous_Num_Coded" AS "Employment_Tot_Est_Previous_Num_Coded",
    src_2."Employment_Tot_Est_Previous_Pct_Coded" AS "Employment_Tot_Est_Previous_Pct_Coded",
    src_3."Employment_Tot_Est_Previous2_Num_Coded" AS "Employment_Tot_Est_Previous2_Num_Coded",
    src_3."Employment_Tot_Est_Previous2_Pct_Coded" AS "Employment_Tot_Est_Previous2_Pct_Coded"
FROM all_ids a
LEFT JOIN src_1 ON src_1."Id" = a."Id"
LEFT JOIN src_2 ON src_2."Id" = a."Id"
LEFT JOIN src_3 ON src_3."Id" = a."Id"
LEFT JOIN v_establishment e ON e."URN" = a."Id"
;
