-- AUTO-GENERATED MATERIALIZED VIEW: v_england_performance

DROP MATERIALIZED VIEW IF EXISTS v_england_performance;

CREATE MATERIALIZED VIEW v_england_performance AS
WITH
src_1 AS (
    SELECT
        t."geographic_level" AS "Id",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_Tot_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."breakdown" = 'Boys' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_Boy_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'First language' AND t."breakdown" = 'Known or believed to be other than English' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_EAL_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_Dis_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Disadvantaged' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_Dis_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Disadvantaged' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_Dis_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."breakdown" = 'Girls' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_Grl_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_NDi_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_NDi_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_NDi_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Mobility' AND t."breakdown" = 'Non mobile' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_NMo_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_Tot_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8_average"::text END) AS "Attainment8_Tot_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8ebacc_average"::text END) AS "Attainment8_Ebc_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8eng_average"::text END) AS "Attainment8_Eng_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8eng_average"::text END) AS "Attainment8_EngDis_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8eng_average"::text END) AS "Attainment8_EngNDi_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8mat_average"::text END) AS "Attainment8_Mat_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8mat_average"::text END) AS "Attainment8_MatDis_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8mat_average"::text END) AS "Attainment8_MatNDi_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8open_average"::text END) AS "Attainment8_AnQ_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8open_average"::text END) AS "Attainment8_AnQNDis_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8open_gcse_average"::text END) AS "Attainment8_Acad_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8open_gcse_average"::text END) AS "Attainment8_AcadDis_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8open_gcse_average"::text END) AS "Attainment8_AcadNDi_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8open_nongcse_average"::text END) AS "Attainment8_Voc_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8open_nongcse_average"::text END) AS "Attainment8_VocDis_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."attainment8open_nongcse_average"::text END) AS "Attainment8_VocNDi_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."breakdown" = 'Boys' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."pupil_count"::text END) AS "Pup_Boy_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."breakdown" = 'Girls' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."pupil_count"::text END) AS "Pup_Grl_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."progress8_lower_95_ci"::text END) AS "Prog8_CI_Lower_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."progress8_upper_95_ci"::text END) AS "Prog8_CI_Upper_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."progress8_average"::text END) AS "Prog8_Tot_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."progress8_average"::text END) AS "Prog8_Tot_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."progress8_average"::text END) AS "Prog8_Tot_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."progress8_pupil_count"::text END) AS "Prog8_TotPup_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."progress8_pupil_count"::text END) AS "Prog8_TotPup_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."progress8_pupil_count"::text END) AS "Prog8_TotPup_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."breakdown" = 'Boys' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_94_percent"::text END) AS "EngMaths49_Boy_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."breakdown" = 'Boys' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_95_percent"::text END) AS "EngMaths59_Boy_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."breakdown" = 'Girls' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_94_percent"::text END) AS "EngMaths49_Grl_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."breakdown" = 'Girls' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_95_percent"::text END) AS "EngMaths59_Grl_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."gcse_91_percent"::text END) AS "AnyQual_Tot_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_94_percent"::text END) AS "EngMaths49_Dis_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_95_percent"::text END) AS "EngMaths59_Dis_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_94_percent"::text END) AS "EngMaths49_Tot_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_94_percent"::text END) AS "EngMaths49_Tot_Eng_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_94_percent"::text END) AS "EngMaths49_Tot_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_95_percent"::text END) AS "EngMaths59_Tot_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_95_percent"::text END) AS "EngMaths59_Tot_Eng_Previous_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_95_percent"::text END) AS "EngMaths59_Tot_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'First language' AND t."breakdown" = 'Known or believed to be other than English' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_94_percent"::text END) AS "EngMaths49_EAL_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'First language' AND t."breakdown" = 'Known or believed to be other than English' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_95_percent"::text END) AS "EngMaths59_EAL_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Mobility' AND t."breakdown" = 'Non mobile' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_94_percent"::text END) AS "EngMaths49_NMo_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Mobility' AND t."breakdown" = 'Non mobile' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_95_percent"::text END) AS "EngMaths59_NMo_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."lan_multiple_entering_percent"::text END) AS "More1FL_Tot_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_94_percent"::text END) AS "EngMaths49_NDi_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."engmath_95_percent"::text END) AS "EngMaths59_NDi_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."sci_triple_entering_percent"::text END) AS "TripSci_Tot_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."qual_entries_average"::text END) AS "ExamEntriesKS4_Dis_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."qual_entries_average"::text END) AS "ExamEntriesKS4_NDi_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."qual_entries_average"::text END) AS "ExamEntriesKS4_Tot_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."gcse_entries_average"::text END) AS "ExamEntriesGSCE_Tot_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."gcse_entries_average"::text END) AS "ExamEntriesGSCE_Dis_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."gcse_entries_average"::text END) AS "ExamEntriesGSCE_NDi_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'First language' AND t."breakdown" = 'Known or believed to be other than English' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."pupil_count"::text END) AS "Pup_EAL_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."pupil_count"::text END) AS "Pup_Dis_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Mobility' AND t."breakdown" = 'Non mobile' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."pupil_count"::text END) AS "Pup_NMo_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."pupil_count"::text END) AS "Pup_NDi_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."pupil_count"::text END) AS "Pup_NDi_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."breakdown" = 'Not known to be disadvantaged' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."pupil_count"::text END) AS "Pup_NDi_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type_group" = 'All state-funded' THEN t."pupil_count"::text END) AS "Pup_Tot_Eng_Current_Num_Coded"
    FROM t_202425_all_state_fun_ba848234b7 t
    GROUP BY t."geographic_level"
)
,
src_2 AS (
    SELECT
        t."geographic_level" AS "Id",
        MAX(CASE WHEN t."phase_type_grouping" = 'State-funded secondary' AND t."hospital_school" = 'No' AND t."type_of_establishment" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' THEN t."ehc_plan_percent"::text END) AS "PupEHCP_Tot_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."phase_type_grouping" = 'State-funded secondary' AND t."hospital_school" = 'No' AND t."type_of_establishment" = 'Total' AND t."time_period" = '202425' AND t."geographic_level" = 'National' THEN t."sen_support_percent"::text END) AS "PupSEN_Tot_Eng_Current_Pct_Coded"
    FROM t_sen_phase_type__9c901a9464 t
    GROUP BY t."geographic_level"
)
,
src_3 AS (
    SELECT
        t."geographic_level" AS "Id",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202324' AND t."progress_banding" = 'Well Above Average' THEN t."percent_schools"::text END) AS "Prog8Band_Band1_Eng_Previous_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202324' AND t."progress_banding" = 'Above Average' THEN t."percent_schools"::text END) AS "Prog8Band_Band2_Eng_Previous_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202324' AND t."progress_banding" = 'Average' THEN t."percent_schools"::text END) AS "Prog8Band_Band3_Eng_Previous_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202324' AND t."progress_banding" = 'Below Average' THEN t."percent_schools"::text END) AS "Prog8Band_Band4_Eng_Previous_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202324' AND t."progress_banding" = 'Well Below Average' THEN t."percent_schools"::text END) AS "Prog8Band_Band5_Eng_Previous_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202223' AND t."progress_banding" = 'Well Above Average' THEN t."percent_schools"::text END) AS "Prog8Band_Band1_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202223' AND t."progress_banding" = 'Above Average' THEN t."percent_schools"::text END) AS "Prog8Band_Band2_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202223' AND t."progress_banding" = 'Average' THEN t."percent_schools"::text END) AS "Prog8Band_Band3_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202223' AND t."progress_banding" = 'Below Average' THEN t."percent_schools"::text END) AS "Prog8Band_Band4_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202223' AND t."progress_banding" = 'Well Below Average' THEN t."percent_schools"::text END) AS "Prog8Band_Band5_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202324' AND t."progress_banding" = 'Well Above Average' THEN t."banding_description" END) AS "Prog8Band_Band1_Eng_Previous_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202324' AND t."progress_banding" = 'Above Average' THEN t."banding_description" END) AS "Prog8Band_Band2_Eng_Previous_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202324' AND t."progress_banding" = 'Average' THEN t."banding_description" END) AS "Prog8Band_Band3_Eng_Previous_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202324' AND t."progress_banding" = 'Below Average' THEN t."banding_description" END) AS "Prog8Band_Band4_Eng_Previous_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202324' AND t."progress_banding" = 'Well Below Average' THEN t."banding_description" END) AS "Prog8Band_Band5_Eng_Previous_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202223' AND t."progress_banding" = 'Well Above Average' THEN t."banding_description" END) AS "Prog8Band_Band1_Eng_Previous2_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202223' AND t."progress_banding" = 'Above Average' THEN t."banding_description" END) AS "Prog8Band_Band2_Eng_Previous2_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202223' AND t."progress_banding" = 'Average' THEN t."banding_description" END) AS "Prog8Band_Band3_Eng_Previous2_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202223' AND t."progress_banding" = 'Below Average' THEN t."banding_description" END) AS "Prog8Band_Band4_Eng_Previous2_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202223' AND t."progress_banding" = 'Well Below Average' THEN t."banding_description" END) AS "Prog8Band_Band5_Eng_Previous2_Desc"
    FROM t_banding_information__b2381100ed t
    GROUP BY t."geographic_level"
)
,
all_ids AS (
    SELECT "Id" FROM src_1
    UNION SELECT "Id" FROM src_2
    UNION SELECT "Id" FROM src_3
)

SELECT
    a."Id" AS "Id",
    src_1."AnyQual_Tot_Eng_Current_Pct_Coded" AS "AnyQual_Tot_Eng_Current_Pct_Coded",
    src_1."Attainment8_Acad_Eng_Current_Num_Coded" AS "Attainment8_Acad_Eng_Current_Num_Coded",
    src_1."Attainment8_AcadDis_Eng_Current_Num_Coded" AS "Attainment8_AcadDis_Eng_Current_Num_Coded",
    src_1."Attainment8_AcadNDi_Eng_Current_Num_Coded" AS "Attainment8_AcadNDi_Eng_Current_Num_Coded",
    src_1."Attainment8_AnQ_Eng_Current_Num_Coded" AS "Attainment8_AnQ_Eng_Current_Num_Coded",
    src_1."Attainment8_AnQNDis_Eng_Current_Num_Coded" AS "Attainment8_AnQNDis_Eng_Current_Num_Coded",
    src_1."Attainment8_Boy_Eng_Current_Num_Coded" AS "Attainment8_Boy_Eng_Current_Num_Coded",
    src_1."Attainment8_Dis_Eng_Current_Num_Coded" AS "Attainment8_Dis_Eng_Current_Num_Coded",
    src_1."Attainment8_Dis_Eng_Previous_Num_Coded" AS "Attainment8_Dis_Eng_Previous_Num_Coded",
    src_1."Attainment8_Dis_Eng_Previous2_Num_Coded" AS "Attainment8_Dis_Eng_Previous2_Num_Coded",
    src_1."Attainment8_EAL_Eng_Current_Num_Coded" AS "Attainment8_EAL_Eng_Current_Num_Coded",
    src_1."Attainment8_Ebc_Eng_Current_Num_Coded" AS "Attainment8_Ebc_Eng_Current_Num_Coded",
    src_1."Attainment8_Eng_Eng_Current_Num_Coded" AS "Attainment8_Eng_Eng_Current_Num_Coded",
    src_1."Attainment8_EngDis_Eng_Current_Num_Coded" AS "Attainment8_EngDis_Eng_Current_Num_Coded",
    src_1."Attainment8_EngNDi_Eng_Current_Num_Coded" AS "Attainment8_EngNDi_Eng_Current_Num_Coded",
    src_1."Attainment8_Grl_Eng_Current_Num_Coded" AS "Attainment8_Grl_Eng_Current_Num_Coded",
    src_1."Attainment8_Mat_Eng_Current_Num_Coded" AS "Attainment8_Mat_Eng_Current_Num_Coded",
    src_1."Attainment8_MatDis_Eng_Current_Num_Coded" AS "Attainment8_MatDis_Eng_Current_Num_Coded",
    src_1."Attainment8_MatNDi_Eng_Current_Num_Coded" AS "Attainment8_MatNDi_Eng_Current_Num_Coded",
    src_1."Attainment8_NDi_Eng_Current_Num_Coded" AS "Attainment8_NDi_Eng_Current_Num_Coded",
    src_1."Attainment8_NDi_Eng_Previous_Num_Coded" AS "Attainment8_NDi_Eng_Previous_Num_Coded",
    src_1."Attainment8_NDi_Eng_Previous2_Num_Coded" AS "Attainment8_NDi_Eng_Previous2_Num_Coded",
    src_1."Attainment8_NMo_Eng_Current_Num_Coded" AS "Attainment8_NMo_Eng_Current_Num_Coded",
    src_1."Attainment8_Tot_Eng_Current_Num_Coded" AS "Attainment8_Tot_Eng_Current_Num_Coded",
    src_1."Attainment8_Tot_Eng_Previous_Num_Coded" AS "Attainment8_Tot_Eng_Previous_Num_Coded",
    src_1."Attainment8_Tot_Eng_Previous2_Num_Coded" AS "Attainment8_Tot_Eng_Previous2_Num_Coded",
    src_1."Attainment8_Voc_Eng_Current_Num_Coded" AS "Attainment8_Voc_Eng_Current_Num_Coded",
    src_1."Attainment8_VocDis_Eng_Current_Num_Coded" AS "Attainment8_VocDis_Eng_Current_Num_Coded",
    src_1."Attainment8_VocNDi_Eng_Current_Num_Coded" AS "Attainment8_VocNDi_Eng_Current_Num_Coded",
    src_1."EngMaths49_Boy_Eng_Current_Pct_Coded" AS "EngMaths49_Boy_Eng_Current_Pct_Coded",
    src_1."EngMaths49_Dis_Eng_Current_Pct_Coded" AS "EngMaths49_Dis_Eng_Current_Pct_Coded",
    src_1."EngMaths49_EAL_Eng_Current_Pct_Coded" AS "EngMaths49_EAL_Eng_Current_Pct_Coded",
    src_1."EngMaths49_Grl_Eng_Current_Pct_Coded" AS "EngMaths49_Grl_Eng_Current_Pct_Coded",
    src_1."EngMaths49_NDi_Eng_Current_Pct_Coded" AS "EngMaths49_NDi_Eng_Current_Pct_Coded",
    src_1."EngMaths49_NMo_Eng_Current_Pct_Coded" AS "EngMaths49_NMo_Eng_Current_Pct_Coded",
    src_1."EngMaths49_Tot_Eng_Current_Pct_Coded" AS "EngMaths49_Tot_Eng_Current_Pct_Coded",
    src_1."EngMaths49_Tot_Eng_Previous_Pct_Coded" AS "EngMaths49_Tot_Eng_Previous_Pct_Coded",
    src_1."EngMaths49_Tot_Eng_Previous2_Pct_Coded" AS "EngMaths49_Tot_Eng_Previous2_Pct_Coded",
    src_1."EngMaths59_Boy_Eng_Current_Pct_Coded" AS "EngMaths59_Boy_Eng_Current_Pct_Coded",
    src_1."EngMaths59_Dis_Eng_Current_Pct_Coded" AS "EngMaths59_Dis_Eng_Current_Pct_Coded",
    src_1."EngMaths59_EAL_Eng_Current_Pct_Coded" AS "EngMaths59_EAL_Eng_Current_Pct_Coded",
    src_1."EngMaths59_Grl_Eng_Current_Pct_Coded" AS "EngMaths59_Grl_Eng_Current_Pct_Coded",
    src_1."EngMaths59_NDi_Eng_Current_Pct_Coded" AS "EngMaths59_NDi_Eng_Current_Pct_Coded",
    src_1."EngMaths59_NMo_Eng_Current_Pct_Coded" AS "EngMaths59_NMo_Eng_Current_Pct_Coded",
    src_1."EngMaths59_Tot_Eng_Current_Pct_Coded" AS "EngMaths59_Tot_Eng_Current_Pct_Coded",
    src_1."EngMaths59_Tot_Eng_Previous_Pct_Coded" AS "EngMaths59_Tot_Eng_Previous_Pct_Coded",
    src_1."EngMaths59_Tot_Eng_Previous2_Pct_Coded" AS "EngMaths59_Tot_Eng_Previous2_Pct_Coded",
    src_1."ExamEntriesGSCE_Dis_Eng_Current_Num_Coded" AS "ExamEntriesGSCE_Dis_Eng_Current_Num_Coded",
    src_1."ExamEntriesGSCE_NDi_Eng_Current_Num_Coded" AS "ExamEntriesGSCE_NDi_Eng_Current_Num_Coded",
    src_1."ExamEntriesGSCE_Tot_Eng_Current_Num_Coded" AS "ExamEntriesGSCE_Tot_Eng_Current_Num_Coded",
    src_1."ExamEntriesKS4_Dis_Eng_Current_Num_Coded" AS "ExamEntriesKS4_Dis_Eng_Current_Num_Coded",
    src_1."ExamEntriesKS4_NDi_Eng_Current_Num_Coded" AS "ExamEntriesKS4_NDi_Eng_Current_Num_Coded",
    src_1."ExamEntriesKS4_Tot_Eng_Current_Num_Coded" AS "ExamEntriesKS4_Tot_Eng_Current_Num_Coded",
    src_1."More1FL_Tot_Eng_Current_Pct_Coded" AS "More1FL_Tot_Eng_Current_Pct_Coded",
    src_1."Prog8_CI_Lower_Eng_Current_Num_Coded" AS "Prog8_CI_Lower_Eng_Current_Num_Coded",
    src_1."Prog8_CI_Upper_Eng_Current_Num_Coded" AS "Prog8_CI_Upper_Eng_Current_Num_Coded",
    src_1."Prog8_Tot_Eng_Current_Num_Coded" AS "Prog8_Tot_Eng_Current_Num_Coded",
    src_1."Prog8_Tot_Eng_Previous_Num_Coded" AS "Prog8_Tot_Eng_Previous_Num_Coded",
    src_1."Prog8_Tot_Eng_Previous2_Num_Coded" AS "Prog8_Tot_Eng_Previous2_Num_Coded",
    src_1."Prog8_TotPup_Eng_Current_Num_Coded" AS "Prog8_TotPup_Eng_Current_Num_Coded",
    src_1."Prog8_TotPup_Eng_Previous_Num_Coded" AS "Prog8_TotPup_Eng_Previous_Num_Coded",
    src_1."Prog8_TotPup_Eng_Previous2_Num_Coded" AS "Prog8_TotPup_Eng_Previous2_Num_Coded",
    src_3."Prog8Band_Band1_Eng_Previous_Desc" AS "Prog8Band_Band1_Eng_Previous_Desc",
    src_3."Prog8Band_Band1_Eng_Previous_Pct_Coded" AS "Prog8Band_Band1_Eng_Previous_Pct_Coded",
    src_3."Prog8Band_Band1_Eng_Previous2_Desc" AS "Prog8Band_Band1_Eng_Previous2_Desc",
    src_3."Prog8Band_Band1_Eng_Previous2_Pct_Coded" AS "Prog8Band_Band1_Eng_Previous2_Pct_Coded",
    src_3."Prog8Band_Band2_Eng_Previous_Desc" AS "Prog8Band_Band2_Eng_Previous_Desc",
    src_3."Prog8Band_Band2_Eng_Previous_Pct_Coded" AS "Prog8Band_Band2_Eng_Previous_Pct_Coded",
    src_3."Prog8Band_Band2_Eng_Previous2_Desc" AS "Prog8Band_Band2_Eng_Previous2_Desc",
    src_3."Prog8Band_Band2_Eng_Previous2_Pct_Coded" AS "Prog8Band_Band2_Eng_Previous2_Pct_Coded",
    src_3."Prog8Band_Band3_Eng_Previous_Desc" AS "Prog8Band_Band3_Eng_Previous_Desc",
    src_3."Prog8Band_Band3_Eng_Previous_Pct_Coded" AS "Prog8Band_Band3_Eng_Previous_Pct_Coded",
    src_3."Prog8Band_Band3_Eng_Previous2_Desc" AS "Prog8Band_Band3_Eng_Previous2_Desc",
    src_3."Prog8Band_Band3_Eng_Previous2_Pct_Coded" AS "Prog8Band_Band3_Eng_Previous2_Pct_Coded",
    src_3."Prog8Band_Band4_Eng_Previous_Desc" AS "Prog8Band_Band4_Eng_Previous_Desc",
    src_3."Prog8Band_Band4_Eng_Previous_Pct_Coded" AS "Prog8Band_Band4_Eng_Previous_Pct_Coded",
    src_3."Prog8Band_Band4_Eng_Previous2_Desc" AS "Prog8Band_Band4_Eng_Previous2_Desc",
    src_3."Prog8Band_Band4_Eng_Previous2_Pct_Coded" AS "Prog8Band_Band4_Eng_Previous2_Pct_Coded",
    src_3."Prog8Band_Band5_Eng_Previous_Desc" AS "Prog8Band_Band5_Eng_Previous_Desc",
    src_3."Prog8Band_Band5_Eng_Previous_Pct_Coded" AS "Prog8Band_Band5_Eng_Previous_Pct_Coded",
    src_3."Prog8Band_Band5_Eng_Previous2_Desc" AS "Prog8Band_Band5_Eng_Previous2_Desc",
    src_3."Prog8Band_Band5_Eng_Previous2_Pct_Coded" AS "Prog8Band_Band5_Eng_Previous2_Pct_Coded",
    src_1."Pup_Boy_Eng_Current_Num_Coded" AS "Pup_Boy_Eng_Current_Num_Coded",
    src_1."Pup_Dis_Eng_Current_Num_Coded" AS "Pup_Dis_Eng_Current_Num_Coded",
    src_1."Pup_EAL_Eng_Current_Num_Coded" AS "Pup_EAL_Eng_Current_Num_Coded",
    src_1."Pup_Grl_Eng_Current_Num_Coded" AS "Pup_Grl_Eng_Current_Num_Coded",
    src_1."Pup_NDi_Eng_Current_Num_Coded" AS "Pup_NDi_Eng_Current_Num_Coded",
    src_1."Pup_NDi_Eng_Previous_Num_Coded" AS "Pup_NDi_Eng_Previous_Num_Coded",
    src_1."Pup_NDi_Eng_Previous2_Num_Coded" AS "Pup_NDi_Eng_Previous2_Num_Coded",
    src_1."Pup_NMo_Eng_Current_Num_Coded" AS "Pup_NMo_Eng_Current_Num_Coded",
    src_1."Pup_Tot_Eng_Current_Num_Coded" AS "Pup_Tot_Eng_Current_Num_Coded",
    src_2."PupEHCP_Tot_Eng_Current_Pct_Coded" AS "PupEHCP_Tot_Eng_Current_Pct_Coded",
    src_2."PupSEN_Tot_Eng_Current_Pct_Coded" AS "PupSEN_Tot_Eng_Current_Pct_Coded",
    src_1."TripSci_Tot_Eng_Current_Pct_Coded" AS "TripSci_Tot_Eng_Current_Pct_Coded"
FROM all_ids a
LEFT JOIN src_1 ON src_1."Id" = a."Id"
LEFT JOIN src_2 ON src_2."Id" = a."Id"
LEFT JOIN src_3 ON src_3."Id" = a."Id"
;
