-- AUTO-GENERATED MATERIALIZED VIEW: v_establishment_ks5_performance

DROP MATERIALIZED VIEW IF EXISTS v_establishment_ks5_performance;

CREATE MATERIALIZED VIEW v_establishment_ks5_performance AS
WITH
src_1 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' THEN t."english_progress_entries_percent"::text END) AS "ENTRY_PER_E_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' THEN t."maths_progress_entries_percent"::text END) AS "ENTRY_PER_M_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' THEN t."level_3_maths_percent"::text END) AS "L3M_PER_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_ACAD_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_ACAD_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_AGEN_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_AGEN_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_ALEV_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_ALEV_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_TECHCERT_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_TECHCERT_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_TLEV_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_TLEV_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' THEN t."english_progress"::text END) AS "PROGEX_E_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' THEN t."english_progress"::text END) AS "PROGEX_E_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' THEN t."maths_progress"::text END) AS "PROGEX_M_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' THEN t."maths_progress"::text END) AS "PROGEX_M_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."progress_banding" END) AS "PROGRESS_BAND_ACAD_Est_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."progress_banding" END) AS "PROGRESS_BAND_AGEN_Est_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."progress_banding" END) AS "PROGRESS_BAND_ALEV_Est_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."progress_banding" END) AS "PROGRESS_BAND_TECHCERT_Est_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."progress_banding" END) AS "PROGRESS_BAND_TLEV_Est_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_ACAD_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_AGEN_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_ALEV_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_TECHCERT_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_TLEV_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_23_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_24_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_DIS_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_23_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202324' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_24_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_DIS_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202223' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_23_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202324' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_24_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_DIS_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202223' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_23_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202324' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_24_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."retained_percent"::text END) AS "PT_Retained_TECHCERT_Ret_DIS_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202223' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_23_Est_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202324' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_24_Est_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_DIS_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."aab_percent"::text END) AS "PTAAB_2FAC_Est_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."retained_student_count"::text END) AS "T_InScope_ACAD_Ret_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."retained_student_count"::text END) AS "T_INSCOPE_ACAD_RET_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."retained_student_count"::text END) AS "T_InScope_AGEN_Ret_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."retained_student_count"::text END) AS "T_INSCOPE_AGEN_RET_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."retained_student_count"::text END) AS "T_InScope_ALEV_Ret_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."retained_student_count"::text END) AS "T_InScope_ALEV_Ret_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."retained_student_count"::text END) AS "T_InScope_TECHCERT_Ret_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."retained_student_count"::text END) AS "T_INSCOPE_TECHCERT_RET_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."retained_student_count"::text END) AS "T_InScope_TLEV_Ret_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' THEN t."english_progress_inscope_count"::text END) AS "T_SCOPEEX_E_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' THEN t."english_progress_inscope_count"::text END) AS "T_SCOPEEX_E_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' THEN t."maths_progress_inscope_count"::text END) AS "T_SCOPEEX_M_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' THEN t."maths_progress_inscope_count"::text END) AS "T_SCOPEEX_M_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202324' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202223' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202324' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202223' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202324' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202223' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202324' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ACAD_1618_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ACAD_1618_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ACAD_1618_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ACAD_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_AGEN_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_AGEN_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202324' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_AGEN_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_AGEN_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ALEV_1618_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ALEV_1618_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ALEV_1618_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ALEV_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TECHCERT_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202223' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TECHCERT_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202324' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TECHCERT_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TECHCERT_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TLEV_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202223' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TLEV_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202324' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TLEV_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TLEV_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TLEV_DIS_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."end1618_student_count"::text END) AS "TALLPUP_1618_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."end1618_student_count"::text END) AS "TALLPUP_1618_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ACAD_1618_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ACAD_1618_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ACAD_1618_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ACAD_1618_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_AGEN_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_AGEN_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202324' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_AGEN_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_AGEN_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ALEV_1618_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202223' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ALEV_1618_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202324' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ALEV_1618_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ALEV_1618_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TECHCERT_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202223' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TECHCERT_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202324' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TECHCERT_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TECHCERT_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TLEV_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202223' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TLEV_23_Est_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202324' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TLEV_24_Est_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TLEV_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."best_three_alevels_aps"::text END) AS "TB3PTSE_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."best_three_alevels_grade"::text END) AS "TB3PTSE_GRD_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."aab_student_count"::text END) AS "TINCLUDE_AAB_2FAC_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."best_three_alevels_student_count"::text END) AS "TINCLUDE_B3_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_ACAD_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_ACAD_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_AGEN_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_AGEN_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_ALEV_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_ALEV_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_TECHCERT_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_TECHCERT_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_TLEV_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_TLEV_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."value_added"::text END) AS "VA_INS_ACAD_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' THEN t."value_added"::text END) AS "VA_INS_ACAD_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."value_added"::text END) AS "VA_INS_AGEN_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' THEN t."value_added"::text END) AS "VA_INS_AGEN_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."value_added"::text END) AS "VA_INS_ALEV_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' THEN t."value_added"::text END) AS "VA_INS_ALEV_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."value_added"::text END) AS "VA_INS_TECHCERT_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' THEN t."value_added"::text END) AS "VA_INS_TECHCERT_DIS_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."value_added"::text END) AS "VA_INS_TLEV_Est_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' THEN t."value_added"::text END) AS "VA_INS_TLEV_DIS_Est_Current_Num_Coded"
    FROM t_institution_performa_9b77f00557 t
    GROUP BY t."school_urn"
)
,
all_ids AS (
    SELECT "Id" FROM src_1
)

SELECT
    a."Id" AS "Id",
    e."LAId" AS "LAId",
    e."LAName" AS "LAName",
    e."RegionId" AS "RegionId",
    e."RegionName" AS "RegionName",
    e."LAId" || e."EstablishmentNumber" AS "LAEstab",
    src_1."ENTRY_PER_E_Est_Current_Pct_Coded" AS "ENTRY_PER_E_Est_Current_Pct_Coded",
    src_1."ENTRY_PER_M_Est_Current_Pct_Coded" AS "ENTRY_PER_M_Est_Current_Pct_Coded",
    src_1."L3M_PER_Est_Current_Pct_Coded" AS "L3M_PER_Est_Current_Pct_Coded",
    src_1."LCI_INS_ACAD_DIS_Est_Current_Num_Coded" AS "LCI_INS_ACAD_DIS_Est_Current_Num_Coded",
    src_1."LCI_INS_ACAD_Est_Current_Num_Coded" AS "LCI_INS_ACAD_Est_Current_Num_Coded",
    src_1."LCI_INS_AGEN_DIS_Est_Current_Num_Coded" AS "LCI_INS_AGEN_DIS_Est_Current_Num_Coded",
    src_1."LCI_INS_AGEN_Est_Current_Num_Coded" AS "LCI_INS_AGEN_Est_Current_Num_Coded",
    src_1."LCI_INS_ALEV_DIS_Est_Current_Num_Coded" AS "LCI_INS_ALEV_DIS_Est_Current_Num_Coded",
    src_1."LCI_INS_ALEV_Est_Current_Num_Coded" AS "LCI_INS_ALEV_Est_Current_Num_Coded",
    src_1."LCI_INS_TECHCERT_DIS_Est_Current_Num_Coded" AS "LCI_INS_TECHCERT_DIS_Est_Current_Num_Coded",
    src_1."LCI_INS_TECHCERT_Est_Current_Num_Coded" AS "LCI_INS_TECHCERT_Est_Current_Num_Coded",
    src_1."LCI_INS_TLEV_DIS_Est_Current_Num_Coded" AS "LCI_INS_TLEV_DIS_Est_Current_Num_Coded",
    src_1."LCI_INS_TLEV_Est_Current_Num_Coded" AS "LCI_INS_TLEV_Est_Current_Num_Coded",
    src_1."PROGEX_E_DIS_Est_Current_Num_Coded" AS "PROGEX_E_DIS_Est_Current_Num_Coded",
    src_1."PROGEX_E_Est_Current_Num_Coded" AS "PROGEX_E_Est_Current_Num_Coded",
    src_1."PROGEX_M_DIS_Est_Current_Num_Coded" AS "PROGEX_M_DIS_Est_Current_Num_Coded",
    src_1."PROGEX_M_Est_Current_Num_Coded" AS "PROGEX_M_Est_Current_Num_Coded",
    src_1."PROGRESS_BAND_ACAD_Est_Current" AS "PROGRESS_BAND_ACAD_Est_Current",
    src_1."PROGRESS_BAND_AGEN_Est_Current" AS "PROGRESS_BAND_AGEN_Est_Current",
    src_1."PROGRESS_BAND_ALEV_Est_Current" AS "PROGRESS_BAND_ALEV_Est_Current",
    src_1."PROGRESS_BAND_TECHCERT_Est_Current" AS "PROGRESS_BAND_TECHCERT_Est_Current",
    src_1."PROGRESS_BAND_TLEV_Est_Current" AS "PROGRESS_BAND_TLEV_Est_Current",
    src_1."PT_RET_ASSESSED_ACAD_Est_Current_Pct_Coded" AS "PT_RET_ASSESSED_ACAD_Est_Current_Pct_Coded",
    src_1."PT_RET_ASSESSED_AGEN_Est_Current_Pct_Coded" AS "PT_RET_ASSESSED_AGEN_Est_Current_Pct_Coded",
    src_1."PT_RET_ASSESSED_ALEV_Est_Current_Pct_Coded" AS "PT_RET_ASSESSED_ALEV_Est_Current_Pct_Coded",
    src_1."PT_RET_ASSESSED_TECHCERT_Est_Current_Pct_Coded" AS "PT_RET_ASSESSED_TECHCERT_Est_Current_Pct_Coded",
    src_1."PT_RET_ASSESSED_TLEV_Est_Current_Pct_Coded" AS "PT_RET_ASSESSED_TLEV_Est_Current_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_23_Est_Previous2_Pct_Coded" AS "PT_RETAINED_ACAD_RET_23_Est_Previous2_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_24_Est_Previous_Pct_Coded" AS "PT_RETAINED_ACAD_RET_24_Est_Previous_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_DIS_Est_Current_Pct_Coded" AS "PT_RETAINED_ACAD_RET_DIS_Est_Current_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_Est_Current_Pct_Coded" AS "PT_RETAINED_ACAD_RET_Est_Current_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_23_Est_Previous2_Pct_Coded" AS "PT_RETAINED_AGEN_RET_23_Est_Previous2_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_24_Est_Previous_Pct_Coded" AS "PT_RETAINED_AGEN_RET_24_Est_Previous_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_DIS_Est_Current_Pct_Coded" AS "PT_RETAINED_AGEN_RET_DIS_Est_Current_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_Est_Current_Pct_Coded" AS "PT_RETAINED_AGEN_RET_Est_Current_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_23_Est_Previous2_Pct_Coded" AS "PT_RETAINED_ALEV_RET_23_Est_Previous2_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_24_Est_Previous_Pct_Coded" AS "PT_RETAINED_ALEV_RET_24_Est_Previous_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_DIS_Est_Current_Pct_Coded" AS "PT_RETAINED_ALEV_RET_DIS_Est_Current_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_Est_Current_Pct_Coded" AS "PT_RETAINED_ALEV_RET_Est_Current_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_23_Est_Previous2_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_23_Est_Previous2_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_24_Est_Previous_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_24_Est_Previous_Pct_Coded",
    src_1."PT_Retained_TECHCERT_Ret_DIS_Est_Current_Pct_Coded" AS "PT_Retained_TECHCERT_Ret_DIS_Est_Current_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_Est_Current_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_Est_Current_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_23_Est_Previous2_Pct_Coded" AS "PT_RETAINED_TLEV_RET_23_Est_Previous2_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_24_Est_Previous_Pct_Coded" AS "PT_RETAINED_TLEV_RET_24_Est_Previous_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_DIS_Est_Current_Pct_Coded" AS "PT_RETAINED_TLEV_RET_DIS_Est_Current_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_Est_Current_Pct_Coded" AS "PT_RETAINED_TLEV_RET_Est_Current_Pct_Coded",
    src_1."PTAAB_2FAC_Est_Current_Pct_Coded" AS "PTAAB_2FAC_Est_Current_Pct_Coded",
    src_1."T_INSCOPE_ACAD_RET_DIS_Est_Current_Num_Coded" AS "T_INSCOPE_ACAD_RET_DIS_Est_Current_Num_Coded",
    src_1."T_InScope_ACAD_Ret_Est_Current_Num_Coded" AS "T_InScope_ACAD_Ret_Est_Current_Num_Coded",
    src_1."T_INSCOPE_AGEN_RET_DIS_Est_Current_Num_Coded" AS "T_INSCOPE_AGEN_RET_DIS_Est_Current_Num_Coded",
    src_1."T_InScope_AGEN_Ret_Est_Current_Num_Coded" AS "T_InScope_AGEN_Ret_Est_Current_Num_Coded",
    src_1."T_InScope_ALEV_Ret_DIS_Est_Current_Num_Coded" AS "T_InScope_ALEV_Ret_DIS_Est_Current_Num_Coded",
    src_1."T_InScope_ALEV_Ret_Est_Current_Num_Coded" AS "T_InScope_ALEV_Ret_Est_Current_Num_Coded",
    src_1."T_INSCOPE_TECHCERT_RET_DIS_Est_Current_Num_Coded" AS "T_INSCOPE_TECHCERT_RET_DIS_Est_Current_Num_Coded",
    src_1."T_InScope_TECHCERT_Ret_Est_Current_Num_Coded" AS "T_InScope_TECHCERT_Ret_Est_Current_Num_Coded",
    src_1."T_InScope_TLEV_Ret_Est_Current_Num_Coded" AS "T_InScope_TLEV_Ret_Est_Current_Num_Coded",
    src_1."T_SCOPEEX_E_DIS_Est_Current_Num_Coded" AS "T_SCOPEEX_E_DIS_Est_Current_Num_Coded",
    src_1."T_SCOPEEX_E_Est_Current_Num_Coded" AS "T_SCOPEEX_E_Est_Current_Num_Coded",
    src_1."T_SCOPEEX_M_DIS_Est_Current_Num_Coded" AS "T_SCOPEEX_M_DIS_Est_Current_Num_Coded",
    src_1."T_SCOPEEX_M_Est_Current_Num_Coded" AS "T_SCOPEEX_M_Est_Current_Num_Coded",
    src_1."TALLPPE_ACAD_1618_23_Est_Previous2_Num_Coded" AS "TALLPPE_ACAD_1618_23_Est_Previous2_Num_Coded",
    src_1."TALLPPE_ACAD_1618_24_Est_Previous_Num_Coded" AS "TALLPPE_ACAD_1618_24_Est_Previous_Num_Coded",
    src_1."TALLPPE_ACAD_1618_DIS_Est_Current_Num_Coded" AS "TALLPPE_ACAD_1618_DIS_Est_Current_Num_Coded",
    src_1."TALLPPE_ACAD_1618_Est_Current_Num_Coded" AS "TALLPPE_ACAD_1618_Est_Current_Num_Coded",
    src_1."TALLPPE_AGEN_23_Est_Previous2_Num_Coded" AS "TALLPPE_AGEN_23_Est_Previous2_Num_Coded",
    src_1."TALLPPE_AGEN_24_Est_Previous_Num_Coded" AS "TALLPPE_AGEN_24_Est_Previous_Num_Coded",
    src_1."TALLPPE_AGEN_DIS_Est_Current_Num_Coded" AS "TALLPPE_AGEN_DIS_Est_Current_Num_Coded",
    src_1."TALLPPE_AGEN_Est_Current_Num_Coded" AS "TALLPPE_AGEN_Est_Current_Num_Coded",
    src_1."TALLPPE_ALEV_1618_23_Est_Previous2_Num_Coded" AS "TALLPPE_ALEV_1618_23_Est_Previous2_Num_Coded",
    src_1."TALLPPE_ALEV_1618_24_Est_Previous_Num_Coded" AS "TALLPPE_ALEV_1618_24_Est_Previous_Num_Coded",
    src_1."TALLPPE_ALEV_1618_DIS_Est_Current_Num_Coded" AS "TALLPPE_ALEV_1618_DIS_Est_Current_Num_Coded",
    src_1."TALLPPE_ALEV_1618_Est_Current_Num_Coded" AS "TALLPPE_ALEV_1618_Est_Current_Num_Coded",
    src_1."TALLPPE_TECHCERT_23_Est_Previous2_Num_Coded" AS "TALLPPE_TECHCERT_23_Est_Previous2_Num_Coded",
    src_1."TALLPPE_TECHCERT_24_Est_Previous_Num_Coded" AS "TALLPPE_TECHCERT_24_Est_Previous_Num_Coded",
    src_1."TALLPPE_TECHCERT_DIS_Est_Current_Num_Coded" AS "TALLPPE_TECHCERT_DIS_Est_Current_Num_Coded",
    src_1."TALLPPE_TECHCERT_Est_Current_Num_Coded" AS "TALLPPE_TECHCERT_Est_Current_Num_Coded",
    src_1."TALLPPE_TLEV_23_Est_Previous2_Num_Coded" AS "TALLPPE_TLEV_23_Est_Previous2_Num_Coded",
    src_1."TALLPPE_TLEV_24_Est_Previous_Num_Coded" AS "TALLPPE_TLEV_24_Est_Previous_Num_Coded",
    src_1."TALLPPE_TLEV_DIS_Est_Current_Num_Coded" AS "TALLPPE_TLEV_DIS_Est_Current_Num_Coded",
    src_1."TALLPPE_TLEV_Est_Current_Num_Coded" AS "TALLPPE_TLEV_Est_Current_Num_Coded",
    src_1."TALLPPEGRD_ACAD_1618_23_Est_Previous2_Num_Coded" AS "TALLPPEGRD_ACAD_1618_23_Est_Previous2_Num_Coded",
    src_1."TALLPPEGRD_ACAD_1618_24_Est_Previous_Num_Coded" AS "TALLPPEGRD_ACAD_1618_24_Est_Previous_Num_Coded",
    src_1."TALLPPEGRD_ACAD_1618_Est_Current_Num_Coded" AS "TALLPPEGRD_ACAD_1618_Est_Current_Num_Coded",
    src_1."TALLPPEGRD_ACAD_DIS_Est_Current_Num_Coded" AS "TALLPPEGRD_ACAD_DIS_Est_Current_Num_Coded",
    src_1."TALLPPEGRD_AGEN_23_Est_Previous2_Num_Coded" AS "TALLPPEGRD_AGEN_23_Est_Previous2_Num_Coded",
    src_1."TALLPPEGRD_AGEN_24_Est_Previous_Num_Coded" AS "TALLPPEGRD_AGEN_24_Est_Previous_Num_Coded",
    src_1."TALLPPEGRD_AGEN_DIS_Est_Current_Num_Coded" AS "TALLPPEGRD_AGEN_DIS_Est_Current_Num_Coded",
    src_1."TALLPPEGRD_AGEN_Est_Current_Num_Coded" AS "TALLPPEGRD_AGEN_Est_Current_Num_Coded",
    src_1."TALLPPEGRD_ALEV_1618_23_Est_Previous2_Num_Coded" AS "TALLPPEGRD_ALEV_1618_23_Est_Previous2_Num_Coded",
    src_1."TALLPPEGRD_ALEV_1618_24_Est_Previous_Num_Coded" AS "TALLPPEGRD_ALEV_1618_24_Est_Previous_Num_Coded",
    src_1."TALLPPEGRD_ALEV_1618_Est_Current_Num_Coded" AS "TALLPPEGRD_ALEV_1618_Est_Current_Num_Coded",
    src_1."TALLPPEGRD_ALEV_DIS_Est_Current_Num_Coded" AS "TALLPPEGRD_ALEV_DIS_Est_Current_Num_Coded",
    src_1."TALLPPEGRD_TECHCERT_23_Est_Previous2_Num_Coded" AS "TALLPPEGRD_TECHCERT_23_Est_Previous2_Num_Coded",
    src_1."TALLPPEGRD_TECHCERT_24_Est_Previous_Num_Coded" AS "TALLPPEGRD_TECHCERT_24_Est_Previous_Num_Coded",
    src_1."TALLPPEGRD_TECHCERT_DIS_Est_Current_Num_Coded" AS "TALLPPEGRD_TECHCERT_DIS_Est_Current_Num_Coded",
    src_1."TALLPPEGRD_TECHCERT_Est_Current_Num_Coded" AS "TALLPPEGRD_TECHCERT_Est_Current_Num_Coded",
    src_1."TALLPPEGRD_TLEV_23_Est_Previous2_Num_Coded" AS "TALLPPEGRD_TLEV_23_Est_Previous2_Num_Coded",
    src_1."TALLPPEGRD_TLEV_24_Est_Previous_Num_Coded" AS "TALLPPEGRD_TLEV_24_Est_Previous_Num_Coded",
    src_1."TALLPPEGRD_TLEV_DIS_24_Est_Previous_Num_Coded" AS "TALLPPEGRD_TLEV_DIS_24_Est_Previous_Num_Coded",
    src_1."TALLPPEGRD_TLEV_DIS_Est_Current_Num_Coded" AS "TALLPPEGRD_TLEV_DIS_Est_Current_Num_Coded",
    src_1."TALLPPEGRD_TLEV_Est_Current_Num_Coded" AS "TALLPPEGRD_TLEV_Est_Current_Num_Coded",
    src_1."TALLPUP_1618_DIS_Est_Current_Num_Coded" AS "TALLPUP_1618_DIS_Est_Current_Num_Coded",
    src_1."TALLPUP_1618_Est_Current_Num_Coded" AS "TALLPUP_1618_Est_Current_Num_Coded",
    src_1."TALLPUP_ACAD_1618_23_Est_Previous2_Num_Coded" AS "TALLPUP_ACAD_1618_23_Est_Previous2_Num_Coded",
    src_1."TALLPUP_ACAD_1618_24_Est_Previous_Num_Coded" AS "TALLPUP_ACAD_1618_24_Est_Previous_Num_Coded",
    src_1."TALLPUP_ACAD_1618_DIS_Est_Current_Num_Coded" AS "TALLPUP_ACAD_1618_DIS_Est_Current_Num_Coded",
    src_1."TALLPUP_ACAD_1618_Est_Current_Num_Coded" AS "TALLPUP_ACAD_1618_Est_Current_Num_Coded",
    src_1."TALLPUP_AGEN_23_Est_Previous2_Num_Coded" AS "TALLPUP_AGEN_23_Est_Previous2_Num_Coded",
    src_1."TALLPUP_AGEN_24_Est_Previous_Num_Coded" AS "TALLPUP_AGEN_24_Est_Previous_Num_Coded",
    src_1."TALLPUP_AGEN_DIS_Est_Current_Num_Coded" AS "TALLPUP_AGEN_DIS_Est_Current_Num_Coded",
    src_1."TALLPUP_AGEN_Est_Current_Num_Coded" AS "TALLPUP_AGEN_Est_Current_Num_Coded",
    src_1."TALLPUP_ALEV_1618_23_Est_Previous2_Num_Coded" AS "TALLPUP_ALEV_1618_23_Est_Previous2_Num_Coded",
    src_1."TALLPUP_ALEV_1618_24_Est_Previous_Num_Coded" AS "TALLPUP_ALEV_1618_24_Est_Previous_Num_Coded",
    src_1."TALLPUP_ALEV_1618_DIS_Est_Current_Num_Coded" AS "TALLPUP_ALEV_1618_DIS_Est_Current_Num_Coded",
    src_1."TALLPUP_ALEV_1618_Est_Current_Num_Coded" AS "TALLPUP_ALEV_1618_Est_Current_Num_Coded",
    src_1."TALLPUP_TECHCERT_23_Est_Previous2_Num_Coded" AS "TALLPUP_TECHCERT_23_Est_Previous2_Num_Coded",
    src_1."TALLPUP_TECHCERT_24_Est_Previous_Num_Coded" AS "TALLPUP_TECHCERT_24_Est_Previous_Num_Coded",
    src_1."TALLPUP_TECHCERT_DIS_Est_Current_Num_Coded" AS "TALLPUP_TECHCERT_DIS_Est_Current_Num_Coded",
    src_1."TALLPUP_TECHCERT_Est_Current_Num_Coded" AS "TALLPUP_TECHCERT_Est_Current_Num_Coded",
    src_1."TALLPUP_TLEV_23_Est_Previous2_Num_Coded" AS "TALLPUP_TLEV_23_Est_Previous2_Num_Coded",
    src_1."TALLPUP_TLEV_24_Est_Previous_Num_Coded" AS "TALLPUP_TLEV_24_Est_Previous_Num_Coded",
    src_1."TALLPUP_TLEV_DIS_Est_Current_Num_Coded" AS "TALLPUP_TLEV_DIS_Est_Current_Num_Coded",
    src_1."TALLPUP_TLEV_Est_Current_Num_Coded" AS "TALLPUP_TLEV_Est_Current_Num_Coded",
    src_1."TB3PTSE_Est_Current_Num_Coded" AS "TB3PTSE_Est_Current_Num_Coded",
    src_1."TB3PTSE_GRD_Est_Current_Num_Coded" AS "TB3PTSE_GRD_Est_Current_Num_Coded",
    src_1."TINCLUDE_AAB_2FAC_Est_Current_Num_Coded" AS "TINCLUDE_AAB_2FAC_Est_Current_Num_Coded",
    src_1."TINCLUDE_B3_Est_Current_Num_Coded" AS "TINCLUDE_B3_Est_Current_Num_Coded",
    src_1."UCI_INS_ACAD_DIS_Est_Current_Num_Coded" AS "UCI_INS_ACAD_DIS_Est_Current_Num_Coded",
    src_1."UCI_INS_ACAD_Est_Current_Num_Coded" AS "UCI_INS_ACAD_Est_Current_Num_Coded",
    src_1."UCI_INS_AGEN_DIS_Est_Current_Num_Coded" AS "UCI_INS_AGEN_DIS_Est_Current_Num_Coded",
    src_1."UCI_INS_AGEN_Est_Current_Num_Coded" AS "UCI_INS_AGEN_Est_Current_Num_Coded",
    src_1."UCI_INS_ALEV_DIS_Est_Current_Num_Coded" AS "UCI_INS_ALEV_DIS_Est_Current_Num_Coded",
    src_1."UCI_INS_ALEV_Est_Current_Num_Coded" AS "UCI_INS_ALEV_Est_Current_Num_Coded",
    src_1."UCI_INS_TECHCERT_DIS_Est_Current_Num_Coded" AS "UCI_INS_TECHCERT_DIS_Est_Current_Num_Coded",
    src_1."UCI_INS_TECHCERT_Est_Current_Num_Coded" AS "UCI_INS_TECHCERT_Est_Current_Num_Coded",
    src_1."UCI_INS_TLEV_DIS_Est_Current_Num_Coded" AS "UCI_INS_TLEV_DIS_Est_Current_Num_Coded",
    src_1."UCI_INS_TLEV_Est_Current_Num_Coded" AS "UCI_INS_TLEV_Est_Current_Num_Coded",
    src_1."VA_INS_ACAD_DIS_Est_Current_Num_Coded" AS "VA_INS_ACAD_DIS_Est_Current_Num_Coded",
    src_1."VA_INS_ACAD_Est_Current_Num_Coded" AS "VA_INS_ACAD_Est_Current_Num_Coded",
    src_1."VA_INS_AGEN_DIS_Est_Current_Num_Coded" AS "VA_INS_AGEN_DIS_Est_Current_Num_Coded",
    src_1."VA_INS_AGEN_Est_Current_Num_Coded" AS "VA_INS_AGEN_Est_Current_Num_Coded",
    src_1."VA_INS_ALEV_DIS_Est_Current_Num_Coded" AS "VA_INS_ALEV_DIS_Est_Current_Num_Coded",
    src_1."VA_INS_ALEV_Est_Current_Num_Coded" AS "VA_INS_ALEV_Est_Current_Num_Coded",
    src_1."VA_INS_TECHCERT_DIS_Est_Current_Num_Coded" AS "VA_INS_TECHCERT_DIS_Est_Current_Num_Coded",
    src_1."VA_INS_TECHCERT_Est_Current_Num_Coded" AS "VA_INS_TECHCERT_Est_Current_Num_Coded",
    src_1."VA_INS_TLEV_DIS_Est_Current_Num_Coded" AS "VA_INS_TLEV_DIS_Est_Current_Num_Coded",
    src_1."VA_INS_TLEV_Est_Current_Num_Coded" AS "VA_INS_TLEV_Est_Current_Num_Coded"
FROM all_ids a
LEFT JOIN src_1 ON src_1."Id" = a."Id"
LEFT JOIN v_establishment e ON e."URN" = a."Id"
;
