-- AUTO-GENERATED MATERIALIZED VIEW: v_la_ks5_performance

DROP MATERIALIZED VIEW IF EXISTS v_la_ks5_performance;

CREATE MATERIALIZED VIEW v_la_ks5_performance AS
WITH
src_1 AS (
    SELECT
        t."old_la_code" AS "Id",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."level_3_maths_percent"::text END) AS "L3M_PER_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_ACAD_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_AGEN_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_ALEV_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_TECHCERT_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_TLEV_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ACAD_1618_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ACAD_1618_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ALEV_1618_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ALEV_1618_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TLEV_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TLEV_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TB3PTSE_GRD_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_ACAD_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_AGEN_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_ALEV_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_TECHCERT_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_TLEV_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_NOTDIS_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."english_progress_entries_percent"::text END) AS "ENTRY_PER_E_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."maths_progress_entries_percent"::text END) AS "ENTRY_PER_M_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_ACAD_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_AGEN_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_ALEV_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_TECHCERT_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_TLEV_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."english_progress"::text END) AS "PROGEX_E_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."english_progress"::text END) AS "PROGEX_E_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."english_progress"::text END) AS "PROGEX_E_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."maths_progress"::text END) AS "PROGEX_M_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."maths_progress"::text END) AS "PROGEX_M_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."maths_progress"::text END) AS "PROGEX_M_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_ACAD_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_AGEN_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_ALEV_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_TECHCERT_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_TLEV_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_23_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_24_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_23_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_24_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_DIS_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_NOTDIS_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_23_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_24_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_DIS_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_NOTDIS_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_23_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_24_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_DIS_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_NOTDIS_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_23_LA_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_24_LA_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_DIS_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_NOTDIS_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aab_percent"::text END) AS "PTAAB_2FAC_LA_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."english_progress_inscope_count"::text END) AS "T_SCOPEEX_E_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."english_progress_inscope_count"::text END) AS "T_SCOPEEX_E_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."maths_progress_inscope_count"::text END) AS "T_SCOPEEX_M_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."maths_progress_inscope_count"::text END) AS "T_SCOPEEX_M_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_23_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_24_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_23_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_24_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_23_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_24_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_23_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_24_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_23_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_24_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ACAD_1618_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ACAD_1618_23_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ACAD_1618_24_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ACAD_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ACAD_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_AGEN_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_AGEN_23_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_AGEN_24_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_AGEN_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_AGEN_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ALEV_1618_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ALEV_1618_23_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ALEV_1618_24_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ALEV_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_ALEV_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TECHCERT_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TECHCERT_23_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TECHCERT_24_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TECHCERT_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TECHCERT_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TLEV_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TLEV_23_LA_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202324' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TLEV_24_LA_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TLEV_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_grade"::text END) AS "TALLPPEGRD_TLEV_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."end1618_student_count"::text END) AS "TALLPUP_1618_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."end1618_student_count"::text END) AS "TALLPUP_1618_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ACAD_1618_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_AGEN_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_AGEN_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TECHCERT_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TECHCERT_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."best_three_alevels_aps"::text END) AS "TB3PTSE_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_ACAD_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_AGEN_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_ALEV_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_TECHCERT_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_TLEV_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added"::text END) AS "VA_INS_ACAD_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added"::text END) AS "VA_INS_ACAD_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added"::text END) AS "VA_INS_AGEN_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added"::text END) AS "VA_INS_AGEN_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added"::text END) AS "VA_INS_ALEV_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added"::text END) AS "VA_INS_ALEV_NOTDIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added"::text END) AS "VA_INS_TLEV_DIS_LA_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'Local authority' THEN t."value_added"::text END) AS "VA_INS_TLEV_NOTDIS_LA_Current_Num_Coded"
    FROM t_national_performance_89ee26b9ac t
    GROUP BY t."old_la_code"
)
,
all_ids AS (
    SELECT "Id" FROM src_1
)

SELECT
    a."Id" AS "Id",
    src_1."ENTRY_PER_E_LA_Current_Pct_Coded" AS "ENTRY_PER_E_LA_Current_Pct_Coded",
    src_1."ENTRY_PER_M_LA_Current_Pct_Coded" AS "ENTRY_PER_M_LA_Current_Pct_Coded",
    src_1."L3M_PER_LA_Current_Pct_Coded" AS "L3M_PER_LA_Current_Pct_Coded",
    src_1."LCI_INS_ACAD_DIS_LA_Current_Num_Coded" AS "LCI_INS_ACAD_DIS_LA_Current_Num_Coded",
    src_1."LCI_INS_ACAD_NOTDIS_LA_Current_Num_Coded" AS "LCI_INS_ACAD_NOTDIS_LA_Current_Num_Coded",
    src_1."LCI_INS_AGEN_DIS_LA_Current_Num_Coded" AS "LCI_INS_AGEN_DIS_LA_Current_Num_Coded",
    src_1."LCI_INS_AGEN_NOTDIS_LA_Current_Num_Coded" AS "LCI_INS_AGEN_NOTDIS_LA_Current_Num_Coded",
    src_1."LCI_INS_ALEV_DIS_LA_Current_Num_Coded" AS "LCI_INS_ALEV_DIS_LA_Current_Num_Coded",
    src_1."LCI_INS_ALEV_NOTDIS_LA_Current_Num_Coded" AS "LCI_INS_ALEV_NOTDIS_LA_Current_Num_Coded",
    src_1."LCI_INS_TECHCERT_DIS_LA_Current_Num_Coded" AS "LCI_INS_TECHCERT_DIS_LA_Current_Num_Coded",
    src_1."LCI_INS_TECHCERT_NOTDIS_LA_Current_Num_Coded" AS "LCI_INS_TECHCERT_NOTDIS_LA_Current_Num_Coded",
    src_1."LCI_INS_TLEV_DIS_LA_Current_Num_Coded" AS "LCI_INS_TLEV_DIS_LA_Current_Num_Coded",
    src_1."LCI_INS_TLEV_NOTDIS_LA_Current_Num_Coded" AS "LCI_INS_TLEV_NOTDIS_LA_Current_Num_Coded",
    src_1."PROGEX_E_DIS_LA_Current_Num_Coded" AS "PROGEX_E_DIS_LA_Current_Num_Coded",
    src_1."PROGEX_E_LA_Current_Num_Coded" AS "PROGEX_E_LA_Current_Num_Coded",
    src_1."PROGEX_E_NOTDIS_LA_Current_Num_Coded" AS "PROGEX_E_NOTDIS_LA_Current_Num_Coded",
    src_1."PROGEX_M_DIS_LA_Current_Num_Coded" AS "PROGEX_M_DIS_LA_Current_Num_Coded",
    src_1."PROGEX_M_LA_Current_Num_Coded" AS "PROGEX_M_LA_Current_Num_Coded",
    src_1."PROGEX_M_NOTDIS_LA_Current_Num_Coded" AS "PROGEX_M_NOTDIS_LA_Current_Num_Coded",
    src_1."PT_RET_ASSESSED_ACAD_LA_Current_Pct_Coded" AS "PT_RET_ASSESSED_ACAD_LA_Current_Pct_Coded",
    src_1."PT_RET_ASSESSED_AGEN_LA_Current_Pct_Coded" AS "PT_RET_ASSESSED_AGEN_LA_Current_Pct_Coded",
    src_1."PT_RET_ASSESSED_ALEV_LA_Current_Pct_Coded" AS "PT_RET_ASSESSED_ALEV_LA_Current_Pct_Coded",
    src_1."PT_RET_ASSESSED_TECHCERT_LA_Current_Pct_Coded" AS "PT_RET_ASSESSED_TECHCERT_LA_Current_Pct_Coded",
    src_1."PT_RET_ASSESSED_TLEV_LA_Current_Pct_Coded" AS "PT_RET_ASSESSED_TLEV_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_23_LA_Previous2_Pct_Coded" AS "PT_RETAINED_ACAD_RET_23_LA_Previous2_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_24_LA_Previous_Pct_Coded" AS "PT_RETAINED_ACAD_RET_24_LA_Previous_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_LA_Current_Pct_Coded" AS "PT_RETAINED_ACAD_RET_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_NOTDIS_LA_Current_Pct_Coded" AS "PT_RETAINED_ACAD_RET_NOTDIS_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_23_LA_Previous2_Pct_Coded" AS "PT_RETAINED_AGEN_RET_23_LA_Previous2_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_24_LA_Previous_Pct_Coded" AS "PT_RETAINED_AGEN_RET_24_LA_Previous_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_DIS_LA_Current_Pct_Coded" AS "PT_RETAINED_AGEN_RET_DIS_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_LA_Current_Pct_Coded" AS "PT_RETAINED_AGEN_RET_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_NOTDIS_LA_Current_Pct_Coded" AS "PT_RETAINED_AGEN_RET_NOTDIS_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_23_LA_Previous2_Pct_Coded" AS "PT_RETAINED_ALEV_RET_23_LA_Previous2_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_24_LA_Previous_Pct_Coded" AS "PT_RETAINED_ALEV_RET_24_LA_Previous_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_DIS_LA_Current_Pct_Coded" AS "PT_RETAINED_ALEV_RET_DIS_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_LA_Current_Pct_Coded" AS "PT_RETAINED_ALEV_RET_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_NOTDIS_LA_Current_Pct_Coded" AS "PT_RETAINED_ALEV_RET_NOTDIS_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_23_LA_Previous2_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_23_LA_Previous2_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_24_LA_Previous_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_24_LA_Previous_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_DIS_LA_Current_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_DIS_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_LA_Current_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_NOTDIS_LA_Current_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_NOTDIS_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_23_LA_Previous2_Pct_Coded" AS "PT_RETAINED_TLEV_RET_23_LA_Previous2_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_24_LA_Previous_Pct_Coded" AS "PT_RETAINED_TLEV_RET_24_LA_Previous_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_DIS_LA_Current_Pct_Coded" AS "PT_RETAINED_TLEV_RET_DIS_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_LA_Current_Pct_Coded" AS "PT_RETAINED_TLEV_RET_LA_Current_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_NOTDIS_LA_Current_Pct_Coded" AS "PT_RETAINED_TLEV_RET_NOTDIS_LA_Current_Pct_Coded",
    src_1."PTAAB_2FAC_LA_Current_Pct_Coded" AS "PTAAB_2FAC_LA_Current_Pct_Coded",
    src_1."T_SCOPEEX_E_DIS_LA_Current_Num_Coded" AS "T_SCOPEEX_E_DIS_LA_Current_Num_Coded",
    src_1."T_SCOPEEX_E_NOTDIS_LA_Current_Num_Coded" AS "T_SCOPEEX_E_NOTDIS_LA_Current_Num_Coded",
    src_1."T_SCOPEEX_M_DIS_LA_Current_Num_Coded" AS "T_SCOPEEX_M_DIS_LA_Current_Num_Coded",
    src_1."T_SCOPEEX_M_NOTDIS_LA_Current_Num_Coded" AS "T_SCOPEEX_M_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPPE_ACAD_1618_23_LA_Previous2_Num_Coded" AS "TALLPPE_ACAD_1618_23_LA_Previous2_Num_Coded",
    src_1."TALLPPE_ACAD_1618_24_LA_Previous_Num_Coded" AS "TALLPPE_ACAD_1618_24_LA_Previous_Num_Coded",
    src_1."TALLPPE_ACAD_1618_DIS_LA_Current_Num_Coded" AS "TALLPPE_ACAD_1618_DIS_LA_Current_Num_Coded",
    src_1."TALLPPE_ACAD_1618_LA_Current_Num_Coded" AS "TALLPPE_ACAD_1618_LA_Current_Num_Coded",
    src_1."TALLPPE_ACAD_1618_NOTDIS_LA_Current_Num_Coded" AS "TALLPPE_ACAD_1618_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPPE_AGEN_23_LA_Previous2_Num_Coded" AS "TALLPPE_AGEN_23_LA_Previous2_Num_Coded",
    src_1."TALLPPE_AGEN_24_LA_Previous_Num_Coded" AS "TALLPPE_AGEN_24_LA_Previous_Num_Coded",
    src_1."TALLPPE_AGEN_DIS_LA_Current_Num_Coded" AS "TALLPPE_AGEN_DIS_LA_Current_Num_Coded",
    src_1."TALLPPE_AGEN_LA_Current_Num_Coded" AS "TALLPPE_AGEN_LA_Current_Num_Coded",
    src_1."TALLPPE_AGEN_NOTDIS_LA_Current_Num_Coded" AS "TALLPPE_AGEN_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPPE_ALEV_1618_23_LA_Previous2_Num_Coded" AS "TALLPPE_ALEV_1618_23_LA_Previous2_Num_Coded",
    src_1."TALLPPE_ALEV_1618_24_LA_Previous_Num_Coded" AS "TALLPPE_ALEV_1618_24_LA_Previous_Num_Coded",
    src_1."TALLPPE_ALEV_1618_DIS_LA_Current_Num_Coded" AS "TALLPPE_ALEV_1618_DIS_LA_Current_Num_Coded",
    src_1."TALLPPE_ALEV_1618_LA_Current_Num_Coded" AS "TALLPPE_ALEV_1618_LA_Current_Num_Coded",
    src_1."TALLPPE_ALEV_1618_NOTDIS_LA_Current_Num_Coded" AS "TALLPPE_ALEV_1618_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPPE_TECHCERT_23_LA_Previous2_Num_Coded" AS "TALLPPE_TECHCERT_23_LA_Previous2_Num_Coded",
    src_1."TALLPPE_TECHCERT_24_LA_Previous_Num_Coded" AS "TALLPPE_TECHCERT_24_LA_Previous_Num_Coded",
    src_1."TALLPPE_TECHCERT_DIS_LA_Current_Num_Coded" AS "TALLPPE_TECHCERT_DIS_LA_Current_Num_Coded",
    src_1."TALLPPE_TECHCERT_LA_Current_Num_Coded" AS "TALLPPE_TECHCERT_LA_Current_Num_Coded",
    src_1."TALLPPE_TECHCERT_NOTDIS_LA_Current_Num_Coded" AS "TALLPPE_TECHCERT_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPPE_TLEV_23_LA_Previous2_Num_Coded" AS "TALLPPE_TLEV_23_LA_Previous2_Num_Coded",
    src_1."TALLPPE_TLEV_24_LA_Previous_Num_Coded" AS "TALLPPE_TLEV_24_LA_Previous_Num_Coded",
    src_1."TALLPPE_TLEV_DIS_LA_Current_Num_Coded" AS "TALLPPE_TLEV_DIS_LA_Current_Num_Coded",
    src_1."TALLPPE_TLEV_LA_Current_Num_Coded" AS "TALLPPE_TLEV_LA_Current_Num_Coded",
    src_1."TALLPPE_TLEV_NOTDIS_LA_Current_Num_Coded" AS "TALLPPE_TLEV_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_ACAD_1618_23_LA_Previous2_Num_Coded" AS "TALLPPEGRD_ACAD_1618_23_LA_Previous2_Num_Coded",
    src_1."TALLPPEGRD_ACAD_1618_24_LA_Previous_Num_Coded" AS "TALLPPEGRD_ACAD_1618_24_LA_Previous_Num_Coded",
    src_1."TALLPPEGRD_ACAD_1618_LA_Current_Num_Coded" AS "TALLPPEGRD_ACAD_1618_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_ACAD_DIS_LA_Current_Num_Coded" AS "TALLPPEGRD_ACAD_DIS_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_ACAD_NOTDIS_LA_Current_Num_Coded" AS "TALLPPEGRD_ACAD_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_AGEN_23_LA_Previous2_Num_Coded" AS "TALLPPEGRD_AGEN_23_LA_Previous2_Num_Coded",
    src_1."TALLPPEGRD_AGEN_24_LA_Previous_Num_Coded" AS "TALLPPEGRD_AGEN_24_LA_Previous_Num_Coded",
    src_1."TALLPPEGRD_AGEN_DIS_LA_Current_Num_Coded" AS "TALLPPEGRD_AGEN_DIS_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_AGEN_LA_Current_Num_Coded" AS "TALLPPEGRD_AGEN_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_AGEN_NOTDIS_LA_Current_Num_Coded" AS "TALLPPEGRD_AGEN_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_ALEV_1618_23_LA_Previous2_Num_Coded" AS "TALLPPEGRD_ALEV_1618_23_LA_Previous2_Num_Coded",
    src_1."TALLPPEGRD_ALEV_1618_24_LA_Previous_Num_Coded" AS "TALLPPEGRD_ALEV_1618_24_LA_Previous_Num_Coded",
    src_1."TALLPPEGRD_ALEV_1618_LA_Current_Num_Coded" AS "TALLPPEGRD_ALEV_1618_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_ALEV_DIS_LA_Current_Num_Coded" AS "TALLPPEGRD_ALEV_DIS_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_ALEV_NOTDIS_LA_Current_Num_Coded" AS "TALLPPEGRD_ALEV_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_TECHCERT_23_LA_Previous2_Num_Coded" AS "TALLPPEGRD_TECHCERT_23_LA_Previous2_Num_Coded",
    src_1."TALLPPEGRD_TECHCERT_24_LA_Previous_Num_Coded" AS "TALLPPEGRD_TECHCERT_24_LA_Previous_Num_Coded",
    src_1."TALLPPEGRD_TECHCERT_DIS_LA_Current_Num_Coded" AS "TALLPPEGRD_TECHCERT_DIS_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_TECHCERT_LA_Current_Num_Coded" AS "TALLPPEGRD_TECHCERT_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_TECHCERT_NOTDIS_LA_Current_Num_Coded" AS "TALLPPEGRD_TECHCERT_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_TLEV_23_LA_Previous2_Num_Coded" AS "TALLPPEGRD_TLEV_23_LA_Previous2_Num_Coded",
    src_1."TALLPPEGRD_TLEV_24_LA_Previous_Num_Coded" AS "TALLPPEGRD_TLEV_24_LA_Previous_Num_Coded",
    src_1."TALLPPEGRD_TLEV_DIS_LA_Current_Num_Coded" AS "TALLPPEGRD_TLEV_DIS_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_TLEV_LA_Current_Num_Coded" AS "TALLPPEGRD_TLEV_LA_Current_Num_Coded",
    src_1."TALLPPEGRD_TLEV_NOTDIS_LA_Current_Num_Coded" AS "TALLPPEGRD_TLEV_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPUP_1618_DIS_LA_Current_Num_Coded" AS "TALLPUP_1618_DIS_LA_Current_Num_Coded",
    src_1."TALLPUP_1618_NOTDIS_LA_Current_Num_Coded" AS "TALLPUP_1618_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPUP_ACAD_1618_DIS_LA_Current_Num_Coded" AS "TALLPUP_ACAD_1618_DIS_LA_Current_Num_Coded",
    src_1."TALLPUP_ACAD_1618_LA_Current_Num_Coded" AS "TALLPUP_ACAD_1618_LA_Current_Num_Coded",
    src_1."TALLPUP_ACAD_1618_NOTDIS_LA_Current_Num_Coded" AS "TALLPUP_ACAD_1618_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPUP_AGEN_DIS_LA_Current_Num_Coded" AS "TALLPUP_AGEN_DIS_LA_Current_Num_Coded",
    src_1."TALLPUP_AGEN_NOTDIS_LA_Current_Num_Coded" AS "TALLPUP_AGEN_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPUP_ALEV_1618_DIS_LA_Current_Num_Coded" AS "TALLPUP_ALEV_1618_DIS_LA_Current_Num_Coded",
    src_1."TALLPUP_ALEV_1618_NOTDIS_LA_Current_Num_Coded" AS "TALLPUP_ALEV_1618_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPUP_TECHCERT_DIS_LA_Current_Num_Coded" AS "TALLPUP_TECHCERT_DIS_LA_Current_Num_Coded",
    src_1."TALLPUP_TECHCERT_NOTDIS_LA_Current_Num_Coded" AS "TALLPUP_TECHCERT_NOTDIS_LA_Current_Num_Coded",
    src_1."TALLPUP_TLEV_DIS_LA_Current_Num_Coded" AS "TALLPUP_TLEV_DIS_LA_Current_Num_Coded",
    src_1."TALLPUP_TLEV_NOTDIS_LA_Current_Num_Coded" AS "TALLPUP_TLEV_NOTDIS_LA_Current_Num_Coded",
    src_1."TB3PTSE_GRD_LA_Current_Num_Coded" AS "TB3PTSE_GRD_LA_Current_Num_Coded",
    src_1."TB3PTSE_LA_Current_Num_Coded" AS "TB3PTSE_LA_Current_Num_Coded",
    src_1."UCI_INS_ACAD_DIS_LA_Current_Num_Coded" AS "UCI_INS_ACAD_DIS_LA_Current_Num_Coded",
    src_1."UCI_INS_ACAD_NOTDIS_LA_Current_Num_Coded" AS "UCI_INS_ACAD_NOTDIS_LA_Current_Num_Coded",
    src_1."UCI_INS_AGEN_DIS_LA_Current_Num_Coded" AS "UCI_INS_AGEN_DIS_LA_Current_Num_Coded",
    src_1."UCI_INS_AGEN_NOTDIS_LA_Current_Num_Coded" AS "UCI_INS_AGEN_NOTDIS_LA_Current_Num_Coded",
    src_1."UCI_INS_ALEV_DIS_LA_Current_Num_Coded" AS "UCI_INS_ALEV_DIS_LA_Current_Num_Coded",
    src_1."UCI_INS_ALEV_NOTDIS_LA_Current_Num_Coded" AS "UCI_INS_ALEV_NOTDIS_LA_Current_Num_Coded",
    src_1."UCI_INS_TECHCERT_DIS_LA_Current_Num_Coded" AS "UCI_INS_TECHCERT_DIS_LA_Current_Num_Coded",
    src_1."UCI_INS_TECHCERT_NOTDIS_LA_Current_Num_Coded" AS "UCI_INS_TECHCERT_NOTDIS_LA_Current_Num_Coded",
    src_1."UCI_INS_TLEV_DIS_LA_Current_Num_Coded" AS "UCI_INS_TLEV_DIS_LA_Current_Num_Coded",
    src_1."UCI_INS_TLEV_NOTDIS_LA_Current_Num_Coded" AS "UCI_INS_TLEV_NOTDIS_LA_Current_Num_Coded",
    src_1."VA_INS_ACAD_DIS_LA_Current_Num_Coded" AS "VA_INS_ACAD_DIS_LA_Current_Num_Coded",
    src_1."VA_INS_ACAD_NOTDIS_LA_Current_Num_Coded" AS "VA_INS_ACAD_NOTDIS_LA_Current_Num_Coded",
    src_1."VA_INS_AGEN_DIS_LA_Current_Num_Coded" AS "VA_INS_AGEN_DIS_LA_Current_Num_Coded",
    src_1."VA_INS_AGEN_NOTDIS_LA_Current_Num_Coded" AS "VA_INS_AGEN_NOTDIS_LA_Current_Num_Coded",
    src_1."VA_INS_ALEV_DIS_LA_Current_Num_Coded" AS "VA_INS_ALEV_DIS_LA_Current_Num_Coded",
    src_1."VA_INS_ALEV_NOTDIS_LA_Current_Num_Coded" AS "VA_INS_ALEV_NOTDIS_LA_Current_Num_Coded",
    src_1."VA_INS_TLEV_DIS_LA_Current_Num_Coded" AS "VA_INS_TLEV_DIS_LA_Current_Num_Coded",
    src_1."VA_INS_TLEV_NOTDIS_LA_Current_Num_Coded" AS "VA_INS_TLEV_NOTDIS_LA_Current_Num_Coded"
FROM all_ids a
LEFT JOIN src_1 ON src_1."Id" = a."Id"
;
