-- AUTO-GENERATED MATERIALIZED VIEW: v_england_ks5_performance

DROP MATERIALIZED VIEW IF EXISTS v_england_ks5_performance;

CREATE MATERIALIZED VIEW v_england_ks5_performance AS
WITH
src_1 AS (
    SELECT
        t."geographic_level" AS "Id",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "ENTRIES_ALEV_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."english_progress_entries_percent"::text END) AS "ENTRY_PER_E_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."maths_progress_entries_percent"::text END) AS "ENTRY_PER_M_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."level_3_maths_percent"::text END) AS "L3M_PER_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_ACAD_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_ACAD_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_AGEN_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_AGEN_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_ALEV_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_ALEV_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_TECHCERT_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_TECHCERT_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_TLEV_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_lower_ci"::text END) AS "LCI_INS_TLEV_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."english_progress"::text END) AS "PROGEX_E_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."english_progress"::text END) AS "PROGEX_E_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."english_progress"::text END) AS "PROGEX_E_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."maths_progress"::text END) AS "PROGEX_M_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."maths_progress"::text END) AS "PROGEX_M_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."maths_progress"::text END) AS "PROGEX_M_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_ACAD_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_ACAD_23_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_AGEN_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_AGEN_23_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_ALEV_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_ALEV_23_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_TECHCERT_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_TLEV_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_TLEV_23_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_23_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_24_Eng_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_DIS_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_ACAD_RET_NOTDIS_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_23_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_24_Eng_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_DIS_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_AGEN_RET_NOTDIS_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_23_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_24_Eng_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_DIS_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_ALEV_RET_NOTDIS_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_23_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_24_Eng_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_DIS_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_TECHCERT_RET_NOTDIS_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_23_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_24_Eng_Previous_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_DIS_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_percent"::text END) AS "PT_RETAINED_TLEV_RET_NOTDIS_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aab_percent"::text END) AS "PTAAB_2FAC_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."english_progress_inscope_count"::text END) AS "T_SCOPEEX_E_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."english_progress_inscope_count"::text END) AS "T_SCOPEEX_E_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."maths_progress_inscope_count"::text END) AS "T_SCOPEEX_M_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'E/M measures' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."maths_progress_inscope_count"::text END) AS "T_SCOPEEX_M_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_ACAD_1618_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_AGEN_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_ALEV_1618_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_TECHCERT_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry"::text END) AS "TALLPPE_TLEV_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_ACAD_1618_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_ACAD_1618_Eng_Previous2",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_ACAD_1618_Eng_Previous",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_ACAD_DIS_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_ACAD_NOTDIS_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_AGEN_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_AGEN_Eng_Previous2",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_AGEN_Eng_Previous",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_AGEN_DIS_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_AGEN_NOTDIS_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_ALEV_1618_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_ALEV_1618_Eng_Previous2",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_ALEV_1618_Eng_Previous",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_ALEV_DIS_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_ALEV_NOTDIS_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_TECHCERT_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_TECHCERT_Eng_Previous2",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_TECHCERT_Eng_Previous",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_TECHCERT_DIS_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_TECHCERT_NOTDIS_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_TLEV_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_TLEV_Eng_Previous2",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_TLEV_Eng_Previous",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_TLEV_DIS_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_grade" END) AS "TALLPPEGRD_TLEV_NOTDIS_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."end1618_student_count"::text END) AS "TALLPUP_1618_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."end1618_student_count"::text END) AS "TALLPUP_1618_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ACAD_1618_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ACAD_1618_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ACAD_1618_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ACAD_1618_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ACAD_1618_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_AGEN_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_AGEN_Eng_Previous2_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_AGEN_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_AGEN_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_AGEN_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ALEV_1618_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ALEV_1618_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TECHCERT_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TECHCERT_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TLEV_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TLEV_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."best_three_alevels_aps"::text END) AS "TB3PTSE_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."best_three_alevels_grade" END) AS "TB3PTSE_GRD_Eng_Current",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_ACAD_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_ACAD_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_AGEN_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_AGEN_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_ALEV_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_ALEV_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_TECHCERT_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_TECHCERT_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_TLEV_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added_upper_ci"::text END) AS "UCI_INS_TLEV_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_ACAD_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_ACAD_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Academic' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_ACAD_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_AGEN_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_AGEN_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Applied general' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_AGEN_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_ALEV_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_ALEV_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_ALEV_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_TECHCERT_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_TLEV_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_TLEV_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_TLEV_NOTDIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202223' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."retained_assessed_percent"::text END) AS "PT_RET_ASSESSED_TECHCERT_23_Eng_Previous2_Pct_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ALEV_1618_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TECHCERT_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202324' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TLEV_Eng_Previous_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'A level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_ALEV_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TECHCERT_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Total' AND t."exam_cohort" = 'Tech level' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."aps_per_entry_student_count"::text END) AS "TALLPUP_TLEV_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_TECHCERT_DIS_Eng_Current_Num_Coded",
        MAX(CASE WHEN t."disadvantage_status" = 'Not disadvantaged' AND t."exam_cohort" = 'Technical certificate' AND t."time_period" = '202425' AND t."geographic_level" = 'National' AND t."establishment_type" = 'All state-funded schools and colleges' THEN t."value_added"::text END) AS "VA_INS_TECHCERT_NOTDIS_Eng_Current_Num_Coded"
    FROM t_national_performance_89ee26b9ac t
    GROUP BY t."geographic_level"
)
,
src_2 AS (
    SELECT
        t."geographic_level" AS "Id",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Above Average' AND t."exam_cohort" = 'A level' THEN t."percent_providers"::text END) AS "ProgBand_Alev_Band1_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Above Average' AND t."exam_cohort" = 'A level' THEN t."percent_providers"::text END) AS "ProgBand_Alev_Band2_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Average' AND t."exam_cohort" = 'A level' THEN t."percent_providers"::text END) AS "ProgBand_Alev_Band3_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Below Average' AND t."exam_cohort" = 'A level' THEN t."percent_providers"::text END) AS "ProgBand_Alev_Band4_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Below Average' AND t."exam_cohort" = 'A level' THEN t."percent_providers"::text END) AS "ProgBand_Alev_Band5_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Above Average' AND t."exam_cohort" = 'A level' THEN t."banding_description" END) AS "ProgBand_Alev_Band1_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Above Average' AND t."exam_cohort" = 'A level' THEN t."banding_description" END) AS "ProgBand_Alev_Band2_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Average' AND t."exam_cohort" = 'A level' THEN t."banding_description" END) AS "ProgBand_Alev_Band3_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Below Average' AND t."exam_cohort" = 'A level' THEN t."banding_description" END) AS "ProgBand_Alev_Band4_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Below Average' AND t."exam_cohort" = 'A level' THEN t."banding_description" END) AS "ProgBand_Alev_Band5_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Above Average' AND t."exam_cohort" = 'Academic' THEN t."percent_providers"::text END) AS "ProgBand_Acad_Band1_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Above Average' AND t."exam_cohort" = 'Academic' THEN t."percent_providers"::text END) AS "ProgBand_Acad_Band2_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Average' AND t."exam_cohort" = 'Academic' THEN t."percent_providers"::text END) AS "ProgBand_Acad_Band3_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Below Average' AND t."exam_cohort" = 'Academic' THEN t."percent_providers"::text END) AS "ProgBand_Acad_Band4_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Below Average' AND t."exam_cohort" = 'Academic' THEN t."percent_providers"::text END) AS "ProgBand_Acad_Band5_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Above Average' AND t."exam_cohort" = 'Academic' THEN t."banding_description" END) AS "ProgBand_Acad_Band1_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Above Average' AND t."exam_cohort" = 'Academic' THEN t."banding_description" END) AS "ProgBand_Acad_Band2_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Average' AND t."exam_cohort" = 'Academic' THEN t."banding_description" END) AS "ProgBand_Acad_Band3_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Below Average' AND t."exam_cohort" = 'Academic' THEN t."banding_description" END) AS "ProgBand_Acad_Band4_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Below Average' AND t."exam_cohort" = 'Academic' THEN t."banding_description" END) AS "ProgBand_Acad_Band5_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Above Average' AND t."exam_cohort" = 'Applied general' THEN t."percent_providers"::text END) AS "ProgBand_Agen_Band1_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Above Average' AND t."exam_cohort" = 'Applied general' THEN t."percent_providers"::text END) AS "ProgBand_Agen_Band2_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Average' AND t."exam_cohort" = 'Applied general' THEN t."percent_providers"::text END) AS "ProgBand_Agen_Band3_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Below Average' AND t."exam_cohort" = 'Applied general' THEN t."percent_providers"::text END) AS "ProgBand_Agen_Band4_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Below Average' AND t."exam_cohort" = 'Applied general' THEN t."percent_providers"::text END) AS "ProgBand_Agen_Band5_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Above Average' AND t."exam_cohort" = 'Applied general' THEN t."banding_description" END) AS "ProgBand_Agen_Band1_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Above Average' AND t."exam_cohort" = 'Applied general' THEN t."banding_description" END) AS "ProgBand_Agen_Band2_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Average' AND t."exam_cohort" = 'Applied general' THEN t."banding_description" END) AS "ProgBand_Agen_Band3_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Below Average' AND t."exam_cohort" = 'Applied general' THEN t."banding_description" END) AS "ProgBand_Agen_Band4_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Below Average' AND t."exam_cohort" = 'Applied general' THEN t."banding_description" END) AS "ProgBand_Agen_Band5_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Above Average' AND t."exam_cohort" = 'Tech level' THEN t."percent_providers"::text END) AS "ProgBand_Tlev_Band1_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Above Average' AND t."exam_cohort" = 'Tech level' THEN t."percent_providers"::text END) AS "ProgBand_Tlev_Band2_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Average' AND t."exam_cohort" = 'Tech level' THEN t."percent_providers"::text END) AS "ProgBand_Tlev_Band3_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Below Average' AND t."exam_cohort" = 'Tech level' THEN t."percent_providers"::text END) AS "ProgBand_Tlev_Band4_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Below Average' AND t."exam_cohort" = 'Tech level' THEN t."percent_providers"::text END) AS "ProgBand_Tlev_Band5_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Above Average' AND t."exam_cohort" = 'Tech level' THEN t."banding_description" END) AS "ProgBand_Tlev_Band1_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Above Average' AND t."exam_cohort" = 'Tech level' THEN t."banding_description" END) AS "ProgBand_Tlev_Band2_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Average' AND t."exam_cohort" = 'Tech level' THEN t."banding_description" END) AS "ProgBand_Tlev_Band3_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Below Average' AND t."exam_cohort" = 'Tech level' THEN t."banding_description" END) AS "ProgBand_Tlev_Band4_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Below Average' AND t."exam_cohort" = 'Tech level' THEN t."banding_description" END) AS "ProgBand_Tlev_Band5_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Above Average' AND t."exam_cohort" = 'Technical certificate' THEN t."percent_providers"::text END) AS "ProgBand_Techcert_Band1_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Above Average' AND t."exam_cohort" = 'Technical certificate' THEN t."percent_providers"::text END) AS "ProgBand_Techcert_Band2_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Average' AND t."exam_cohort" = 'Technical certificate' THEN t."percent_providers"::text END) AS "ProgBand_Techcert_Band3_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Below Average' AND t."exam_cohort" = 'Technical certificate' THEN t."percent_providers"::text END) AS "ProgBand_Techcert_Band4_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Below Average' AND t."exam_cohort" = 'Technical certificate' THEN t."percent_providers"::text END) AS "ProgBand_Techcert_Band5_Eng_Current_Pct_Coded",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Above Average' AND t."exam_cohort" = 'Technical certificate' THEN t."banding_description" END) AS "ProgBand_Techcert_Band1_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Above Average' AND t."exam_cohort" = 'Technical certificate' THEN t."banding_description" END) AS "ProgBand_Techcert_Band2_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Average' AND t."exam_cohort" = 'Technical certificate' THEN t."banding_description" END) AS "ProgBand_Techcert_Band3_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Below Average' AND t."exam_cohort" = 'Technical certificate' THEN t."banding_description" END) AS "ProgBand_Techcert_Band4_Eng_Current_Desc",
        MAX(CASE WHEN t."geographic_level" = 'National' AND t."time_period" = '202425' AND t."progress_banding" = 'Well Below Average' AND t."exam_cohort" = 'Technical certificate' THEN t."banding_description" END) AS "ProgBand_Techcert_Band5_Eng_Current_Desc"
    FROM t_banding_information__c7c95db9aa t
    GROUP BY t."geographic_level"
)
,
all_ids AS (
    SELECT "Id" FROM src_1
    UNION SELECT "Id" FROM src_2
)

SELECT
    a."Id" AS "Id",
    src_1."ENTRIES_ALEV_DIS_Eng_Current_Num_Coded" AS "ENTRIES_ALEV_DIS_Eng_Current_Num_Coded",
    src_1."ENTRY_PER_E_Eng_Current_Pct_Coded" AS "ENTRY_PER_E_Eng_Current_Pct_Coded",
    src_1."ENTRY_PER_M_Eng_Current_Pct_Coded" AS "ENTRY_PER_M_Eng_Current_Pct_Coded",
    src_1."L3M_PER_Eng_Current_Pct_Coded" AS "L3M_PER_Eng_Current_Pct_Coded",
    src_1."LCI_INS_ACAD_DIS_Eng_Current_Num_Coded" AS "LCI_INS_ACAD_DIS_Eng_Current_Num_Coded",
    src_1."LCI_INS_ACAD_NOTDIS_Eng_Current_Num_Coded" AS "LCI_INS_ACAD_NOTDIS_Eng_Current_Num_Coded",
    src_1."LCI_INS_AGEN_DIS_Eng_Current_Num_Coded" AS "LCI_INS_AGEN_DIS_Eng_Current_Num_Coded",
    src_1."LCI_INS_AGEN_NOTDIS_Eng_Current_Num_Coded" AS "LCI_INS_AGEN_NOTDIS_Eng_Current_Num_Coded",
    src_1."LCI_INS_ALEV_DIS_Eng_Current_Num_Coded" AS "LCI_INS_ALEV_DIS_Eng_Current_Num_Coded",
    src_1."LCI_INS_ALEV_NOTDIS_Eng_Current_Num_Coded" AS "LCI_INS_ALEV_NOTDIS_Eng_Current_Num_Coded",
    src_1."LCI_INS_TECHCERT_DIS_Eng_Current_Num_Coded" AS "LCI_INS_TECHCERT_DIS_Eng_Current_Num_Coded",
    src_1."LCI_INS_TECHCERT_NOTDIS_Eng_Current_Num_Coded" AS "LCI_INS_TECHCERT_NOTDIS_Eng_Current_Num_Coded",
    src_1."LCI_INS_TLEV_DIS_Eng_Current_Num_Coded" AS "LCI_INS_TLEV_DIS_Eng_Current_Num_Coded",
    src_1."LCI_INS_TLEV_NOTDIS_Eng_Current_Num_Coded" AS "LCI_INS_TLEV_NOTDIS_Eng_Current_Num_Coded",
    src_2."ProgBand_Acad_Band1_Eng_Current_Desc" AS "ProgBand_Acad_Band1_Eng_Current_Desc",
    src_2."ProgBand_Acad_Band1_Eng_Current_Pct_Coded" AS "ProgBand_Acad_Band1_Eng_Current_Pct_Coded",
    src_2."ProgBand_Acad_Band2_Eng_Current_Desc" AS "ProgBand_Acad_Band2_Eng_Current_Desc",
    src_2."ProgBand_Acad_Band2_Eng_Current_Pct_Coded" AS "ProgBand_Acad_Band2_Eng_Current_Pct_Coded",
    src_2."ProgBand_Acad_Band3_Eng_Current_Desc" AS "ProgBand_Acad_Band3_Eng_Current_Desc",
    src_2."ProgBand_Acad_Band3_Eng_Current_Pct_Coded" AS "ProgBand_Acad_Band3_Eng_Current_Pct_Coded",
    src_2."ProgBand_Acad_Band4_Eng_Current_Desc" AS "ProgBand_Acad_Band4_Eng_Current_Desc",
    src_2."ProgBand_Acad_Band4_Eng_Current_Pct_Coded" AS "ProgBand_Acad_Band4_Eng_Current_Pct_Coded",
    src_2."ProgBand_Acad_Band5_Eng_Current_Desc" AS "ProgBand_Acad_Band5_Eng_Current_Desc",
    src_2."ProgBand_Acad_Band5_Eng_Current_Pct_Coded" AS "ProgBand_Acad_Band5_Eng_Current_Pct_Coded",
    src_2."ProgBand_Agen_Band1_Eng_Current_Desc" AS "ProgBand_Agen_Band1_Eng_Current_Desc",
    src_2."ProgBand_Agen_Band1_Eng_Current_Pct_Coded" AS "ProgBand_Agen_Band1_Eng_Current_Pct_Coded",
    src_2."ProgBand_Agen_Band2_Eng_Current_Desc" AS "ProgBand_Agen_Band2_Eng_Current_Desc",
    src_2."ProgBand_Agen_Band2_Eng_Current_Pct_Coded" AS "ProgBand_Agen_Band2_Eng_Current_Pct_Coded",
    src_2."ProgBand_Agen_Band3_Eng_Current_Desc" AS "ProgBand_Agen_Band3_Eng_Current_Desc",
    src_2."ProgBand_Agen_Band3_Eng_Current_Pct_Coded" AS "ProgBand_Agen_Band3_Eng_Current_Pct_Coded",
    src_2."ProgBand_Agen_Band4_Eng_Current_Desc" AS "ProgBand_Agen_Band4_Eng_Current_Desc",
    src_2."ProgBand_Agen_Band4_Eng_Current_Pct_Coded" AS "ProgBand_Agen_Band4_Eng_Current_Pct_Coded",
    src_2."ProgBand_Agen_Band5_Eng_Current_Desc" AS "ProgBand_Agen_Band5_Eng_Current_Desc",
    src_2."ProgBand_Agen_Band5_Eng_Current_Pct_Coded" AS "ProgBand_Agen_Band5_Eng_Current_Pct_Coded",
    src_2."ProgBand_Alev_Band1_Eng_Current_Desc" AS "ProgBand_Alev_Band1_Eng_Current_Desc",
    src_2."ProgBand_Alev_Band1_Eng_Current_Pct_Coded" AS "ProgBand_Alev_Band1_Eng_Current_Pct_Coded",
    src_2."ProgBand_Alev_Band2_Eng_Current_Desc" AS "ProgBand_Alev_Band2_Eng_Current_Desc",
    src_2."ProgBand_Alev_Band2_Eng_Current_Pct_Coded" AS "ProgBand_Alev_Band2_Eng_Current_Pct_Coded",
    src_2."ProgBand_Alev_Band3_Eng_Current_Desc" AS "ProgBand_Alev_Band3_Eng_Current_Desc",
    src_2."ProgBand_Alev_Band3_Eng_Current_Pct_Coded" AS "ProgBand_Alev_Band3_Eng_Current_Pct_Coded",
    src_2."ProgBand_Alev_Band4_Eng_Current_Desc" AS "ProgBand_Alev_Band4_Eng_Current_Desc",
    src_2."ProgBand_Alev_Band4_Eng_Current_Pct_Coded" AS "ProgBand_Alev_Band4_Eng_Current_Pct_Coded",
    src_2."ProgBand_Alev_Band5_Eng_Current_Desc" AS "ProgBand_Alev_Band5_Eng_Current_Desc",
    src_2."ProgBand_Alev_Band5_Eng_Current_Pct_Coded" AS "ProgBand_Alev_Band5_Eng_Current_Pct_Coded",
    src_2."ProgBand_Techcert_Band1_Eng_Current_Desc" AS "ProgBand_Techcert_Band1_Eng_Current_Desc",
    src_2."ProgBand_Techcert_Band1_Eng_Current_Pct_Coded" AS "ProgBand_Techcert_Band1_Eng_Current_Pct_Coded",
    src_2."ProgBand_Techcert_Band2_Eng_Current_Desc" AS "ProgBand_Techcert_Band2_Eng_Current_Desc",
    src_2."ProgBand_Techcert_Band2_Eng_Current_Pct_Coded" AS "ProgBand_Techcert_Band2_Eng_Current_Pct_Coded",
    src_2."ProgBand_Techcert_Band3_Eng_Current_Desc" AS "ProgBand_Techcert_Band3_Eng_Current_Desc",
    src_2."ProgBand_Techcert_Band3_Eng_Current_Pct_Coded" AS "ProgBand_Techcert_Band3_Eng_Current_Pct_Coded",
    src_2."ProgBand_Techcert_Band4_Eng_Current_Desc" AS "ProgBand_Techcert_Band4_Eng_Current_Desc",
    src_2."ProgBand_Techcert_Band4_Eng_Current_Pct_Coded" AS "ProgBand_Techcert_Band4_Eng_Current_Pct_Coded",
    src_2."ProgBand_Techcert_Band5_Eng_Current_Desc" AS "ProgBand_Techcert_Band5_Eng_Current_Desc",
    src_2."ProgBand_Techcert_Band5_Eng_Current_Pct_Coded" AS "ProgBand_Techcert_Band5_Eng_Current_Pct_Coded",
    src_2."ProgBand_Tlev_Band1_Eng_Current_Desc" AS "ProgBand_Tlev_Band1_Eng_Current_Desc",
    src_2."ProgBand_Tlev_Band1_Eng_Current_Pct_Coded" AS "ProgBand_Tlev_Band1_Eng_Current_Pct_Coded",
    src_2."ProgBand_Tlev_Band2_Eng_Current_Desc" AS "ProgBand_Tlev_Band2_Eng_Current_Desc",
    src_2."ProgBand_Tlev_Band2_Eng_Current_Pct_Coded" AS "ProgBand_Tlev_Band2_Eng_Current_Pct_Coded",
    src_2."ProgBand_Tlev_Band3_Eng_Current_Desc" AS "ProgBand_Tlev_Band3_Eng_Current_Desc",
    src_2."ProgBand_Tlev_Band3_Eng_Current_Pct_Coded" AS "ProgBand_Tlev_Band3_Eng_Current_Pct_Coded",
    src_2."ProgBand_Tlev_Band4_Eng_Current_Desc" AS "ProgBand_Tlev_Band4_Eng_Current_Desc",
    src_2."ProgBand_Tlev_Band4_Eng_Current_Pct_Coded" AS "ProgBand_Tlev_Band4_Eng_Current_Pct_Coded",
    src_2."ProgBand_Tlev_Band5_Eng_Current_Desc" AS "ProgBand_Tlev_Band5_Eng_Current_Desc",
    src_2."ProgBand_Tlev_Band5_Eng_Current_Pct_Coded" AS "ProgBand_Tlev_Band5_Eng_Current_Pct_Coded",
    src_1."PROGEX_E_DIS_Eng_Current_Num_Coded" AS "PROGEX_E_DIS_Eng_Current_Num_Coded",
    src_1."PROGEX_E_Eng_Current_Num_Coded" AS "PROGEX_E_Eng_Current_Num_Coded",
    src_1."PROGEX_E_NOTDIS_Eng_Current_Num_Coded" AS "PROGEX_E_NOTDIS_Eng_Current_Num_Coded",
    src_1."PROGEX_M_DIS_Eng_Current_Num_Coded" AS "PROGEX_M_DIS_Eng_Current_Num_Coded",
    src_1."PROGEX_M_Eng_Current_Num_Coded" AS "PROGEX_M_Eng_Current_Num_Coded",
    src_1."PROGEX_M_NOTDIS_Eng_Current_Num_Coded" AS "PROGEX_M_NOTDIS_Eng_Current_Num_Coded",
    src_1."PT_RET_ASSESSED_ACAD_23_Eng_Previous2_Pct_Coded" AS "PT_RET_ASSESSED_ACAD_23_Eng_Previous2_Pct_Coded",
    src_1."PT_RET_ASSESSED_ACAD_Eng_Current_Pct_Coded" AS "PT_RET_ASSESSED_ACAD_Eng_Current_Pct_Coded",
    src_1."PT_RET_ASSESSED_AGEN_23_Eng_Previous2_Pct_Coded" AS "PT_RET_ASSESSED_AGEN_23_Eng_Previous2_Pct_Coded",
    src_1."PT_RET_ASSESSED_AGEN_Eng_Current_Pct_Coded" AS "PT_RET_ASSESSED_AGEN_Eng_Current_Pct_Coded",
    src_1."PT_RET_ASSESSED_ALEV_23_Eng_Previous2_Pct_Coded" AS "PT_RET_ASSESSED_ALEV_23_Eng_Previous2_Pct_Coded",
    src_1."PT_RET_ASSESSED_ALEV_Eng_Current_Pct_Coded" AS "PT_RET_ASSESSED_ALEV_Eng_Current_Pct_Coded",
    src_1."PT_RET_ASSESSED_TECHCERT_23_Eng_Previous2_Pct_Coded" AS "PT_RET_ASSESSED_TECHCERT_23_Eng_Previous2_Pct_Coded",
    src_1."PT_RET_ASSESSED_TECHCERT_Eng_Current_Pct_Coded" AS "PT_RET_ASSESSED_TECHCERT_Eng_Current_Pct_Coded",
    src_1."PT_RET_ASSESSED_TLEV_23_Eng_Previous2_Pct_Coded" AS "PT_RET_ASSESSED_TLEV_23_Eng_Previous2_Pct_Coded",
    src_1."PT_RET_ASSESSED_TLEV_Eng_Current_Pct_Coded" AS "PT_RET_ASSESSED_TLEV_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_23_Eng_Previous2_Pct_Coded" AS "PT_RETAINED_ACAD_RET_23_Eng_Previous2_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_24_Eng_Previous_Pct_Coded" AS "PT_RETAINED_ACAD_RET_24_Eng_Previous_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_DIS_Eng_Current_Pct_Coded" AS "PT_RETAINED_ACAD_RET_DIS_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_Eng_Current_Pct_Coded" AS "PT_RETAINED_ACAD_RET_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_ACAD_RET_NOTDIS_Eng_Current_Pct_Coded" AS "PT_RETAINED_ACAD_RET_NOTDIS_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_23_Eng_Previous2_Pct_Coded" AS "PT_RETAINED_AGEN_RET_23_Eng_Previous2_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_24_Eng_Previous_Pct_Coded" AS "PT_RETAINED_AGEN_RET_24_Eng_Previous_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_DIS_Eng_Current_Pct_Coded" AS "PT_RETAINED_AGEN_RET_DIS_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_Eng_Current_Pct_Coded" AS "PT_RETAINED_AGEN_RET_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_AGEN_RET_NOTDIS_Eng_Current_Pct_Coded" AS "PT_RETAINED_AGEN_RET_NOTDIS_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_23_Eng_Previous2_Pct_Coded" AS "PT_RETAINED_ALEV_RET_23_Eng_Previous2_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_24_Eng_Previous_Pct_Coded" AS "PT_RETAINED_ALEV_RET_24_Eng_Previous_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_DIS_Eng_Current_Pct_Coded" AS "PT_RETAINED_ALEV_RET_DIS_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_Eng_Current_Pct_Coded" AS "PT_RETAINED_ALEV_RET_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_ALEV_RET_NOTDIS_Eng_Current_Pct_Coded" AS "PT_RETAINED_ALEV_RET_NOTDIS_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_23_Eng_Previous2_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_23_Eng_Previous2_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_24_Eng_Previous_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_24_Eng_Previous_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_DIS_Eng_Current_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_DIS_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_Eng_Current_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_TECHCERT_RET_NOTDIS_Eng_Current_Pct_Coded" AS "PT_RETAINED_TECHCERT_RET_NOTDIS_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_23_Eng_Previous2_Pct_Coded" AS "PT_RETAINED_TLEV_RET_23_Eng_Previous2_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_24_Eng_Previous_Pct_Coded" AS "PT_RETAINED_TLEV_RET_24_Eng_Previous_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_DIS_Eng_Current_Pct_Coded" AS "PT_RETAINED_TLEV_RET_DIS_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_Eng_Current_Pct_Coded" AS "PT_RETAINED_TLEV_RET_Eng_Current_Pct_Coded",
    src_1."PT_RETAINED_TLEV_RET_NOTDIS_Eng_Current_Pct_Coded" AS "PT_RETAINED_TLEV_RET_NOTDIS_Eng_Current_Pct_Coded",
    src_1."PTAAB_2FAC_Eng_Current_Pct_Coded" AS "PTAAB_2FAC_Eng_Current_Pct_Coded",
    src_1."T_SCOPEEX_E_DIS_Eng_Current_Num_Coded" AS "T_SCOPEEX_E_DIS_Eng_Current_Num_Coded",
    src_1."T_SCOPEEX_E_NOTDIS_Eng_Current_Num_Coded" AS "T_SCOPEEX_E_NOTDIS_Eng_Current_Num_Coded",
    src_1."T_SCOPEEX_M_DIS_Eng_Current_Num_Coded" AS "T_SCOPEEX_M_DIS_Eng_Current_Num_Coded",
    src_1."T_SCOPEEX_M_NOTDIS_Eng_Current_Num_Coded" AS "T_SCOPEEX_M_NOTDIS_Eng_Current_Num_Coded",
    src_1."TALLPPE_ACAD_1618_DIS_Eng_Current_Num_Coded" AS "TALLPPE_ACAD_1618_DIS_Eng_Current_Num_Coded",
    src_1."TALLPPE_ACAD_1618_Eng_Current_Num_Coded" AS "TALLPPE_ACAD_1618_Eng_Current_Num_Coded",
    src_1."TALLPPE_ACAD_1618_Eng_Previous_Num_Coded" AS "TALLPPE_ACAD_1618_Eng_Previous_Num_Coded",
    src_1."TALLPPE_ACAD_1618_Eng_Previous2_Num_Coded" AS "TALLPPE_ACAD_1618_Eng_Previous2_Num_Coded",
    src_1."TALLPPE_ACAD_1618_NOTDIS_Eng_Current_Num_Coded" AS "TALLPPE_ACAD_1618_NOTDIS_Eng_Current_Num_Coded",
    src_1."TALLPPE_AGEN_DIS_Eng_Current_Num_Coded" AS "TALLPPE_AGEN_DIS_Eng_Current_Num_Coded",
    src_1."TALLPPE_AGEN_Eng_Current_Num_Coded" AS "TALLPPE_AGEN_Eng_Current_Num_Coded",
    src_1."TALLPPE_AGEN_Eng_Previous_Num_Coded" AS "TALLPPE_AGEN_Eng_Previous_Num_Coded",
    src_1."TALLPPE_AGEN_Eng_Previous2_Num_Coded" AS "TALLPPE_AGEN_Eng_Previous2_Num_Coded",
    src_1."TALLPPE_AGEN_NOTDIS_Eng_Current_Num_Coded" AS "TALLPPE_AGEN_NOTDIS_Eng_Current_Num_Coded",
    src_1."TALLPPE_ALEV_1618_DIS_Eng_Current_Num_Coded" AS "TALLPPE_ALEV_1618_DIS_Eng_Current_Num_Coded",
    src_1."TALLPPE_ALEV_1618_Eng_Current_Num_Coded" AS "TALLPPE_ALEV_1618_Eng_Current_Num_Coded",
    src_1."TALLPPE_ALEV_1618_Eng_Previous_Num_Coded" AS "TALLPPE_ALEV_1618_Eng_Previous_Num_Coded",
    src_1."TALLPPE_ALEV_1618_Eng_Previous2_Num_Coded" AS "TALLPPE_ALEV_1618_Eng_Previous2_Num_Coded",
    src_1."TALLPPE_ALEV_1618_NOTDIS_Eng_Current_Num_Coded" AS "TALLPPE_ALEV_1618_NOTDIS_Eng_Current_Num_Coded",
    src_1."TALLPPE_TECHCERT_DIS_Eng_Current_Num_Coded" AS "TALLPPE_TECHCERT_DIS_Eng_Current_Num_Coded",
    src_1."TALLPPE_TECHCERT_Eng_Current_Num_Coded" AS "TALLPPE_TECHCERT_Eng_Current_Num_Coded",
    src_1."TALLPPE_TECHCERT_Eng_Previous_Num_Coded" AS "TALLPPE_TECHCERT_Eng_Previous_Num_Coded",
    src_1."TALLPPE_TECHCERT_Eng_Previous2_Num_Coded" AS "TALLPPE_TECHCERT_Eng_Previous2_Num_Coded",
    src_1."TALLPPE_TECHCERT_NOTDIS_Eng_Current_Num_Coded" AS "TALLPPE_TECHCERT_NOTDIS_Eng_Current_Num_Coded",
    src_1."TALLPPE_TLEV_DIS_Eng_Current_Num_Coded" AS "TALLPPE_TLEV_DIS_Eng_Current_Num_Coded",
    src_1."TALLPPE_TLEV_Eng_Current_Num_Coded" AS "TALLPPE_TLEV_Eng_Current_Num_Coded",
    src_1."TALLPPE_TLEV_Eng_Previous_Num_Coded" AS "TALLPPE_TLEV_Eng_Previous_Num_Coded",
    src_1."TALLPPE_TLEV_Eng_Previous2_Num_Coded" AS "TALLPPE_TLEV_Eng_Previous2_Num_Coded",
    src_1."TALLPPE_TLEV_NOTDIS_Eng_Current_Num_Coded" AS "TALLPPE_TLEV_NOTDIS_Eng_Current_Num_Coded",
    src_1."TALLPPEGRD_ACAD_1618_Eng_Current" AS "TALLPPEGRD_ACAD_1618_Eng_Current",
    src_1."TALLPPEGRD_ACAD_1618_Eng_Previous" AS "TALLPPEGRD_ACAD_1618_Eng_Previous",
    src_1."TALLPPEGRD_ACAD_1618_Eng_Previous2" AS "TALLPPEGRD_ACAD_1618_Eng_Previous2",
    src_1."TALLPPEGRD_ACAD_DIS_Eng_Current" AS "TALLPPEGRD_ACAD_DIS_Eng_Current",
    src_1."TALLPPEGRD_ACAD_NOTDIS_Eng_Current" AS "TALLPPEGRD_ACAD_NOTDIS_Eng_Current",
    src_1."TALLPPEGRD_AGEN_DIS_Eng_Current" AS "TALLPPEGRD_AGEN_DIS_Eng_Current",
    src_1."TALLPPEGRD_AGEN_Eng_Current" AS "TALLPPEGRD_AGEN_Eng_Current",
    src_1."TALLPPEGRD_AGEN_Eng_Previous" AS "TALLPPEGRD_AGEN_Eng_Previous",
    src_1."TALLPPEGRD_AGEN_Eng_Previous2" AS "TALLPPEGRD_AGEN_Eng_Previous2",
    src_1."TALLPPEGRD_AGEN_NOTDIS_Eng_Current" AS "TALLPPEGRD_AGEN_NOTDIS_Eng_Current",
    src_1."TALLPPEGRD_ALEV_1618_Eng_Current" AS "TALLPPEGRD_ALEV_1618_Eng_Current",
    src_1."TALLPPEGRD_ALEV_1618_Eng_Previous" AS "TALLPPEGRD_ALEV_1618_Eng_Previous",
    src_1."TALLPPEGRD_ALEV_1618_Eng_Previous2" AS "TALLPPEGRD_ALEV_1618_Eng_Previous2",
    src_1."TALLPPEGRD_ALEV_DIS_Eng_Current" AS "TALLPPEGRD_ALEV_DIS_Eng_Current",
    src_1."TALLPPEGRD_ALEV_NOTDIS_Eng_Current" AS "TALLPPEGRD_ALEV_NOTDIS_Eng_Current",
    src_1."TALLPPEGRD_TECHCERT_DIS_Eng_Current" AS "TALLPPEGRD_TECHCERT_DIS_Eng_Current",
    src_1."TALLPPEGRD_TECHCERT_Eng_Current" AS "TALLPPEGRD_TECHCERT_Eng_Current",
    src_1."TALLPPEGRD_TECHCERT_Eng_Previous" AS "TALLPPEGRD_TECHCERT_Eng_Previous",
    src_1."TALLPPEGRD_TECHCERT_Eng_Previous2" AS "TALLPPEGRD_TECHCERT_Eng_Previous2",
    src_1."TALLPPEGRD_TECHCERT_NOTDIS_Eng_Current" AS "TALLPPEGRD_TECHCERT_NOTDIS_Eng_Current",
    src_1."TALLPPEGRD_TLEV_DIS_Eng_Current" AS "TALLPPEGRD_TLEV_DIS_Eng_Current",
    src_1."TALLPPEGRD_TLEV_Eng_Current" AS "TALLPPEGRD_TLEV_Eng_Current",
    src_1."TALLPPEGRD_TLEV_Eng_Previous" AS "TALLPPEGRD_TLEV_Eng_Previous",
    src_1."TALLPPEGRD_TLEV_Eng_Previous2" AS "TALLPPEGRD_TLEV_Eng_Previous2",
    src_1."TALLPPEGRD_TLEV_NOTDIS_Eng_Current" AS "TALLPPEGRD_TLEV_NOTDIS_Eng_Current",
    src_1."TALLPUP_1618_DIS_Eng_Current_Num_Coded" AS "TALLPUP_1618_DIS_Eng_Current_Num_Coded",
    src_1."TALLPUP_1618_NOTDIS_Eng_Current_Num_Coded" AS "TALLPUP_1618_NOTDIS_Eng_Current_Num_Coded",
    src_1."TALLPUP_ACAD_1618_DIS_Eng_Current_Num_Coded" AS "TALLPUP_ACAD_1618_DIS_Eng_Current_Num_Coded",
    src_1."TALLPUP_ACAD_1618_Eng_Current_Num_Coded" AS "TALLPUP_ACAD_1618_Eng_Current_Num_Coded",
    src_1."TALLPUP_ACAD_1618_Eng_Previous_Num_Coded" AS "TALLPUP_ACAD_1618_Eng_Previous_Num_Coded",
    src_1."TALLPUP_ACAD_1618_Eng_Previous2_Num_Coded" AS "TALLPUP_ACAD_1618_Eng_Previous2_Num_Coded",
    src_1."TALLPUP_ACAD_1618_NOTDIS_Eng_Current_Num_Coded" AS "TALLPUP_ACAD_1618_NOTDIS_Eng_Current_Num_Coded",
    src_1."TALLPUP_AGEN_DIS_Eng_Current_Num_Coded" AS "TALLPUP_AGEN_DIS_Eng_Current_Num_Coded",
    src_1."TALLPUP_AGEN_Eng_Current_Num_Coded" AS "TALLPUP_AGEN_Eng_Current_Num_Coded",
    src_1."TALLPUP_AGEN_Eng_Previous_Num_Coded" AS "TALLPUP_AGEN_Eng_Previous_Num_Coded",
    src_1."TALLPUP_AGEN_Eng_Previous2_Num_Coded" AS "TALLPUP_AGEN_Eng_Previous2_Num_Coded",
    src_1."TALLPUP_AGEN_NOTDIS_Eng_Current_Num_Coded" AS "TALLPUP_AGEN_NOTDIS_Eng_Current_Num_Coded",
    src_1."TALLPUP_ALEV_1618_DIS_Eng_Current_Num_Coded" AS "TALLPUP_ALEV_1618_DIS_Eng_Current_Num_Coded",
    src_1."TALLPUP_ALEV_1618_Eng_Previous_Num_Coded" AS "TALLPUP_ALEV_1618_Eng_Previous_Num_Coded",
    src_1."TALLPUP_ALEV_1618_NOTDIS_Eng_Current_Num_Coded" AS "TALLPUP_ALEV_1618_NOTDIS_Eng_Current_Num_Coded",
    src_1."TALLPUP_ALEV_Eng_Current_Num_Coded" AS "TALLPUP_ALEV_Eng_Current_Num_Coded",
    src_1."TALLPUP_TECHCERT_DIS_Eng_Current_Num_Coded" AS "TALLPUP_TECHCERT_DIS_Eng_Current_Num_Coded",
    src_1."TALLPUP_TECHCERT_Eng_Current_Num_Coded" AS "TALLPUP_TECHCERT_Eng_Current_Num_Coded",
    src_1."TALLPUP_TECHCERT_Eng_Previous_Num_Coded" AS "TALLPUP_TECHCERT_Eng_Previous_Num_Coded",
    src_1."TALLPUP_TECHCERT_NOTDIS_Eng_Current_Num_Coded" AS "TALLPUP_TECHCERT_NOTDIS_Eng_Current_Num_Coded",
    src_1."TALLPUP_TLEV_DIS_Eng_Current_Num_Coded" AS "TALLPUP_TLEV_DIS_Eng_Current_Num_Coded",
    src_1."TALLPUP_TLEV_Eng_Current_Num_Coded" AS "TALLPUP_TLEV_Eng_Current_Num_Coded",
    src_1."TALLPUP_TLEV_Eng_Previous_Num_Coded" AS "TALLPUP_TLEV_Eng_Previous_Num_Coded",
    src_1."TALLPUP_TLEV_NOTDIS_Eng_Current_Num_Coded" AS "TALLPUP_TLEV_NOTDIS_Eng_Current_Num_Coded",
    src_1."TB3PTSE_Eng_Current_Num_Coded" AS "TB3PTSE_Eng_Current_Num_Coded",
    src_1."TB3PTSE_GRD_Eng_Current" AS "TB3PTSE_GRD_Eng_Current",
    src_1."UCI_INS_ACAD_DIS_Eng_Current_Num_Coded" AS "UCI_INS_ACAD_DIS_Eng_Current_Num_Coded",
    src_1."UCI_INS_ACAD_NOTDIS_Eng_Current_Num_Coded" AS "UCI_INS_ACAD_NOTDIS_Eng_Current_Num_Coded",
    src_1."UCI_INS_AGEN_DIS_Eng_Current_Num_Coded" AS "UCI_INS_AGEN_DIS_Eng_Current_Num_Coded",
    src_1."UCI_INS_AGEN_NOTDIS_Eng_Current_Num_Coded" AS "UCI_INS_AGEN_NOTDIS_Eng_Current_Num_Coded",
    src_1."UCI_INS_ALEV_DIS_Eng_Current_Num_Coded" AS "UCI_INS_ALEV_DIS_Eng_Current_Num_Coded",
    src_1."UCI_INS_ALEV_NOTDIS_Eng_Current_Num_Coded" AS "UCI_INS_ALEV_NOTDIS_Eng_Current_Num_Coded",
    src_1."UCI_INS_TECHCERT_DIS_Eng_Current_Num_Coded" AS "UCI_INS_TECHCERT_DIS_Eng_Current_Num_Coded",
    src_1."UCI_INS_TECHCERT_NOTDIS_Eng_Current_Num_Coded" AS "UCI_INS_TECHCERT_NOTDIS_Eng_Current_Num_Coded",
    src_1."UCI_INS_TLEV_DIS_Eng_Current_Num_Coded" AS "UCI_INS_TLEV_DIS_Eng_Current_Num_Coded",
    src_1."UCI_INS_TLEV_NOTDIS_Eng_Current_Num_Coded" AS "UCI_INS_TLEV_NOTDIS_Eng_Current_Num_Coded",
    src_1."VA_INS_ACAD_DIS_Eng_Current_Num_Coded" AS "VA_INS_ACAD_DIS_Eng_Current_Num_Coded",
    src_1."VA_INS_ACAD_Eng_Current_Num_Coded" AS "VA_INS_ACAD_Eng_Current_Num_Coded",
    src_1."VA_INS_ACAD_NOTDIS_Eng_Current_Num_Coded" AS "VA_INS_ACAD_NOTDIS_Eng_Current_Num_Coded",
    src_1."VA_INS_AGEN_DIS_Eng_Current_Num_Coded" AS "VA_INS_AGEN_DIS_Eng_Current_Num_Coded",
    src_1."VA_INS_AGEN_Eng_Current_Num_Coded" AS "VA_INS_AGEN_Eng_Current_Num_Coded",
    src_1."VA_INS_AGEN_NOTDIS_Eng_Current_Num_Coded" AS "VA_INS_AGEN_NOTDIS_Eng_Current_Num_Coded",
    src_1."VA_INS_ALEV_DIS_Eng_Current_Num_Coded" AS "VA_INS_ALEV_DIS_Eng_Current_Num_Coded",
    src_1."VA_INS_ALEV_Eng_Current_Num_Coded" AS "VA_INS_ALEV_Eng_Current_Num_Coded",
    src_1."VA_INS_ALEV_NOTDIS_Eng_Current_Num_Coded" AS "VA_INS_ALEV_NOTDIS_Eng_Current_Num_Coded",
    src_1."VA_INS_TECHCERT_DIS_Eng_Current_Num_Coded" AS "VA_INS_TECHCERT_DIS_Eng_Current_Num_Coded",
    src_1."VA_INS_TECHCERT_Eng_Current_Num_Coded" AS "VA_INS_TECHCERT_Eng_Current_Num_Coded",
    src_1."VA_INS_TECHCERT_NOTDIS_Eng_Current_Num_Coded" AS "VA_INS_TECHCERT_NOTDIS_Eng_Current_Num_Coded",
    src_1."VA_INS_TLEV_DIS_Eng_Current_Num_Coded" AS "VA_INS_TLEV_DIS_Eng_Current_Num_Coded",
    src_1."VA_INS_TLEV_Eng_Current_Num_Coded" AS "VA_INS_TLEV_Eng_Current_Num_Coded",
    src_1."VA_INS_TLEV_NOTDIS_Eng_Current_Num_Coded" AS "VA_INS_TLEV_NOTDIS_Eng_Current_Num_Coded"
FROM all_ids a
LEFT JOIN src_1 ON src_1."Id" = a."Id"
LEFT JOIN src_2 ON src_2."Id" = a."Id"
;
